$axure.loadCurrentPage({
  "url":"editar_canal.html",
  "generationDate":new Date(1423764013758.69),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"7eabd6578c4847889177ee213b6b3d9b",
    "type":"Axure:Page",
    "name":"Editar canal",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"ad5fb82a34004b22b5dcdef014582e62",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "size":{
              "width":980,
              "height":990},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e865d69a062d49b08c895d84f52e2eac",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "size":{
                  "width":980,
                  "height":990},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/editar_canal/u0.png"}},
{
          "id":"8f38cb583df640fe8b0aafd890bb4eeb",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":950},
            "size":{
              "width":1277,
              "height":33}},
          "adaptiveStyles":{
},
          "masterId":"4226023da38e45578b3ec7ef42593243"},
{
          "id":"bfc248ea12b74832a4ab6da2915f183e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":15,
              "y":52},
            "size":{
              "width":545,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"24f8842010964ede9587a4438e58e008",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":15,
                  "y":52},
                "size":{
                  "width":545,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"27a970e902d94d84b2e5a31fd5c2783c",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":34,
              "y":138},
            "size":{
              "width":446,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"79e61e0923cb4587857eda8c2f2ae2e4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":34,
                  "y":138},
                "size":{
                  "width":446,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a1997c0e97294d519b53bfcd26d5bcd6",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"fbc37d401c784c2abad213112443341e"},
{
          "id":"9f2e86a0178a42d98971be7fa66c9698",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":34,
              "y":214},
            "size":{
              "width":326,
              "height":32},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4e83b326b6434fccb61296dd41579943",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":34,
                  "y":214},
                "size":{
                  "width":326,
                  "height":32},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/novo_canal/u40.png"}},
{
          "id":"b9d21d6d65964af4a44ca99e02c73ad0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":35,
              "y":190},
            "size":{
              "width":220,
              "height":17},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4b1e574b621f4048a379e9aa0a034cd5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":35,
                  "y":190},
                "size":{
                  "width":220,
                  "height":17},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"081150b141004317aee39e9cf071ae5b",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"12px",
            "fontWeight":"400",
            "underline":true,
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0066FF,
              "opacity":1},
            "location":{
              "x":34,
              "y":112},
            "size":{
              "width":216,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cceae6be835047df919ccc99ac5a6e2c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"12px",
                "fontWeight":"400",
                "underline":true,
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0066FF,
                  "opacity":1},
                "location":{
                  "x":34,
                  "y":112},
                "size":{
                  "width":216,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Forum in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"forum.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d32d7329821643f9b132729a6f624a8b",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"12px",
            "fontWeight":"400",
            "underline":true,
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0066FF,
              "opacity":1},
            "location":{
              "x":34,
              "y":720},
            "size":{
              "width":236,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9cdb61bb6e334c75a367714afa5c9c7f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"12px",
                "fontWeight":"400",
                "underline":true,
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0066FF,
                  "opacity":1},
                "location":{
                  "x":34,
                  "y":720},
                "size":{
                  "width":236,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Forum in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"forum.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7896512d4f414f3cb4feab890fdc54ce",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":34,
              "y":690},
            "size":{
              "width":876,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/alterar_senha/u42_line.png"}},
{
          "id":"874472199b024a54b9b67a08982ccb75",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negrito', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF0099FF},
            "location":{
              "x":34,
              "y":390},
            "size":{
              "width":96,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"57b865993f8449d0a5fab011966a9c55",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negrito', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0099FF},
                "location":{
                  "x":34,
                  "y":390},
                "size":{
                  "width":96,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"2"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Forum in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"forum.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/novo_lembrete_status1/u42.png"}},
{
          "id":"d595b453b64944318a9c71ca4b04c706",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":35,
              "y":280},
            "size":{
              "width":95,
              "height":17},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6958cb951dcf4a61b5e6ecf3e234193f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":35,
                  "y":280},
                "size":{
                  "width":95,
                  "height":17},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ed7a14dcccfd40b499bf70743eca3a54",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":35,
              "y":320},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f473a08ff7a74357bbb3dd25e8662dc1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":35,
                  "y":320},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"096e06512c854d0e958e3127f4ccd3bb",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":130,
              "y":320},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c963fdf667734269b5147d6b9c496b7f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":130,
                  "y":320},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]}]}},
  "masters":{
    "4226023da38e45578b3ec7ef42593243":{
      "packageId":"4226023da38e45578b3ec7ef42593243",
      "type":"Axure:Master",
      "name":"footer",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"98f6e95fccd74ca4a04a4a23229806bc",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"12px",
              "verticalAlignment":"middle",
              "fill":{
                "fillType":"solid",
                "color":0xFFF2F2F2},
              "location":{
                "x":240,
                "y":0},
              "size":{
                "width":780,
                "height":40}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"4c99a36cd31f4770a5042ff302db729c",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"12px",
                  "verticalAlignment":"middle",
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2},
                  "location":{
                    "x":240,
                    "y":0},
                  "size":{
                    "width":780,
                    "height":40}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/cadastro/u3.png"}}]}},
    "fbc37d401c784c2abad213112443341e":{
      "packageId":"fbc37d401c784c2abad213112443341e",
      "type":"Axure:Master",
      "name":"header_gerente",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"a98ffd8705e040929b7ec88c6bbc264e",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "size":{
                "width":980,
                "height":80},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8ab6195fdb274feb89b20710a3fc5997",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":980,
                    "height":80},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/alterar_senha/u6.png"}},
{
            "id":"fa8b587736bf4c6ea418fcbeaa262c99",
            "label":"",
            "type":"verticalLine",
            "styleType":"verticalLine",
            "visible":true,
            "style":{
              "location":{
                "x":284,
                "y":0},
              "size":{
                "width":10,
                "height":81},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFE4E4E4}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/alterar_senha/u8_line.png"}},
{
            "id":"fe49e2a706744e048a3667060b9a3e69",
            "label":"dropdown-user",
            "type":"dynamicPanel",
            "styleType":"dynamicPanel",
            "visible":true,
            "style":{
              "location":{
                "x":780,
                "y":22},
              "size":{
                "width":200,
                "height":138}},
            "adaptiveStyles":{
},
            "scrollbars":"none",
            "fitToContent":false,
            "propagate":false,
            "diagrams":[{
                "id":"9988237930104c0f96653f270533b92b",
                "label":"State1",
                "type":"Axure:PanelDiagram",
                "objects":[{
                    "id":"6204713e832042c18bfcced89f8bce20",
                    "label":"",
                    "parentDynamicPanel":"fe49e2a706744e048a3667060b9a3e69",
                    "panelIndex":0,
                    "type":"buttonShape",
                    "styleType":"paragraph",
                    "visible":true,
                    "style":{
                      "fontName":"'Helvetica Neue'",
                      "fontSize":"18px",
                      "horizontalAlignment":"right",
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF666666,
                        "opacity":1},
                      "location":{
                        "x":54,
                        "y":18},
                      "size":{
                        "width":92,
                        "height":22}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"62986fe513794f9c8abec46cde2877a7",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"fe49e2a706744e048a3667060b9a3e69",
                        "panelIndex":0,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontName":"'Helvetica Neue'",
                          "fontSize":"18px",
                          "horizontalAlignment":"right",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFF666666,
                            "opacity":1},
                          "location":{
                            "x":54,
                            "y":18},
                          "size":{
                            "width":92,
                            "height":22}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"c076f0909fb542b49a704785b1078434",
                    "label":"",
                    "parentDynamicPanel":"fe49e2a706744e048a3667060b9a3e69",
                    "panelIndex":0,
                    "type":"buttonShape",
                    "styleType":"paragraph",
                    "visible":true,
                    "style":{
                      "fontName":"'Helvetica Neue'",
                      "fontSize":"12px",
                      "horizontalAlignment":"right",
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF666666,
                        "opacity":1},
                      "location":{
                        "x":79,
                        "y":0},
                      "size":{
                        "width":66,
                        "height":14}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"c925cae17de947179805ef69d39926c2",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"fe49e2a706744e048a3667060b9a3e69",
                        "panelIndex":0,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontName":"'Helvetica Neue'",
                          "fontSize":"12px",
                          "horizontalAlignment":"right",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFF666666,
                            "opacity":1},
                          "location":{
                            "x":79,
                            "y":0},
                          "size":{
                            "width":66,
                            "height":14}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"11cf14182664433ebd8e6f1a0ee85ffe",
                    "label":"",
                    "parentDynamicPanel":"fe49e2a706744e048a3667060b9a3e69",
                    "panelIndex":0,
                    "type":"imageBox",
                    "styleType":"imageBox",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":162,
                        "y":4},
                      "size":{
                        "width":28,
                        "height":28}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"9a3f85fce4df4d77b97c4565d725eec5",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"fe49e2a706744e048a3667060b9a3e69",
                        "panelIndex":0,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":162,
                            "y":4},
                          "size":{
                            "width":28,
                            "height":28}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/alterar_senha/u14.png"}},
{
                    "id":"f6b7572cbf4c448c9f6afbaa10bfad13",
                    "label":"",
                    "parentDynamicPanel":"fe49e2a706744e048a3667060b9a3e69",
                    "panelIndex":0,
                    "type":"imageMapRegion",
                    "styleType":"imageMapRegion",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":155,
                        "y":0},
                      "size":{
                        "width":40,
                        "height":40}},
                    "adaptiveStyles":{
},
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"setPanelState",
                                "description":"Set dropdown-user to State2",
                                "panelsToStates":[{
                                    "panelPath":["fe49e2a706744e048a3667060b9a3e69"],
                                    "stateInfo":{
                                      "setStateType":"diagram",
                                      "stateNumber":2,
                                      "stateValue":{
                                        "exprType":"stringLiteral",
                                        "value":"1",
                                        "stos":[]},
                                      "loop":false,
                                      "showWhenSet":false,
                                      "options":{
                                        "compress":false}}}]}]}]}},
                    "tabbable":true}],
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFFFFF},
                  "image":null,
                  "imageHorizontalAlignment":"near",
                  "imageVerticalAlignment":"near",
                  "imageRepeat":"auto"},
                "adaptiveStyles":{
}},
{
                "id":"5ab577ad4f0d4fea8d6efa85d310a7cd",
                "label":"State2",
                "type":"Axure:PanelDiagram",
                "objects":[{
                    "id":"9ed6828666f447f7a7e0ceb44c3afe85",
                    "label":"",
                    "parentDynamicPanel":"fe49e2a706744e048a3667060b9a3e69",
                    "panelIndex":1,
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFE4E4E4},
                      "location":{
                        "x":0,
                        "y":47},
                      "size":{
                        "width":200,
                        "height":83},
                      "borderFill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "cornerRadiusTopLeft":"5"},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"bd713743a4fd4100b43ccca1b70ca994",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"fe49e2a706744e048a3667060b9a3e69",
                        "panelIndex":1,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFE4E4E4},
                          "location":{
                            "x":0,
                            "y":47},
                          "size":{
                            "width":200,
                            "height":83},
                          "borderFill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "cornerRadiusTopLeft":"5"},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/alterar_senha/u17.png"}},
{
                    "id":"c45b355677264302bfe15da0b7663744",
                    "label":"",
                    "parentDynamicPanel":"fe49e2a706744e048a3667060b9a3e69",
                    "panelIndex":1,
                    "type":"buttonShape",
                    "styleType":"paragraph",
                    "visible":true,
                    "style":{
                      "fontSize":"14px",
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF0066FF,
                        "opacity":1},
                      "location":{
                        "x":20,
                        "y":58},
                      "size":{
                        "width":170,
                        "height":16},
                      "rotation":"0",
                      "textRotation":"0"},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"3dee6155c57042de849e03626aa42332",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"fe49e2a706744e048a3667060b9a3e69",
                        "panelIndex":1,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontSize":"14px",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFF0066FF,
                            "opacity":1},
                          "location":{
                            "x":20,
                            "y":58},
                          "size":{
                            "width":170,
                            "height":16},
                          "rotation":"0",
                          "textRotation":"0"},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"Open Alterar senha in Current Window",
                                "target":{
                                  "targetType":"page",
                                  "url":"alterar_senha.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"5b7ee831d3d94eb7bcd42535e0e07829",
                    "label":"",
                    "parentDynamicPanel":"fe49e2a706744e048a3667060b9a3e69",
                    "panelIndex":1,
                    "type":"horizontalLine",
                    "styleType":"horizontalLine",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":0,
                        "y":82},
                      "size":{
                        "width":200,
                        "height":10},
                      "borderFill":{
                        "fillType":"solid",
                        "color":0xFFCCCCCC}},
                    "adaptiveStyles":{
},
                    "images":{
                      "start~":"resources/images/transparent.gif",
                      "end~":"resources/images/transparent.gif",
                      "line~":"images/alterar_senha/u21_line.png"}},
{
                    "id":"78e83a886be14343987e121a22698ce9",
                    "label":"",
                    "parentDynamicPanel":"fe49e2a706744e048a3667060b9a3e69",
                    "panelIndex":1,
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFE4E4E4},
                      "location":{
                        "x":166,
                        "y":36},
                      "size":{
                        "width":20,
                        "height":15},
                      "borderFill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "cornerRadiusTopLeft":"5"},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"048b499446c24a21965e02b1a1c2cda1",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"fe49e2a706744e048a3667060b9a3e69",
                        "panelIndex":1,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFE4E4E4},
                          "location":{
                            "x":166,
                            "y":36},
                          "size":{
                            "width":20,
                            "height":15},
                          "borderFill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "cornerRadiusTopLeft":"5"},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/alterar_senha/u22.png"}},
{
                    "id":"e07433f9f99a4fcca3478cabd32cb61e",
                    "label":"",
                    "parentDynamicPanel":"fe49e2a706744e048a3667060b9a3e69",
                    "panelIndex":1,
                    "type":"buttonShape",
                    "styleType":"paragraph",
                    "visible":true,
                    "style":{
                      "fontName":"'Helvetica Neue'",
                      "fontSize":"18px",
                      "horizontalAlignment":"right",
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF666666,
                        "opacity":1},
                      "location":{
                        "x":54,
                        "y":18},
                      "size":{
                        "width":92,
                        "height":22}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"87c0a50ec8474ff2a48c7489776d6e3c",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"fe49e2a706744e048a3667060b9a3e69",
                        "panelIndex":1,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontName":"'Helvetica Neue'",
                          "fontSize":"18px",
                          "horizontalAlignment":"right",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFF666666,
                            "opacity":1},
                          "location":{
                            "x":54,
                            "y":18},
                          "size":{
                            "width":92,
                            "height":22}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"1e467f8e63d14e87b4967a32746222e9",
                    "label":"",
                    "parentDynamicPanel":"fe49e2a706744e048a3667060b9a3e69",
                    "panelIndex":1,
                    "type":"buttonShape",
                    "styleType":"paragraph",
                    "visible":true,
                    "style":{
                      "fontName":"'Helvetica Neue'",
                      "fontSize":"12px",
                      "horizontalAlignment":"right",
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF666666,
                        "opacity":1},
                      "location":{
                        "x":79,
                        "y":0},
                      "size":{
                        "width":66,
                        "height":14}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"b19b8a20efe044748b51ac5b68a88f23",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"fe49e2a706744e048a3667060b9a3e69",
                        "panelIndex":1,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontName":"'Helvetica Neue'",
                          "fontSize":"12px",
                          "horizontalAlignment":"right",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFF666666,
                            "opacity":1},
                          "location":{
                            "x":79,
                            "y":0},
                          "size":{
                            "width":66,
                            "height":14}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"b8608e9f638b4660a8a6dee7aa9c3e36",
                    "label":"",
                    "parentDynamicPanel":"fe49e2a706744e048a3667060b9a3e69",
                    "panelIndex":1,
                    "type":"imageBox",
                    "styleType":"imageBox",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":162,
                        "y":4},
                      "size":{
                        "width":28,
                        "height":28}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"a559e57a14854d24a4609485d50f1ed3",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"fe49e2a706744e048a3667060b9a3e69",
                        "panelIndex":1,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":162,
                            "y":4},
                          "size":{
                            "width":28,
                            "height":28}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/alterar_senha/u14.png"}},
{
                    "id":"fda57ffd0f054a0d897d3b093d669bdd",
                    "label":"",
                    "parentDynamicPanel":"fe49e2a706744e048a3667060b9a3e69",
                    "panelIndex":1,
                    "type":"buttonShape",
                    "styleType":"paragraph",
                    "visible":true,
                    "style":{
                      "fontSize":"14px",
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF0066FF,
                        "opacity":1},
                      "location":{
                        "x":20,
                        "y":99},
                      "size":{
                        "width":170,
                        "height":16},
                      "rotation":"0",
                      "textRotation":"0"},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"5cc804455eb0464b85ff7cc456067800",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"fe49e2a706744e048a3667060b9a3e69",
                        "panelIndex":1,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontSize":"14px",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFF0066FF,
                            "opacity":1},
                          "location":{
                            "x":20,
                            "y":99},
                          "size":{
                            "width":170,
                            "height":16},
                          "rotation":"0",
                          "textRotation":"0"},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"Open Cadastro in Current Window",
                                "target":{
                                  "targetType":"page",
                                  "url":"cadastro.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"a6aab5213b4b4c3e85ac4afe1f257e91",
                    "label":"",
                    "parentDynamicPanel":"fe49e2a706744e048a3667060b9a3e69",
                    "panelIndex":1,
                    "type":"imageMapRegion",
                    "styleType":"imageMapRegion",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":155,
                        "y":0},
                      "size":{
                        "width":40,
                        "height":40}},
                    "adaptiveStyles":{
},
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"setPanelState",
                                "description":"Set dropdown-user to State1",
                                "panelsToStates":[{
                                    "panelPath":["fe49e2a706744e048a3667060b9a3e69"],
                                    "stateInfo":{
                                      "setStateType":"diagram",
                                      "stateNumber":1,
                                      "stateValue":{
                                        "exprType":"stringLiteral",
                                        "value":"1",
                                        "stos":[]},
                                      "loop":false,
                                      "showWhenSet":false,
                                      "options":{
                                        "compress":false}}}]}]}]}},
                    "tabbable":true}],
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFFFFF},
                  "image":null,
                  "imageHorizontalAlignment":"near",
                  "imageVerticalAlignment":"near",
                  "imageRepeat":"auto"},
                "adaptiveStyles":{
}}]},
{
            "id":"5280f6ab2ff541e3a08d602a96f14af5",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":8,
                "y":22},
              "size":{
                "width":252,
                "height":37}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"62a6cea60ded4fa9a507f5f197608b58",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":8,
                    "y":22},
                  "size":{
                    "width":252,
                    "height":37}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/cadastro/u19.png"}},
{
            "id":"fe5658b4dd484718b4046ef0c1c59a08",
            "label":"",
            "type":"imageMapRegion",
            "styleType":"imageMapRegion",
            "visible":true,
            "style":{
              "size":{
                "width":294,
                "height":81}},
            "adaptiveStyles":{
},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Dashboard in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"dashboard.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true}]}}},
  "objectPaths":{
    "ad5fb82a34004b22b5dcdef014582e62":{
      "scriptId":"u0"},
    "e865d69a062d49b08c895d84f52e2eac":{
      "scriptId":"u1"},
    "8f38cb583df640fe8b0aafd890bb4eeb":{
      "scriptId":"u2",
      "98f6e95fccd74ca4a04a4a23229806bc":{
        "scriptId":"u3"},
      "4c99a36cd31f4770a5042ff302db729c":{
        "scriptId":"u4"}},
    "bfc248ea12b74832a4ab6da2915f183e":{
      "scriptId":"u5"},
    "24f8842010964ede9587a4438e58e008":{
      "scriptId":"u6"},
    "27a970e902d94d84b2e5a31fd5c2783c":{
      "scriptId":"u7"},
    "79e61e0923cb4587857eda8c2f2ae2e4":{
      "scriptId":"u8"},
    "a1997c0e97294d519b53bfcd26d5bcd6":{
      "scriptId":"u9",
      "a98ffd8705e040929b7ec88c6bbc264e":{
        "scriptId":"u10"},
      "8ab6195fdb274feb89b20710a3fc5997":{
        "scriptId":"u11"},
      "fa8b587736bf4c6ea418fcbeaa262c99":{
        "scriptId":"u12"},
      "fe49e2a706744e048a3667060b9a3e69":{
        "scriptId":"u13"},
      "6204713e832042c18bfcced89f8bce20":{
        "scriptId":"u14"},
      "62986fe513794f9c8abec46cde2877a7":{
        "scriptId":"u15"},
      "c076f0909fb542b49a704785b1078434":{
        "scriptId":"u16"},
      "c925cae17de947179805ef69d39926c2":{
        "scriptId":"u17"},
      "11cf14182664433ebd8e6f1a0ee85ffe":{
        "scriptId":"u18"},
      "9a3f85fce4df4d77b97c4565d725eec5":{
        "scriptId":"u19"},
      "f6b7572cbf4c448c9f6afbaa10bfad13":{
        "scriptId":"u20"},
      "9ed6828666f447f7a7e0ceb44c3afe85":{
        "scriptId":"u21"},
      "bd713743a4fd4100b43ccca1b70ca994":{
        "scriptId":"u22"},
      "c45b355677264302bfe15da0b7663744":{
        "scriptId":"u23"},
      "3dee6155c57042de849e03626aa42332":{
        "scriptId":"u24"},
      "5b7ee831d3d94eb7bcd42535e0e07829":{
        "scriptId":"u25"},
      "78e83a886be14343987e121a22698ce9":{
        "scriptId":"u26"},
      "048b499446c24a21965e02b1a1c2cda1":{
        "scriptId":"u27"},
      "e07433f9f99a4fcca3478cabd32cb61e":{
        "scriptId":"u28"},
      "87c0a50ec8474ff2a48c7489776d6e3c":{
        "scriptId":"u29"},
      "1e467f8e63d14e87b4967a32746222e9":{
        "scriptId":"u30"},
      "b19b8a20efe044748b51ac5b68a88f23":{
        "scriptId":"u31"},
      "b8608e9f638b4660a8a6dee7aa9c3e36":{
        "scriptId":"u32"},
      "a559e57a14854d24a4609485d50f1ed3":{
        "scriptId":"u33"},
      "fda57ffd0f054a0d897d3b093d669bdd":{
        "scriptId":"u34"},
      "5cc804455eb0464b85ff7cc456067800":{
        "scriptId":"u35"},
      "a6aab5213b4b4c3e85ac4afe1f257e91":{
        "scriptId":"u36"},
      "5280f6ab2ff541e3a08d602a96f14af5":{
        "scriptId":"u37"},
      "62a6cea60ded4fa9a507f5f197608b58":{
        "scriptId":"u38"},
      "fe5658b4dd484718b4046ef0c1c59a08":{
        "scriptId":"u39"}},
    "9f2e86a0178a42d98971be7fa66c9698":{
      "scriptId":"u40"},
    "4e83b326b6434fccb61296dd41579943":{
      "scriptId":"u41"},
    "b9d21d6d65964af4a44ca99e02c73ad0":{
      "scriptId":"u42"},
    "4b1e574b621f4048a379e9aa0a034cd5":{
      "scriptId":"u43"},
    "081150b141004317aee39e9cf071ae5b":{
      "scriptId":"u44"},
    "cceae6be835047df919ccc99ac5a6e2c":{
      "scriptId":"u45"},
    "d32d7329821643f9b132729a6f624a8b":{
      "scriptId":"u46"},
    "9cdb61bb6e334c75a367714afa5c9c7f":{
      "scriptId":"u47"},
    "7896512d4f414f3cb4feab890fdc54ce":{
      "scriptId":"u48"},
    "874472199b024a54b9b67a08982ccb75":{
      "scriptId":"u49"},
    "57b865993f8449d0a5fab011966a9c55":{
      "scriptId":"u50"},
    "d595b453b64944318a9c71ca4b04c706":{
      "scriptId":"u51"},
    "6958cb951dcf4a61b5e6ecf3e234193f":{
      "scriptId":"u52"},
    "ed7a14dcccfd40b499bf70743eca3a54":{
      "scriptId":"u53"},
    "f473a08ff7a74357bbb3dd25e8662dc1":{
      "scriptId":"u54"},
    "096e06512c854d0e958e3127f4ccd3bb":{
      "scriptId":"u55"},
    "c963fdf667734269b5147d6b9c496b7f":{
      "scriptId":"u56"}}});