$axure.loadCurrentPage({
  "url":"tratamento_de_erro__cadastro_existente.html",
  "generationDate":new Date(1423764001988.71),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"1224034e8a024641a5dc006f1e335ff3",
    "type":"Axure:Page",
    "name":"Tratamento de erro: cadastro existente",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"3afcab086b9d4f3ea68a36897c8a16d0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "size":{
              "width":980,
              "height":850},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2b8935506b614096a31c2b63c2194d74",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "size":{
                  "width":980,
                  "height":850},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/cadastro/u0.png"}},
{
          "id":"274386b779fa4e6999451bd15fd2ba41",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":810},
            "size":{
              "width":1277,
              "height":33}},
          "adaptiveStyles":{
},
          "masterId":"4226023da38e45578b3ec7ef42593243"},
{
          "id":"f7ccf2a841ff4d3084a5a45fb4dcd8a3",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "horizontalAlignment":"center",
            "location":{
              "x":300,
              "y":127},
            "size":{
              "width":363,
              "height":38}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"71e8a82d74bb48dd9f031177c42a5a0f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "horizontalAlignment":"center",
                "location":{
                  "x":300,
                  "y":127},
                "size":{
                  "width":363,
                  "height":38}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b0c500079f294f788ab81e656c3ee3fa",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":272,
              "y":220},
            "size":{
              "width":440,
              "height":410},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"4",
            "outerShadow":{
              "on":true,
              "offsetX":0,
              "offsetY":4,
              "blurRadius":3,
              "color":{
                "r":134,
                "g":134,
                "b":134,
                "a":0.219607843137255}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bbb7310fd0e54cad840baf7885de66a8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":272,
                  "y":220},
                "size":{
                  "width":440,
                  "height":410},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"4",
                "outerShadow":{
                  "on":true,
                  "offsetX":0,
                  "offsetY":4,
                  "blurRadius":3,
                  "color":{
                    "r":134,
                    "g":134,
                    "b":134,
                    "a":0.219607843137255}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/cadastro/u7.png"}},
{
          "id":"b3422790719344fb8b17e7c98360169b",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":302,
              "y":285},
            "size":{
              "width":380,
              "height":45}},
          "adaptiveStyles":{
}},
{
          "id":"05d1ee5ab7904d478e70b2d0ab87494b",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":302,
              "y":345},
            "size":{
              "width":380,
              "height":45}},
          "adaptiveStyles":{
}},
{
          "id":"362ab529266546d69cb2e97c58c4bde0",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":302,
              "y":404},
            "size":{
              "width":380,
              "height":45}},
          "adaptiveStyles":{
}},
{
          "id":"c823bed4652345d5a883051c1a9c0f2c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negrito', 'Arial'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF0099FF},
            "location":{
              "x":302,
              "y":560},
            "size":{
              "width":380,
              "height":41},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9c66aa4f06ab48ef90e4d438c98e6e9b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negrito', 'Arial'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0099FF},
                "location":{
                  "x":302,
                  "y":560},
                "size":{
                  "width":380,
                  "height":41},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"2"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/cadastro/u12.png"}},
{
          "id":"8f77f47b96ad42a89b355992d4de6757",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":302,
              "y":459},
            "size":{
              "width":350,
              "height":14},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"41fe3ec4a443447ca11b84be94896de2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":302,
                  "y":459},
                "size":{
                  "width":350,
                  "height":14},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2e3875d329e74b88b45b8b0022882ef3",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":302,
              "y":490},
            "size":{
              "width":380,
              "height":45}},
          "adaptiveStyles":{
}},
{
          "id":"5acb99b614dd4e81a7fb9e37c3a7af89",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":302,
              "y":247},
            "size":{
              "width":253,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"61f93b3c6da2432095b03bf33b5a3fb0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":302,
                  "y":247},
                "size":{
                  "width":253,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0cc56a821cca4a1f8548b3d23406dcda",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negrito', 'Arial'",
            "fontWeight":"700",
            "fill":{
              "fillType":"solid",
              "color":0xE0FFFFCC},
            "location":{
              "x":77,
              "y":-10},
            "size":{
              "width":790,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6d8cc74d63db4f1fa63f9626c4d2a609",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negrito', 'Arial'",
                "fontWeight":"700",
                "fill":{
                  "fillType":"solid",
                  "color":0xE0FFFFCC},
                "location":{
                  "x":77,
                  "y":-10},
                "size":{
                  "width":790,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/tratamento_de_erro__cadastro_existente/u19.png"}},
{
          "id":"c645b488358b4327923c647a2ef4d744",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":794,
              "y":0},
            "size":{
              "width":30,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c5f9a6e365dd4a9e9d021fd8828988bb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":794,
                  "y":0},
                "size":{
                  "width":30,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/tratamento_de_erro__cadastro_existente/u21.png"}},
{
          "id":"b22cd6dc1c4a41f9bd572d1dd9727ecf",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":358,
              "y":60},
            "size":{
              "width":252,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5bf2c4a8971b49c9b2373279b89f4313",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":358,
                  "y":60},
                "size":{
                  "width":252,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/cadastro/u19.png"}}]}},
  "masters":{
    "4226023da38e45578b3ec7ef42593243":{
      "packageId":"4226023da38e45578b3ec7ef42593243",
      "type":"Axure:Master",
      "name":"footer",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"98f6e95fccd74ca4a04a4a23229806bc",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"12px",
              "verticalAlignment":"middle",
              "fill":{
                "fillType":"solid",
                "color":0xFFF2F2F2},
              "location":{
                "x":240,
                "y":0},
              "size":{
                "width":780,
                "height":40}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"4c99a36cd31f4770a5042ff302db729c",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"12px",
                  "verticalAlignment":"middle",
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2},
                  "location":{
                    "x":240,
                    "y":0},
                  "size":{
                    "width":780,
                    "height":40}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/cadastro/u3.png"}}]}}},
  "objectPaths":{
    "3afcab086b9d4f3ea68a36897c8a16d0":{
      "scriptId":"u0"},
    "2b8935506b614096a31c2b63c2194d74":{
      "scriptId":"u1"},
    "274386b779fa4e6999451bd15fd2ba41":{
      "scriptId":"u2",
      "98f6e95fccd74ca4a04a4a23229806bc":{
        "scriptId":"u3"},
      "4c99a36cd31f4770a5042ff302db729c":{
        "scriptId":"u4"}},
    "f7ccf2a841ff4d3084a5a45fb4dcd8a3":{
      "scriptId":"u5"},
    "71e8a82d74bb48dd9f031177c42a5a0f":{
      "scriptId":"u6"},
    "b0c500079f294f788ab81e656c3ee3fa":{
      "scriptId":"u7"},
    "bbb7310fd0e54cad840baf7885de66a8":{
      "scriptId":"u8"},
    "b3422790719344fb8b17e7c98360169b":{
      "scriptId":"u9"},
    "05d1ee5ab7904d478e70b2d0ab87494b":{
      "scriptId":"u10"},
    "362ab529266546d69cb2e97c58c4bde0":{
      "scriptId":"u11"},
    "c823bed4652345d5a883051c1a9c0f2c":{
      "scriptId":"u12"},
    "9c66aa4f06ab48ef90e4d438c98e6e9b":{
      "scriptId":"u13"},
    "8f77f47b96ad42a89b355992d4de6757":{
      "scriptId":"u14"},
    "41fe3ec4a443447ca11b84be94896de2":{
      "scriptId":"u15"},
    "2e3875d329e74b88b45b8b0022882ef3":{
      "scriptId":"u16"},
    "5acb99b614dd4e81a7fb9e37c3a7af89":{
      "scriptId":"u17"},
    "61f93b3c6da2432095b03bf33b5a3fb0":{
      "scriptId":"u18"},
    "0cc56a821cca4a1f8548b3d23406dcda":{
      "scriptId":"u19"},
    "6d8cc74d63db4f1fa63f9626c4d2a609":{
      "scriptId":"u20"},
    "c645b488358b4327923c647a2ef4d744":{
      "scriptId":"u21"},
    "c5f9a6e365dd4a9e9d021fd8828988bb":{
      "scriptId":"u22"},
    "b22cd6dc1c4a41f9bd572d1dd9727ecf":{
      "scriptId":"u23"},
    "5bf2c4a8971b49c9b2373279b89f4313":{
      "scriptId":"u24"}}});