$axure.loadCurrentPage({
  "url":"detalhe_calendario_dia.html",
  "generationDate":new Date(1423764010983.99),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"dc4683bf2aa2412098e020b8f80c4482",
    "type":"Axure:Page",
    "name":"Detalhe_calendario_dia",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"c55b641589fa43c8b088ca4aab5d4a57",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "size":{
              "width":980,
              "height":1630},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"22d495609e0745e5a0ae69d35940d195",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "size":{
                  "width":980,
                  "height":1630},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/detalhe_calendario_dia/u0.png"}},
{
          "id":"cb6e95cdba7d46dcb6b26ef506f17169",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":1590},
            "size":{
              "width":780,
              "height":40}},
          "adaptiveStyles":{
},
          "masterId":"4226023da38e45578b3ec7ef42593243"},
{
          "id":"f4379b2d037d4dbe884f6787fc0a0436",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"fbc37d401c784c2abad213112443341e"},
{
          "id":"183881b7ccdc435ab64e34b97fe44fc3",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":34,
              "y":138},
            "size":{
              "width":446,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"68843d8396ec418b8a15ff21e790eae1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":34,
                  "y":138},
                "size":{
                  "width":446,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f59228cc097846c7aa061cca1267511a",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"12px",
            "fontWeight":"400",
            "underline":true,
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0066FF,
              "opacity":1},
            "location":{
              "x":34,
              "y":112},
            "size":{
              "width":196,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fa8402e32e6a4c5fbdfa7c41a06dbfeb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"12px",
                "fontWeight":"400",
                "underline":true,
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0066FF,
                  "opacity":1},
                "location":{
                  "x":34,
                  "y":112},
                "size":{
                  "width":196,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Calendario in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"calendario.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"23f4533711fc4fd7824027d446cd351a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":34,
              "y":350},
            "size":{
              "width":916,
              "height":1160},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3b5e248c44a2413ca5d2e84dda5e6052",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":34,
                  "y":350},
                "size":{
                  "width":916,
                  "height":1160},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/detalhe_calendario_dia/u40.png"}},
{
          "id":"f9501775bcb34f779ec24983b865ff75",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF3F3F3},
            "location":{
              "x":57,
              "y":370},
            "size":{
              "width":103,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"746333f1d7814f07b867f2a69d61f540",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF3F3F3},
                "location":{
                  "x":57,
                  "y":370},
                "size":{
                  "width":103,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/detalhe_calendario_mes/u44.png"}},
{
          "id":"7a8b3d13ec3e4638a0c49623905b1e6a",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":104,
              "y":370},
            "size":{
              "width":10,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/detalhe_calendario_mes/u46_line.png"}},
{
          "id":"05c3ba82355343d69c63b128d1fbb7e2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF646464},
            "location":{
              "x":78,
              "y":386},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9f49121bb4b14350a1d212010ab589b7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF646464},
                "location":{
                  "x":78,
                  "y":386},
                "size":{
                  "width":10,
                  "height":10}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/detalhe_calendario_mes/u47.png"}},
{
          "id":"3f30b9999ba54a27b12174b5561de428",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF646464},
            "location":{
              "x":131,
              "y":386},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3b9c904517904e859f025891ffb690b4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF646464},
                "location":{
                  "x":131,
                  "y":386},
                "size":{
                  "width":10,
                  "height":10}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/detalhe_calendario_mes/u49.png"}},
{
          "id":"0b32928b9e8d4ca389ed45969910dc03",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF32323A},
            "location":{
              "x":170,
              "y":370},
            "size":{
              "width":70,
              "height":40},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5bb79ac1971249f8accb818d3beaab0c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF32323A},
                "location":{
                  "x":170,
                  "y":370},
                "size":{
                  "width":70,
                  "height":40},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/detalhe_calendario_mes/u51.png"}},
{
          "id":"1e8d227ec07147dab03b2a1f5e0c4d21",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":260,
              "y":380},
            "size":{
              "width":320,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6959633c375c4ecf9a813d266414305a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":260,
                  "y":380},
                "size":{
                  "width":320,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"05f06a7d3cec4773b4307642e1004a38",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099FF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFF3F3F3},
            "location":{
              "x":690,
              "y":370},
            "size":{
              "width":80,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c0e4eb80e7ca4f46a4e6742c768fce6f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF3F3F3},
                "location":{
                  "x":690,
                  "y":370},
                "size":{
                  "width":80,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Detalhe_calendario_mes in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"detalhe_calendario_mes.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/detalhe_calendario_mes/u57.png"}},
{
          "id":"6a6d5f5cc76f421a93e71574f4902303",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099FF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFF3F3F3},
            "location":{
              "x":769,
              "y":370},
            "size":{
              "width":80,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"134e8274d76b46a8bb6d13ab26ba21c6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF3F3F3},
                "location":{
                  "x":769,
                  "y":370},
                "size":{
                  "width":80,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Detalhe_calendario_semana in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"detalhe_calendario_semana.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/detalhe_calendario_mes/u57.png"}},
{
          "id":"37a418ccb0804653bf4b319f21195cc6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF32323A},
            "location":{
              "x":848,
              "y":370},
            "size":{
              "width":80,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2f50e659482c4cc1a78053c75602d167",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF32323A},
                "location":{
                  "x":848,
                  "y":370},
                "size":{
                  "width":80,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/detalhe_calendario_semana/u55.png"}},
{
          "id":"211d54c5e09540b69911219a7b1be109",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":57,
              "y":450},
            "size":{
              "width":871,
              "height":1047}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5d27eb2876414e0f87a7a09e691177ee",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Arial Negrito', 'Arial'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "size":{
                  "width":871,
                  "height":49},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d8845604c51e496b9cf7c2d06e97bb1b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negrito', 'Arial'",
                    "fontWeight":"700",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4},
                    "size":{
                      "width":871,
                      "height":49},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/detalhe_calendario_dia/u60.png"}},
{
              "id":"42b17c4323644bd59d481e538d5d743b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "paddingBottom":"980",
                "location":{
                  "x":0,
                  "y":49},
                "size":{
                  "width":871,
                  "height":998},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4dff211629854d1882e1443cffc4d718",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"right",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "paddingBottom":"980",
                    "location":{
                      "x":0,
                      "y":49},
                    "size":{
                      "width":871,
                      "height":998},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/detalhe_calendario_dia/u62.png"}}]},
{
          "id":"f73c5c32d71b429197fc7f348eee48dd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF1FB5AD},
            "location":{
              "x":63,
              "y":505},
            "size":{
              "width":858,
              "height":68},
            "borderWidth":"-1",
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dcec27de90b94f13b43eefb9cebe69aa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF1FB5AD},
                "location":{
                  "x":63,
                  "y":505},
                "size":{
                  "width":858,
                  "height":68},
                "borderWidth":"-1",
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/detalhe_calendario_dia/u64.png"}},
{
          "id":"73164415298e41e685998bc8899eb622",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF1FB5AD},
            "location":{
              "x":63,
              "y":579},
            "size":{
              "width":858,
              "height":68},
            "borderWidth":"-1",
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3f5b71ea184d43b58fa0b860e85a4da0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF1FB5AD},
                "location":{
                  "x":63,
                  "y":579},
                "size":{
                  "width":858,
                  "height":68},
                "borderWidth":"-1",
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/detalhe_calendario_dia/u64.png"}},
{
          "id":"ab91c4f28d6340f291b8f7ee2aa7f4f9",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"12px",
            "fontWeight":"400",
            "underline":true,
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0066FF,
              "opacity":1},
            "location":{
              "x":34,
              "y":1556},
            "size":{
              "width":236,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8835673ecbe84d80b0f303a107af1f32",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"12px",
                "fontWeight":"400",
                "underline":true,
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0066FF,
                  "opacity":1},
                "location":{
                  "x":34,
                  "y":1556},
                "size":{
                  "width":236,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Calendario in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"calendario.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6bf6bf928d974ac399eb821d002d158e",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":34,
              "y":1526},
            "size":{
              "width":876,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/alterar_senha/u42_line.png"}},
{
          "id":"e6f96452ff7d40ffa5fc1ed8c885c68d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "lineSpacing":"12px",
            "location":{
              "x":37,
              "y":187},
            "size":{
              "width":493,
              "height":37},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"56a205e3a4264e098232046df4d5ecc3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "lineSpacing":"12px",
                "location":{
                  "x":37,
                  "y":187},
                "size":{
                  "width":493,
                  "height":37},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dbedb5428644477aa22236d2861fc261",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":37,
              "y":240},
            "size":{
              "width":41,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"98bc4e49c4bf4e9a9c5b6e4adc44dea3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":37,
                  "y":240},
                "size":{
                  "width":41,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fa9fdd77ce764fe09707636afe798f7d",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":34,
              "y":221},
            "size":{
              "width":916,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/dashboard/u173_line.png"}},
{
          "id":"bc470b40c6d8429f8a9dbebcccd80a8e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":37,
              "y":272},
            "size":{
              "width":169,
              "height":15},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d009000227924d2b8f04b55abeed838b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":37,
                  "y":272},
                "size":{
                  "width":169,
                  "height":15},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fc6b340d85aa4523a11ea3eab528684c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":215,
              "y":272},
            "size":{
              "width":143,
              "height":15},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"570673c2f9b0414dbea576d0f3826d4c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":215,
                  "y":272},
                "size":{
                  "width":143,
                  "height":15},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5072322c49a5492db65f05a1144149c3",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF333333,
              "opacity":1},
            "location":{
              "x":215,
              "y":297},
            "size":{
              "width":170,
              "height":32}},
          "adaptiveStyles":{
}},
{
          "id":"77d8ce5d48c345b6bca39b09bf28cff3",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF333333,
              "opacity":1},
            "location":{
              "x":37,
              "y":297},
            "size":{
              "width":169,
              "height":32}},
          "adaptiveStyles":{
}},
{
          "id":"2939b96c8930423286f101acc6b3e2c7",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":395,
              "y":298},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"dddb079336204356b4405ae775cb08e7",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"3f2785b78d234f1694ad71f932e35d42",
                  "label":"",
                  "parentDynamicPanel":"2939b96c8930423286f101acc6b3e2c7",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negrito', 'Arial'",
                    "fontSize":"11px",
                    "fontWeight":"700",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "size":{
                      "width":30,
                      "height":31},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "cornerRadiusTopLeft":"2"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"0a5d8d19e50d4a8eb1766c6f401a81b6",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2939b96c8930423286f101acc6b3e2c7",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Negrito', 'Arial'",
                        "fontSize":"11px",
                        "fontWeight":"700",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC},
                        "size":{
                          "width":30,
                          "height":31},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "cornerRadiusTopLeft":"2"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/senha_feedback1/u193.png"}},
{
                  "id":"ec783e2f80e849a3913b9355e13c2dcd",
                  "label":"",
                  "parentDynamicPanel":"2939b96c8930423286f101acc6b3e2c7",
                  "panelIndex":0,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":6,
                      "y":6},
                    "size":{
                      "width":20,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"79328d0a7e5142b09dd4eef2545b9b43",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2939b96c8930423286f101acc6b3e2c7",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":6,
                          "y":6},
                        "size":{
                          "width":20,
                          "height":20}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/senha_feedback1/u195.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]}]}},
  "masters":{
    "4226023da38e45578b3ec7ef42593243":{
      "packageId":"4226023da38e45578b3ec7ef42593243",
      "type":"Axure:Master",
      "name":"footer",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"98f6e95fccd74ca4a04a4a23229806bc",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"12px",
              "verticalAlignment":"middle",
              "fill":{
                "fillType":"solid",
                "color":0xFFF2F2F2},
              "location":{
                "x":240,
                "y":0},
              "size":{
                "width":780,
                "height":40}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"4c99a36cd31f4770a5042ff302db729c",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"12px",
                  "verticalAlignment":"middle",
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2},
                  "location":{
                    "x":240,
                    "y":0},
                  "size":{
                    "width":780,
                    "height":40}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/cadastro/u3.png"}}]}},
    "fbc37d401c784c2abad213112443341e":{
      "packageId":"fbc37d401c784c2abad213112443341e",
      "type":"Axure:Master",
      "name":"header_gerente",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"a98ffd8705e040929b7ec88c6bbc264e",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "size":{
                "width":980,
                "height":80},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8ab6195fdb274feb89b20710a3fc5997",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":980,
                    "height":80},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/alterar_senha/u6.png"}},
{
            "id":"fa8b587736bf4c6ea418fcbeaa262c99",
            "label":"",
            "type":"verticalLine",
            "styleType":"verticalLine",
            "visible":true,
            "style":{
              "location":{
                "x":284,
                "y":0},
              "size":{
                "width":10,
                "height":81},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFE4E4E4}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/alterar_senha/u8_line.png"}},
{
            "id":"fe49e2a706744e048a3667060b9a3e69",
            "label":"dropdown-user",
            "type":"dynamicPanel",
            "styleType":"dynamicPanel",
            "visible":true,
            "style":{
              "location":{
                "x":780,
                "y":22},
              "size":{
                "width":200,
                "height":138}},
            "adaptiveStyles":{
},
            "scrollbars":"none",
            "fitToContent":false,
            "propagate":false,
            "diagrams":[{
                "id":"9988237930104c0f96653f270533b92b",
                "label":"State1",
                "type":"Axure:PanelDiagram",
                "objects":[{
                    "id":"6204713e832042c18bfcced89f8bce20",
                    "label":"",
                    "parentDynamicPanel":"fe49e2a706744e048a3667060b9a3e69",
                    "panelIndex":0,
                    "type":"buttonShape",
                    "styleType":"paragraph",
                    "visible":true,
                    "style":{
                      "fontName":"'Helvetica Neue'",
                      "fontSize":"18px",
                      "horizontalAlignment":"right",
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF666666,
                        "opacity":1},
                      "location":{
                        "x":54,
                        "y":18},
                      "size":{
                        "width":92,
                        "height":22}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"62986fe513794f9c8abec46cde2877a7",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"fe49e2a706744e048a3667060b9a3e69",
                        "panelIndex":0,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontName":"'Helvetica Neue'",
                          "fontSize":"18px",
                          "horizontalAlignment":"right",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFF666666,
                            "opacity":1},
                          "location":{
                            "x":54,
                            "y":18},
                          "size":{
                            "width":92,
                            "height":22}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"c076f0909fb542b49a704785b1078434",
                    "label":"",
                    "parentDynamicPanel":"fe49e2a706744e048a3667060b9a3e69",
                    "panelIndex":0,
                    "type":"buttonShape",
                    "styleType":"paragraph",
                    "visible":true,
                    "style":{
                      "fontName":"'Helvetica Neue'",
                      "fontSize":"12px",
                      "horizontalAlignment":"right",
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF666666,
                        "opacity":1},
                      "location":{
                        "x":79,
                        "y":0},
                      "size":{
                        "width":66,
                        "height":14}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"c925cae17de947179805ef69d39926c2",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"fe49e2a706744e048a3667060b9a3e69",
                        "panelIndex":0,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontName":"'Helvetica Neue'",
                          "fontSize":"12px",
                          "horizontalAlignment":"right",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFF666666,
                            "opacity":1},
                          "location":{
                            "x":79,
                            "y":0},
                          "size":{
                            "width":66,
                            "height":14}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"11cf14182664433ebd8e6f1a0ee85ffe",
                    "label":"",
                    "parentDynamicPanel":"fe49e2a706744e048a3667060b9a3e69",
                    "panelIndex":0,
                    "type":"imageBox",
                    "styleType":"imageBox",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":162,
                        "y":4},
                      "size":{
                        "width":28,
                        "height":28}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"9a3f85fce4df4d77b97c4565d725eec5",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"fe49e2a706744e048a3667060b9a3e69",
                        "panelIndex":0,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":162,
                            "y":4},
                          "size":{
                            "width":28,
                            "height":28}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/alterar_senha/u14.png"}},
{
                    "id":"f6b7572cbf4c448c9f6afbaa10bfad13",
                    "label":"",
                    "parentDynamicPanel":"fe49e2a706744e048a3667060b9a3e69",
                    "panelIndex":0,
                    "type":"imageMapRegion",
                    "styleType":"imageMapRegion",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":155,
                        "y":0},
                      "size":{
                        "width":40,
                        "height":40}},
                    "adaptiveStyles":{
},
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"setPanelState",
                                "description":"Set dropdown-user to State2",
                                "panelsToStates":[{
                                    "panelPath":["fe49e2a706744e048a3667060b9a3e69"],
                                    "stateInfo":{
                                      "setStateType":"diagram",
                                      "stateNumber":2,
                                      "stateValue":{
                                        "exprType":"stringLiteral",
                                        "value":"1",
                                        "stos":[]},
                                      "loop":false,
                                      "showWhenSet":false,
                                      "options":{
                                        "compress":false}}}]}]}]}},
                    "tabbable":true}],
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFFFFF},
                  "image":null,
                  "imageHorizontalAlignment":"near",
                  "imageVerticalAlignment":"near",
                  "imageRepeat":"auto"},
                "adaptiveStyles":{
}},
{
                "id":"5ab577ad4f0d4fea8d6efa85d310a7cd",
                "label":"State2",
                "type":"Axure:PanelDiagram",
                "objects":[{
                    "id":"9ed6828666f447f7a7e0ceb44c3afe85",
                    "label":"",
                    "parentDynamicPanel":"fe49e2a706744e048a3667060b9a3e69",
                    "panelIndex":1,
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFE4E4E4},
                      "location":{
                        "x":0,
                        "y":47},
                      "size":{
                        "width":200,
                        "height":83},
                      "borderFill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "cornerRadiusTopLeft":"5"},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"bd713743a4fd4100b43ccca1b70ca994",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"fe49e2a706744e048a3667060b9a3e69",
                        "panelIndex":1,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFE4E4E4},
                          "location":{
                            "x":0,
                            "y":47},
                          "size":{
                            "width":200,
                            "height":83},
                          "borderFill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "cornerRadiusTopLeft":"5"},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/alterar_senha/u17.png"}},
{
                    "id":"c45b355677264302bfe15da0b7663744",
                    "label":"",
                    "parentDynamicPanel":"fe49e2a706744e048a3667060b9a3e69",
                    "panelIndex":1,
                    "type":"buttonShape",
                    "styleType":"paragraph",
                    "visible":true,
                    "style":{
                      "fontSize":"14px",
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF0066FF,
                        "opacity":1},
                      "location":{
                        "x":20,
                        "y":58},
                      "size":{
                        "width":170,
                        "height":16},
                      "rotation":"0",
                      "textRotation":"0"},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"3dee6155c57042de849e03626aa42332",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"fe49e2a706744e048a3667060b9a3e69",
                        "panelIndex":1,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontSize":"14px",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFF0066FF,
                            "opacity":1},
                          "location":{
                            "x":20,
                            "y":58},
                          "size":{
                            "width":170,
                            "height":16},
                          "rotation":"0",
                          "textRotation":"0"},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"Open Alterar senha in Current Window",
                                "target":{
                                  "targetType":"page",
                                  "url":"alterar_senha.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"5b7ee831d3d94eb7bcd42535e0e07829",
                    "label":"",
                    "parentDynamicPanel":"fe49e2a706744e048a3667060b9a3e69",
                    "panelIndex":1,
                    "type":"horizontalLine",
                    "styleType":"horizontalLine",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":0,
                        "y":82},
                      "size":{
                        "width":200,
                        "height":10},
                      "borderFill":{
                        "fillType":"solid",
                        "color":0xFFCCCCCC}},
                    "adaptiveStyles":{
},
                    "images":{
                      "start~":"resources/images/transparent.gif",
                      "end~":"resources/images/transparent.gif",
                      "line~":"images/alterar_senha/u21_line.png"}},
{
                    "id":"78e83a886be14343987e121a22698ce9",
                    "label":"",
                    "parentDynamicPanel":"fe49e2a706744e048a3667060b9a3e69",
                    "panelIndex":1,
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFE4E4E4},
                      "location":{
                        "x":166,
                        "y":36},
                      "size":{
                        "width":20,
                        "height":15},
                      "borderFill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "cornerRadiusTopLeft":"5"},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"048b499446c24a21965e02b1a1c2cda1",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"fe49e2a706744e048a3667060b9a3e69",
                        "panelIndex":1,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFE4E4E4},
                          "location":{
                            "x":166,
                            "y":36},
                          "size":{
                            "width":20,
                            "height":15},
                          "borderFill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "cornerRadiusTopLeft":"5"},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/alterar_senha/u22.png"}},
{
                    "id":"e07433f9f99a4fcca3478cabd32cb61e",
                    "label":"",
                    "parentDynamicPanel":"fe49e2a706744e048a3667060b9a3e69",
                    "panelIndex":1,
                    "type":"buttonShape",
                    "styleType":"paragraph",
                    "visible":true,
                    "style":{
                      "fontName":"'Helvetica Neue'",
                      "fontSize":"18px",
                      "horizontalAlignment":"right",
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF666666,
                        "opacity":1},
                      "location":{
                        "x":54,
                        "y":18},
                      "size":{
                        "width":92,
                        "height":22}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"87c0a50ec8474ff2a48c7489776d6e3c",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"fe49e2a706744e048a3667060b9a3e69",
                        "panelIndex":1,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontName":"'Helvetica Neue'",
                          "fontSize":"18px",
                          "horizontalAlignment":"right",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFF666666,
                            "opacity":1},
                          "location":{
                            "x":54,
                            "y":18},
                          "size":{
                            "width":92,
                            "height":22}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"1e467f8e63d14e87b4967a32746222e9",
                    "label":"",
                    "parentDynamicPanel":"fe49e2a706744e048a3667060b9a3e69",
                    "panelIndex":1,
                    "type":"buttonShape",
                    "styleType":"paragraph",
                    "visible":true,
                    "style":{
                      "fontName":"'Helvetica Neue'",
                      "fontSize":"12px",
                      "horizontalAlignment":"right",
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF666666,
                        "opacity":1},
                      "location":{
                        "x":79,
                        "y":0},
                      "size":{
                        "width":66,
                        "height":14}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"b19b8a20efe044748b51ac5b68a88f23",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"fe49e2a706744e048a3667060b9a3e69",
                        "panelIndex":1,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontName":"'Helvetica Neue'",
                          "fontSize":"12px",
                          "horizontalAlignment":"right",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFF666666,
                            "opacity":1},
                          "location":{
                            "x":79,
                            "y":0},
                          "size":{
                            "width":66,
                            "height":14}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"b8608e9f638b4660a8a6dee7aa9c3e36",
                    "label":"",
                    "parentDynamicPanel":"fe49e2a706744e048a3667060b9a3e69",
                    "panelIndex":1,
                    "type":"imageBox",
                    "styleType":"imageBox",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":162,
                        "y":4},
                      "size":{
                        "width":28,
                        "height":28}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"a559e57a14854d24a4609485d50f1ed3",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"fe49e2a706744e048a3667060b9a3e69",
                        "panelIndex":1,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":162,
                            "y":4},
                          "size":{
                            "width":28,
                            "height":28}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/alterar_senha/u14.png"}},
{
                    "id":"fda57ffd0f054a0d897d3b093d669bdd",
                    "label":"",
                    "parentDynamicPanel":"fe49e2a706744e048a3667060b9a3e69",
                    "panelIndex":1,
                    "type":"buttonShape",
                    "styleType":"paragraph",
                    "visible":true,
                    "style":{
                      "fontSize":"14px",
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF0066FF,
                        "opacity":1},
                      "location":{
                        "x":20,
                        "y":99},
                      "size":{
                        "width":170,
                        "height":16},
                      "rotation":"0",
                      "textRotation":"0"},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"5cc804455eb0464b85ff7cc456067800",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"fe49e2a706744e048a3667060b9a3e69",
                        "panelIndex":1,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontSize":"14px",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFF0066FF,
                            "opacity":1},
                          "location":{
                            "x":20,
                            "y":99},
                          "size":{
                            "width":170,
                            "height":16},
                          "rotation":"0",
                          "textRotation":"0"},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"Open Cadastro in Current Window",
                                "target":{
                                  "targetType":"page",
                                  "url":"cadastro.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"a6aab5213b4b4c3e85ac4afe1f257e91",
                    "label":"",
                    "parentDynamicPanel":"fe49e2a706744e048a3667060b9a3e69",
                    "panelIndex":1,
                    "type":"imageMapRegion",
                    "styleType":"imageMapRegion",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":155,
                        "y":0},
                      "size":{
                        "width":40,
                        "height":40}},
                    "adaptiveStyles":{
},
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"setPanelState",
                                "description":"Set dropdown-user to State1",
                                "panelsToStates":[{
                                    "panelPath":["fe49e2a706744e048a3667060b9a3e69"],
                                    "stateInfo":{
                                      "setStateType":"diagram",
                                      "stateNumber":1,
                                      "stateValue":{
                                        "exprType":"stringLiteral",
                                        "value":"1",
                                        "stos":[]},
                                      "loop":false,
                                      "showWhenSet":false,
                                      "options":{
                                        "compress":false}}}]}]}]}},
                    "tabbable":true}],
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFFFFF},
                  "image":null,
                  "imageHorizontalAlignment":"near",
                  "imageVerticalAlignment":"near",
                  "imageRepeat":"auto"},
                "adaptiveStyles":{
}}]},
{
            "id":"5280f6ab2ff541e3a08d602a96f14af5",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":8,
                "y":22},
              "size":{
                "width":252,
                "height":37}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"62a6cea60ded4fa9a507f5f197608b58",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":8,
                    "y":22},
                  "size":{
                    "width":252,
                    "height":37}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/cadastro/u19.png"}},
{
            "id":"fe5658b4dd484718b4046ef0c1c59a08",
            "label":"",
            "type":"imageMapRegion",
            "styleType":"imageMapRegion",
            "visible":true,
            "style":{
              "size":{
                "width":294,
                "height":81}},
            "adaptiveStyles":{
},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Dashboard in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"dashboard.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true}]}}},
  "objectPaths":{
    "c55b641589fa43c8b088ca4aab5d4a57":{
      "scriptId":"u0"},
    "22d495609e0745e5a0ae69d35940d195":{
      "scriptId":"u1"},
    "cb6e95cdba7d46dcb6b26ef506f17169":{
      "scriptId":"u2",
      "98f6e95fccd74ca4a04a4a23229806bc":{
        "scriptId":"u3"},
      "4c99a36cd31f4770a5042ff302db729c":{
        "scriptId":"u4"}},
    "f4379b2d037d4dbe884f6787fc0a0436":{
      "scriptId":"u5",
      "a98ffd8705e040929b7ec88c6bbc264e":{
        "scriptId":"u6"},
      "8ab6195fdb274feb89b20710a3fc5997":{
        "scriptId":"u7"},
      "fa8b587736bf4c6ea418fcbeaa262c99":{
        "scriptId":"u8"},
      "fe49e2a706744e048a3667060b9a3e69":{
        "scriptId":"u9"},
      "6204713e832042c18bfcced89f8bce20":{
        "scriptId":"u10"},
      "62986fe513794f9c8abec46cde2877a7":{
        "scriptId":"u11"},
      "c076f0909fb542b49a704785b1078434":{
        "scriptId":"u12"},
      "c925cae17de947179805ef69d39926c2":{
        "scriptId":"u13"},
      "11cf14182664433ebd8e6f1a0ee85ffe":{
        "scriptId":"u14"},
      "9a3f85fce4df4d77b97c4565d725eec5":{
        "scriptId":"u15"},
      "f6b7572cbf4c448c9f6afbaa10bfad13":{
        "scriptId":"u16"},
      "9ed6828666f447f7a7e0ceb44c3afe85":{
        "scriptId":"u17"},
      "bd713743a4fd4100b43ccca1b70ca994":{
        "scriptId":"u18"},
      "c45b355677264302bfe15da0b7663744":{
        "scriptId":"u19"},
      "3dee6155c57042de849e03626aa42332":{
        "scriptId":"u20"},
      "5b7ee831d3d94eb7bcd42535e0e07829":{
        "scriptId":"u21"},
      "78e83a886be14343987e121a22698ce9":{
        "scriptId":"u22"},
      "048b499446c24a21965e02b1a1c2cda1":{
        "scriptId":"u23"},
      "e07433f9f99a4fcca3478cabd32cb61e":{
        "scriptId":"u24"},
      "87c0a50ec8474ff2a48c7489776d6e3c":{
        "scriptId":"u25"},
      "1e467f8e63d14e87b4967a32746222e9":{
        "scriptId":"u26"},
      "b19b8a20efe044748b51ac5b68a88f23":{
        "scriptId":"u27"},
      "b8608e9f638b4660a8a6dee7aa9c3e36":{
        "scriptId":"u28"},
      "a559e57a14854d24a4609485d50f1ed3":{
        "scriptId":"u29"},
      "fda57ffd0f054a0d897d3b093d669bdd":{
        "scriptId":"u30"},
      "5cc804455eb0464b85ff7cc456067800":{
        "scriptId":"u31"},
      "a6aab5213b4b4c3e85ac4afe1f257e91":{
        "scriptId":"u32"},
      "5280f6ab2ff541e3a08d602a96f14af5":{
        "scriptId":"u33"},
      "62a6cea60ded4fa9a507f5f197608b58":{
        "scriptId":"u34"},
      "fe5658b4dd484718b4046ef0c1c59a08":{
        "scriptId":"u35"}},
    "183881b7ccdc435ab64e34b97fe44fc3":{
      "scriptId":"u36"},
    "68843d8396ec418b8a15ff21e790eae1":{
      "scriptId":"u37"},
    "f59228cc097846c7aa061cca1267511a":{
      "scriptId":"u38"},
    "fa8402e32e6a4c5fbdfa7c41a06dbfeb":{
      "scriptId":"u39"},
    "23f4533711fc4fd7824027d446cd351a":{
      "scriptId":"u40"},
    "3b5e248c44a2413ca5d2e84dda5e6052":{
      "scriptId":"u41"},
    "f9501775bcb34f779ec24983b865ff75":{
      "scriptId":"u42"},
    "746333f1d7814f07b867f2a69d61f540":{
      "scriptId":"u43"},
    "7a8b3d13ec3e4638a0c49623905b1e6a":{
      "scriptId":"u44"},
    "05c3ba82355343d69c63b128d1fbb7e2":{
      "scriptId":"u45"},
    "9f49121bb4b14350a1d212010ab589b7":{
      "scriptId":"u46"},
    "3f30b9999ba54a27b12174b5561de428":{
      "scriptId":"u47"},
    "3b9c904517904e859f025891ffb690b4":{
      "scriptId":"u48"},
    "0b32928b9e8d4ca389ed45969910dc03":{
      "scriptId":"u49"},
    "5bb79ac1971249f8accb818d3beaab0c":{
      "scriptId":"u50"},
    "1e8d227ec07147dab03b2a1f5e0c4d21":{
      "scriptId":"u51"},
    "6959633c375c4ecf9a813d266414305a":{
      "scriptId":"u52"},
    "05f06a7d3cec4773b4307642e1004a38":{
      "scriptId":"u53"},
    "c0e4eb80e7ca4f46a4e6742c768fce6f":{
      "scriptId":"u54"},
    "6a6d5f5cc76f421a93e71574f4902303":{
      "scriptId":"u55"},
    "134e8274d76b46a8bb6d13ab26ba21c6":{
      "scriptId":"u56"},
    "37a418ccb0804653bf4b319f21195cc6":{
      "scriptId":"u57"},
    "2f50e659482c4cc1a78053c75602d167":{
      "scriptId":"u58"},
    "211d54c5e09540b69911219a7b1be109":{
      "scriptId":"u59"},
    "5d27eb2876414e0f87a7a09e691177ee":{
      "scriptId":"u60"},
    "d8845604c51e496b9cf7c2d06e97bb1b":{
      "scriptId":"u61"},
    "42b17c4323644bd59d481e538d5d743b":{
      "scriptId":"u62"},
    "4dff211629854d1882e1443cffc4d718":{
      "scriptId":"u63"},
    "f73c5c32d71b429197fc7f348eee48dd":{
      "scriptId":"u64"},
    "dcec27de90b94f13b43eefb9cebe69aa":{
      "scriptId":"u65"},
    "73164415298e41e685998bc8899eb622":{
      "scriptId":"u66"},
    "3f5b71ea184d43b58fa0b860e85a4da0":{
      "scriptId":"u67"},
    "ab91c4f28d6340f291b8f7ee2aa7f4f9":{
      "scriptId":"u68"},
    "8835673ecbe84d80b0f303a107af1f32":{
      "scriptId":"u69"},
    "6bf6bf928d974ac399eb821d002d158e":{
      "scriptId":"u70"},
    "e6f96452ff7d40ffa5fc1ed8c885c68d":{
      "scriptId":"u71"},
    "56a205e3a4264e098232046df4d5ecc3":{
      "scriptId":"u72"},
    "dbedb5428644477aa22236d2861fc261":{
      "scriptId":"u73"},
    "98bc4e49c4bf4e9a9c5b6e4adc44dea3":{
      "scriptId":"u74"},
    "fa9fdd77ce764fe09707636afe798f7d":{
      "scriptId":"u75"},
    "bc470b40c6d8429f8a9dbebcccd80a8e":{
      "scriptId":"u76"},
    "d009000227924d2b8f04b55abeed838b":{
      "scriptId":"u77"},
    "fc6b340d85aa4523a11ea3eab528684c":{
      "scriptId":"u78"},
    "570673c2f9b0414dbea576d0f3826d4c":{
      "scriptId":"u79"},
    "5072322c49a5492db65f05a1144149c3":{
      "scriptId":"u80"},
    "77d8ce5d48c345b6bca39b09bf28cff3":{
      "scriptId":"u81"},
    "2939b96c8930423286f101acc6b3e2c7":{
      "scriptId":"u82"},
    "3f2785b78d234f1694ad71f932e35d42":{
      "scriptId":"u83"},
    "0a5d8d19e50d4a8eb1766c6f401a81b6":{
      "scriptId":"u84"},
    "ec783e2f80e849a3913b9355e13c2dcd":{
      "scriptId":"u85"},
    "79328d0a7e5142b09dd4eef2545b9b43":{
      "scriptId":"u86"}}});