$axure.loadCurrentPage({
  "url":"novo_usuario_status3.html",
  "generationDate":new Date(1423764021136.55),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"e4f55739c4834ad79f0e5d63f212bd4e",
    "type":"Axure:Page",
    "name":"Novo usuario_status3",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"09429fc5251b48158d5ddd9aa05fb88d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "size":{
              "width":980,
              "height":1090},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b5d659edd1ff410b806a3748f8f37d45",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "size":{
                  "width":980,
                  "height":1090},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/novo_usuario_status3/u0.png"}},
{
          "id":"aa95471021e740a6bf20d84a931cdfe7",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":1050},
            "size":{
              "width":780,
              "height":40}},
          "adaptiveStyles":{
},
          "masterId":"4226023da38e45578b3ec7ef42593243"},
{
          "id":"864bbbfd36fc4d6d947ba8107be32899",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"fbc37d401c784c2abad213112443341e"},
{
          "id":"9ad53d598b5641baa9e4979999c6bc3b",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":34,
              "y":138},
            "size":{
              "width":446,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0e01186751d84be4bd23afa0dcc627f5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":34,
                  "y":138},
                "size":{
                  "width":446,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5a5de49db5af4c4da0961bd6618e34f8",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"12px",
            "fontWeight":"400",
            "underline":true,
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099FF,
              "opacity":1},
            "location":{
              "x":34,
              "y":112},
            "size":{
              "width":216,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"463ea6ffb337461085d6c9c920f2ccc1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"12px",
                "fontWeight":"400",
                "underline":true,
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":34,
                  "y":112},
                "size":{
                  "width":216,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Usuarios in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"usuarios.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c3ed4c9ccc214f2b9fb8dca34ec511d4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negrito', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF0099FF},
            "location":{
              "x":34,
              "y":800},
            "size":{
              "width":96,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"abbcc70f05c04222b0b7fd245c408eac",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negrito', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0099FF},
                "location":{
                  "x":34,
                  "y":800},
                "size":{
                  "width":96,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"2"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/novo_lembrete_status1/u42.png"}},
{
          "id":"21e7dd52a6484ca0a295d0fc45154f62",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":34,
              "y":214},
            "size":{
              "width":255,
              "height":32},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0f96da0930664bcdad4d4a9a9588fd30",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":34,
                  "y":214},
                "size":{
                  "width":255,
                  "height":32},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/novo_relatorio/u40.png"}},
{
          "id":"17073eff9d474580ab116cbba990e038",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":34,
              "y":267},
            "size":{
              "width":906,
              "height":353},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"70da89aea64d429f8b9f8d12496169a8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":34,
                  "y":267},
                "size":{
                  "width":906,
                  "height":353},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/novo_usuario_status3/u44.png"}},
{
          "id":"92fed74d4044416bafc8ccfcaece8114",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":54,
              "y":286},
            "size":{
              "width":143,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cfdfffcbdc634c05bf33d664b3a876f1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":54,
                  "y":286},
                "size":{
                  "width":143,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b52f8c1ad77b4bbeb2152efbad03d183",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":54,
              "y":378},
            "size":{
              "width":856,
              "height":122},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b8f3c8ce8a144d0595db6ddb05565cd5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":54,
                  "y":378},
                "size":{
                  "width":856,
                  "height":122},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/novo_usuario_status2/u48.png"}},
{
          "id":"1f4bab3f8f6b4cec8cda0aa3382a2dd7",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":80,
              "y":402},
            "size":{
              "width":170,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"41842d3fa0c64497bbcc87e821d5e32d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":80,
                  "y":402},
                "size":{
                  "width":170,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"664b3d21649f438fbac17684194b606e",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":80,
              "y":434},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"01c45bc1aa3843199297b6479a8056ef",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":80,
                  "y":434},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"baa9eea046394b0da1919ae9614e7d2b",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":290,
              "y":402},
            "size":{
              "width":160,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"779e13b173ed464895eba3caac71f2ec",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":290,
                  "y":402},
                "size":{
                  "width":160,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"06f536521cae41ab95ec14d19ce8d785",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":290,
              "y":434},
            "size":{
              "width":160,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"faa6b1b063ab4a4b908815b97b922248",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":290,
                  "y":434},
                "size":{
                  "width":160,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"f626173d0a3e43a591cd4fa6b07e9fdc",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":500,
              "y":402},
            "size":{
              "width":170,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3c222b064ff0400ca3094878be96ceef",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":500,
                  "y":402},
                "size":{
                  "width":170,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"df120cc926ad4ddf891404baff865375",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":54,
              "y":353},
            "size":{
              "width":336,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"218d3b3600964a27b8e515acd3cf327c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":54,
                  "y":353},
                "size":{
                  "width":336,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1e0a99b085fb4758a0800817af4f564e",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF333333,
              "opacity":1},
            "location":{
              "x":54,
              "y":310},
            "size":{
              "width":255,
              "height":32}},
          "adaptiveStyles":{
}},
{
          "id":"a172e17379484dc38164da80254a519f",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":700,
              "y":402},
            "size":{
              "width":170,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"06a29402116b48de8264bac6631ee9e5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":700,
                  "y":402},
                "size":{
                  "width":170,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"66e7016d2a5e4efbb0acd017037dcd06",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":500,
              "y":434},
            "size":{
              "width":140,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b53d7a84278046779f9b94a4dd95dc78",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":500,
                  "y":434},
                "size":{
                  "width":140,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"0f6bdad0cf6a4591b3f2125d3c7ba0d9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":53,
              "y":540},
            "size":{
              "width":856,
              "height":53},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"85d5c13e68c84f2db5259b8daa0cc54e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":53,
                  "y":540},
                "size":{
                  "width":856,
                  "height":53},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/novo_usuario_status2/u67.png"}},
{
          "id":"92d962bcc3e240728594f73e89c13129",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":700,
              "y":434},
            "size":{
              "width":140,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"75384e5c5aa24e2bbda7d791067a6415",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":700,
                  "y":434},
                "size":{
                  "width":140,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"d8d00f31352847de81e9195742bc19a2",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":80,
              "y":470},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ba88ed167bd64c38a7789e916d0eb53e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":80,
                  "y":470},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"eff1e005031d47ce8c59d0dfb607c92b",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":80,
              "y":557},
            "size":{
              "width":196,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"041fa7a8160443d3a1608e18a7a91e18",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":80,
                  "y":557},
                "size":{
                  "width":196,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"a187c38c64c441e4aa38cf032fb7baad",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":54,
              "y":516},
            "size":{
              "width":616,
              "height":21},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0481ae9782ec41889de063769f898a1c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":54,
                  "y":516},
                "size":{
                  "width":616,
                  "height":21},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"36aa22bfdc55414d9feb756afb7aa16c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "underline":true,
            "horizontalAlignment":"right",
            "location":{
              "x":710,
              "y":753},
            "size":{
              "width":190,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dbaf0bee84584b8da6a22b12558c0e94",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "underline":true,
                "horizontalAlignment":"right",
                "location":{
                  "x":710,
                  "y":753},
                "size":{
                  "width":190,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5cdf4efa33234fe6a58b870aa1ba6f4e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":35,
              "y":190},
            "size":{
              "width":220,
              "height":17},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bbd6fae126ba4a58af5d45d5154b633d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":35,
                  "y":190},
                "size":{
                  "width":220,
                  "height":17},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b2b179fbe1544dadad335a861d0909d6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":34,
              "y":630},
            "size":{
              "width":906,
              "height":113},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a7b2d7bdf8624d47b64c606b925e7c0b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":34,
                  "y":630},
                "size":{
                  "width":906,
                  "height":113},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/novo_usuario_status1/u44.png"}},
{
          "id":"b16adc15eb2643fcafe43d78f7d95b04",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":54,
              "y":649},
            "size":{
              "width":143,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5bbb8b629f2c4166aad55c6fb4760791",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":54,
                  "y":649},
                "size":{
                  "width":143,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e850e3751db54a30be6e43650c50aa9e",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF333333,
              "opacity":1},
            "location":{
              "x":54,
              "y":673},
            "size":{
              "width":255,
              "height":32}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onFocus":{
              "description":"OnFocus",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Novo usuario_status2 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"novo_usuario_status2.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"7b633e2d169940f19cb4ea065349f1be",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"12px",
            "fontWeight":"400",
            "underline":true,
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099FF,
              "opacity":1},
            "location":{
              "x":34,
              "y":994},
            "size":{
              "width":236,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7b888a413846440382afcbabb2ae37e5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"12px",
                "fontWeight":"400",
                "underline":true,
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":34,
                  "y":994},
                "size":{
                  "width":236,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Usuarios in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"usuarios.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"20579b6553014929b5ff37001869d980",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":34,
              "y":964},
            "size":{
              "width":876,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/alterar_senha/u42_line.png"}}]}},
  "masters":{
    "4226023da38e45578b3ec7ef42593243":{
      "packageId":"4226023da38e45578b3ec7ef42593243",
      "type":"Axure:Master",
      "name":"footer",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"98f6e95fccd74ca4a04a4a23229806bc",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"12px",
              "verticalAlignment":"middle",
              "fill":{
                "fillType":"solid",
                "color":0xFFF2F2F2},
              "location":{
                "x":240,
                "y":0},
              "size":{
                "width":780,
                "height":40}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"4c99a36cd31f4770a5042ff302db729c",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"12px",
                  "verticalAlignment":"middle",
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2},
                  "location":{
                    "x":240,
                    "y":0},
                  "size":{
                    "width":780,
                    "height":40}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/cadastro/u3.png"}}]}},
    "fbc37d401c784c2abad213112443341e":{
      "packageId":"fbc37d401c784c2abad213112443341e",
      "type":"Axure:Master",
      "name":"header_gerente",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"a98ffd8705e040929b7ec88c6bbc264e",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "size":{
                "width":980,
                "height":80},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8ab6195fdb274feb89b20710a3fc5997",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":980,
                    "height":80},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/alterar_senha/u6.png"}},
{
            "id":"fa8b587736bf4c6ea418fcbeaa262c99",
            "label":"",
            "type":"verticalLine",
            "styleType":"verticalLine",
            "visible":true,
            "style":{
              "location":{
                "x":284,
                "y":0},
              "size":{
                "width":10,
                "height":81},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFE4E4E4}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/alterar_senha/u8_line.png"}},
{
            "id":"fe49e2a706744e048a3667060b9a3e69",
            "label":"dropdown-user",
            "type":"dynamicPanel",
            "styleType":"dynamicPanel",
            "visible":true,
            "style":{
              "location":{
                "x":780,
                "y":22},
              "size":{
                "width":200,
                "height":138}},
            "adaptiveStyles":{
},
            "scrollbars":"none",
            "fitToContent":false,
            "propagate":false,
            "diagrams":[{
                "id":"9988237930104c0f96653f270533b92b",
                "label":"State1",
                "type":"Axure:PanelDiagram",
                "objects":[{
                    "id":"6204713e832042c18bfcced89f8bce20",
                    "label":"",
                    "parentDynamicPanel":"fe49e2a706744e048a3667060b9a3e69",
                    "panelIndex":0,
                    "type":"buttonShape",
                    "styleType":"paragraph",
                    "visible":true,
                    "style":{
                      "fontName":"'Helvetica Neue'",
                      "fontSize":"18px",
                      "horizontalAlignment":"right",
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF666666,
                        "opacity":1},
                      "location":{
                        "x":54,
                        "y":18},
                      "size":{
                        "width":92,
                        "height":22}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"62986fe513794f9c8abec46cde2877a7",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"fe49e2a706744e048a3667060b9a3e69",
                        "panelIndex":0,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontName":"'Helvetica Neue'",
                          "fontSize":"18px",
                          "horizontalAlignment":"right",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFF666666,
                            "opacity":1},
                          "location":{
                            "x":54,
                            "y":18},
                          "size":{
                            "width":92,
                            "height":22}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"c076f0909fb542b49a704785b1078434",
                    "label":"",
                    "parentDynamicPanel":"fe49e2a706744e048a3667060b9a3e69",
                    "panelIndex":0,
                    "type":"buttonShape",
                    "styleType":"paragraph",
                    "visible":true,
                    "style":{
                      "fontName":"'Helvetica Neue'",
                      "fontSize":"12px",
                      "horizontalAlignment":"right",
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF666666,
                        "opacity":1},
                      "location":{
                        "x":79,
                        "y":0},
                      "size":{
                        "width":66,
                        "height":14}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"c925cae17de947179805ef69d39926c2",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"fe49e2a706744e048a3667060b9a3e69",
                        "panelIndex":0,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontName":"'Helvetica Neue'",
                          "fontSize":"12px",
                          "horizontalAlignment":"right",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFF666666,
                            "opacity":1},
                          "location":{
                            "x":79,
                            "y":0},
                          "size":{
                            "width":66,
                            "height":14}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"11cf14182664433ebd8e6f1a0ee85ffe",
                    "label":"",
                    "parentDynamicPanel":"fe49e2a706744e048a3667060b9a3e69",
                    "panelIndex":0,
                    "type":"imageBox",
                    "styleType":"imageBox",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":162,
                        "y":4},
                      "size":{
                        "width":28,
                        "height":28}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"9a3f85fce4df4d77b97c4565d725eec5",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"fe49e2a706744e048a3667060b9a3e69",
                        "panelIndex":0,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":162,
                            "y":4},
                          "size":{
                            "width":28,
                            "height":28}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/alterar_senha/u14.png"}},
{
                    "id":"f6b7572cbf4c448c9f6afbaa10bfad13",
                    "label":"",
                    "parentDynamicPanel":"fe49e2a706744e048a3667060b9a3e69",
                    "panelIndex":0,
                    "type":"imageMapRegion",
                    "styleType":"imageMapRegion",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":155,
                        "y":0},
                      "size":{
                        "width":40,
                        "height":40}},
                    "adaptiveStyles":{
},
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"setPanelState",
                                "description":"Set dropdown-user to State2",
                                "panelsToStates":[{
                                    "panelPath":["fe49e2a706744e048a3667060b9a3e69"],
                                    "stateInfo":{
                                      "setStateType":"diagram",
                                      "stateNumber":2,
                                      "stateValue":{
                                        "exprType":"stringLiteral",
                                        "value":"1",
                                        "stos":[]},
                                      "loop":false,
                                      "showWhenSet":false,
                                      "options":{
                                        "compress":false}}}]}]}]}},
                    "tabbable":true}],
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFFFFF},
                  "image":null,
                  "imageHorizontalAlignment":"near",
                  "imageVerticalAlignment":"near",
                  "imageRepeat":"auto"},
                "adaptiveStyles":{
}},
{
                "id":"5ab577ad4f0d4fea8d6efa85d310a7cd",
                "label":"State2",
                "type":"Axure:PanelDiagram",
                "objects":[{
                    "id":"9ed6828666f447f7a7e0ceb44c3afe85",
                    "label":"",
                    "parentDynamicPanel":"fe49e2a706744e048a3667060b9a3e69",
                    "panelIndex":1,
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFE4E4E4},
                      "location":{
                        "x":0,
                        "y":47},
                      "size":{
                        "width":200,
                        "height":83},
                      "borderFill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "cornerRadiusTopLeft":"5"},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"bd713743a4fd4100b43ccca1b70ca994",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"fe49e2a706744e048a3667060b9a3e69",
                        "panelIndex":1,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFE4E4E4},
                          "location":{
                            "x":0,
                            "y":47},
                          "size":{
                            "width":200,
                            "height":83},
                          "borderFill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "cornerRadiusTopLeft":"5"},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/alterar_senha/u17.png"}},
{
                    "id":"c45b355677264302bfe15da0b7663744",
                    "label":"",
                    "parentDynamicPanel":"fe49e2a706744e048a3667060b9a3e69",
                    "panelIndex":1,
                    "type":"buttonShape",
                    "styleType":"paragraph",
                    "visible":true,
                    "style":{
                      "fontSize":"14px",
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF0066FF,
                        "opacity":1},
                      "location":{
                        "x":20,
                        "y":58},
                      "size":{
                        "width":170,
                        "height":16},
                      "rotation":"0",
                      "textRotation":"0"},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"3dee6155c57042de849e03626aa42332",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"fe49e2a706744e048a3667060b9a3e69",
                        "panelIndex":1,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontSize":"14px",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFF0066FF,
                            "opacity":1},
                          "location":{
                            "x":20,
                            "y":58},
                          "size":{
                            "width":170,
                            "height":16},
                          "rotation":"0",
                          "textRotation":"0"},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"Open Alterar senha in Current Window",
                                "target":{
                                  "targetType":"page",
                                  "url":"alterar_senha.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"5b7ee831d3d94eb7bcd42535e0e07829",
                    "label":"",
                    "parentDynamicPanel":"fe49e2a706744e048a3667060b9a3e69",
                    "panelIndex":1,
                    "type":"horizontalLine",
                    "styleType":"horizontalLine",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":0,
                        "y":82},
                      "size":{
                        "width":200,
                        "height":10},
                      "borderFill":{
                        "fillType":"solid",
                        "color":0xFFCCCCCC}},
                    "adaptiveStyles":{
},
                    "images":{
                      "start~":"resources/images/transparent.gif",
                      "end~":"resources/images/transparent.gif",
                      "line~":"images/alterar_senha/u21_line.png"}},
{
                    "id":"78e83a886be14343987e121a22698ce9",
                    "label":"",
                    "parentDynamicPanel":"fe49e2a706744e048a3667060b9a3e69",
                    "panelIndex":1,
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFE4E4E4},
                      "location":{
                        "x":166,
                        "y":36},
                      "size":{
                        "width":20,
                        "height":15},
                      "borderFill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "cornerRadiusTopLeft":"5"},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"048b499446c24a21965e02b1a1c2cda1",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"fe49e2a706744e048a3667060b9a3e69",
                        "panelIndex":1,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFE4E4E4},
                          "location":{
                            "x":166,
                            "y":36},
                          "size":{
                            "width":20,
                            "height":15},
                          "borderFill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "cornerRadiusTopLeft":"5"},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/alterar_senha/u22.png"}},
{
                    "id":"e07433f9f99a4fcca3478cabd32cb61e",
                    "label":"",
                    "parentDynamicPanel":"fe49e2a706744e048a3667060b9a3e69",
                    "panelIndex":1,
                    "type":"buttonShape",
                    "styleType":"paragraph",
                    "visible":true,
                    "style":{
                      "fontName":"'Helvetica Neue'",
                      "fontSize":"18px",
                      "horizontalAlignment":"right",
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF666666,
                        "opacity":1},
                      "location":{
                        "x":54,
                        "y":18},
                      "size":{
                        "width":92,
                        "height":22}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"87c0a50ec8474ff2a48c7489776d6e3c",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"fe49e2a706744e048a3667060b9a3e69",
                        "panelIndex":1,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontName":"'Helvetica Neue'",
                          "fontSize":"18px",
                          "horizontalAlignment":"right",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFF666666,
                            "opacity":1},
                          "location":{
                            "x":54,
                            "y":18},
                          "size":{
                            "width":92,
                            "height":22}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"1e467f8e63d14e87b4967a32746222e9",
                    "label":"",
                    "parentDynamicPanel":"fe49e2a706744e048a3667060b9a3e69",
                    "panelIndex":1,
                    "type":"buttonShape",
                    "styleType":"paragraph",
                    "visible":true,
                    "style":{
                      "fontName":"'Helvetica Neue'",
                      "fontSize":"12px",
                      "horizontalAlignment":"right",
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF666666,
                        "opacity":1},
                      "location":{
                        "x":79,
                        "y":0},
                      "size":{
                        "width":66,
                        "height":14}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"b19b8a20efe044748b51ac5b68a88f23",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"fe49e2a706744e048a3667060b9a3e69",
                        "panelIndex":1,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontName":"'Helvetica Neue'",
                          "fontSize":"12px",
                          "horizontalAlignment":"right",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFF666666,
                            "opacity":1},
                          "location":{
                            "x":79,
                            "y":0},
                          "size":{
                            "width":66,
                            "height":14}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"b8608e9f638b4660a8a6dee7aa9c3e36",
                    "label":"",
                    "parentDynamicPanel":"fe49e2a706744e048a3667060b9a3e69",
                    "panelIndex":1,
                    "type":"imageBox",
                    "styleType":"imageBox",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":162,
                        "y":4},
                      "size":{
                        "width":28,
                        "height":28}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"a559e57a14854d24a4609485d50f1ed3",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"fe49e2a706744e048a3667060b9a3e69",
                        "panelIndex":1,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":162,
                            "y":4},
                          "size":{
                            "width":28,
                            "height":28}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/alterar_senha/u14.png"}},
{
                    "id":"fda57ffd0f054a0d897d3b093d669bdd",
                    "label":"",
                    "parentDynamicPanel":"fe49e2a706744e048a3667060b9a3e69",
                    "panelIndex":1,
                    "type":"buttonShape",
                    "styleType":"paragraph",
                    "visible":true,
                    "style":{
                      "fontSize":"14px",
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF0066FF,
                        "opacity":1},
                      "location":{
                        "x":20,
                        "y":99},
                      "size":{
                        "width":170,
                        "height":16},
                      "rotation":"0",
                      "textRotation":"0"},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"5cc804455eb0464b85ff7cc456067800",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"fe49e2a706744e048a3667060b9a3e69",
                        "panelIndex":1,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontSize":"14px",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFF0066FF,
                            "opacity":1},
                          "location":{
                            "x":20,
                            "y":99},
                          "size":{
                            "width":170,
                            "height":16},
                          "rotation":"0",
                          "textRotation":"0"},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"Open Cadastro in Current Window",
                                "target":{
                                  "targetType":"page",
                                  "url":"cadastro.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"a6aab5213b4b4c3e85ac4afe1f257e91",
                    "label":"",
                    "parentDynamicPanel":"fe49e2a706744e048a3667060b9a3e69",
                    "panelIndex":1,
                    "type":"imageMapRegion",
                    "styleType":"imageMapRegion",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":155,
                        "y":0},
                      "size":{
                        "width":40,
                        "height":40}},
                    "adaptiveStyles":{
},
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"setPanelState",
                                "description":"Set dropdown-user to State1",
                                "panelsToStates":[{
                                    "panelPath":["fe49e2a706744e048a3667060b9a3e69"],
                                    "stateInfo":{
                                      "setStateType":"diagram",
                                      "stateNumber":1,
                                      "stateValue":{
                                        "exprType":"stringLiteral",
                                        "value":"1",
                                        "stos":[]},
                                      "loop":false,
                                      "showWhenSet":false,
                                      "options":{
                                        "compress":false}}}]}]}]}},
                    "tabbable":true}],
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFFFFF},
                  "image":null,
                  "imageHorizontalAlignment":"near",
                  "imageVerticalAlignment":"near",
                  "imageRepeat":"auto"},
                "adaptiveStyles":{
}}]},
{
            "id":"5280f6ab2ff541e3a08d602a96f14af5",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":8,
                "y":22},
              "size":{
                "width":252,
                "height":37}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"62a6cea60ded4fa9a507f5f197608b58",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":8,
                    "y":22},
                  "size":{
                    "width":252,
                    "height":37}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/cadastro/u19.png"}},
{
            "id":"fe5658b4dd484718b4046ef0c1c59a08",
            "label":"",
            "type":"imageMapRegion",
            "styleType":"imageMapRegion",
            "visible":true,
            "style":{
              "size":{
                "width":294,
                "height":81}},
            "adaptiveStyles":{
},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Dashboard in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"dashboard.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true}]}}},
  "objectPaths":{
    "09429fc5251b48158d5ddd9aa05fb88d":{
      "scriptId":"u0"},
    "b5d659edd1ff410b806a3748f8f37d45":{
      "scriptId":"u1"},
    "aa95471021e740a6bf20d84a931cdfe7":{
      "scriptId":"u2",
      "98f6e95fccd74ca4a04a4a23229806bc":{
        "scriptId":"u3"},
      "4c99a36cd31f4770a5042ff302db729c":{
        "scriptId":"u4"}},
    "864bbbfd36fc4d6d947ba8107be32899":{
      "scriptId":"u5",
      "a98ffd8705e040929b7ec88c6bbc264e":{
        "scriptId":"u6"},
      "8ab6195fdb274feb89b20710a3fc5997":{
        "scriptId":"u7"},
      "fa8b587736bf4c6ea418fcbeaa262c99":{
        "scriptId":"u8"},
      "fe49e2a706744e048a3667060b9a3e69":{
        "scriptId":"u9"},
      "6204713e832042c18bfcced89f8bce20":{
        "scriptId":"u10"},
      "62986fe513794f9c8abec46cde2877a7":{
        "scriptId":"u11"},
      "c076f0909fb542b49a704785b1078434":{
        "scriptId":"u12"},
      "c925cae17de947179805ef69d39926c2":{
        "scriptId":"u13"},
      "11cf14182664433ebd8e6f1a0ee85ffe":{
        "scriptId":"u14"},
      "9a3f85fce4df4d77b97c4565d725eec5":{
        "scriptId":"u15"},
      "f6b7572cbf4c448c9f6afbaa10bfad13":{
        "scriptId":"u16"},
      "9ed6828666f447f7a7e0ceb44c3afe85":{
        "scriptId":"u17"},
      "bd713743a4fd4100b43ccca1b70ca994":{
        "scriptId":"u18"},
      "c45b355677264302bfe15da0b7663744":{
        "scriptId":"u19"},
      "3dee6155c57042de849e03626aa42332":{
        "scriptId":"u20"},
      "5b7ee831d3d94eb7bcd42535e0e07829":{
        "scriptId":"u21"},
      "78e83a886be14343987e121a22698ce9":{
        "scriptId":"u22"},
      "048b499446c24a21965e02b1a1c2cda1":{
        "scriptId":"u23"},
      "e07433f9f99a4fcca3478cabd32cb61e":{
        "scriptId":"u24"},
      "87c0a50ec8474ff2a48c7489776d6e3c":{
        "scriptId":"u25"},
      "1e467f8e63d14e87b4967a32746222e9":{
        "scriptId":"u26"},
      "b19b8a20efe044748b51ac5b68a88f23":{
        "scriptId":"u27"},
      "b8608e9f638b4660a8a6dee7aa9c3e36":{
        "scriptId":"u28"},
      "a559e57a14854d24a4609485d50f1ed3":{
        "scriptId":"u29"},
      "fda57ffd0f054a0d897d3b093d669bdd":{
        "scriptId":"u30"},
      "5cc804455eb0464b85ff7cc456067800":{
        "scriptId":"u31"},
      "a6aab5213b4b4c3e85ac4afe1f257e91":{
        "scriptId":"u32"},
      "5280f6ab2ff541e3a08d602a96f14af5":{
        "scriptId":"u33"},
      "62a6cea60ded4fa9a507f5f197608b58":{
        "scriptId":"u34"},
      "fe5658b4dd484718b4046ef0c1c59a08":{
        "scriptId":"u35"}},
    "9ad53d598b5641baa9e4979999c6bc3b":{
      "scriptId":"u36"},
    "0e01186751d84be4bd23afa0dcc627f5":{
      "scriptId":"u37"},
    "5a5de49db5af4c4da0961bd6618e34f8":{
      "scriptId":"u38"},
    "463ea6ffb337461085d6c9c920f2ccc1":{
      "scriptId":"u39"},
    "c3ed4c9ccc214f2b9fb8dca34ec511d4":{
      "scriptId":"u40"},
    "abbcc70f05c04222b0b7fd245c408eac":{
      "scriptId":"u41"},
    "21e7dd52a6484ca0a295d0fc45154f62":{
      "scriptId":"u42"},
    "0f96da0930664bcdad4d4a9a9588fd30":{
      "scriptId":"u43"},
    "17073eff9d474580ab116cbba990e038":{
      "scriptId":"u44"},
    "70da89aea64d429f8b9f8d12496169a8":{
      "scriptId":"u45"},
    "92fed74d4044416bafc8ccfcaece8114":{
      "scriptId":"u46"},
    "cfdfffcbdc634c05bf33d664b3a876f1":{
      "scriptId":"u47"},
    "b52f8c1ad77b4bbeb2152efbad03d183":{
      "scriptId":"u48"},
    "b8f3c8ce8a144d0595db6ddb05565cd5":{
      "scriptId":"u49"},
    "1f4bab3f8f6b4cec8cda0aa3382a2dd7":{
      "scriptId":"u50"},
    "41842d3fa0c64497bbcc87e821d5e32d":{
      "scriptId":"u51"},
    "664b3d21649f438fbac17684194b606e":{
      "scriptId":"u52"},
    "01c45bc1aa3843199297b6479a8056ef":{
      "scriptId":"u53"},
    "baa9eea046394b0da1919ae9614e7d2b":{
      "scriptId":"u54"},
    "779e13b173ed464895eba3caac71f2ec":{
      "scriptId":"u55"},
    "06f536521cae41ab95ec14d19ce8d785":{
      "scriptId":"u56"},
    "faa6b1b063ab4a4b908815b97b922248":{
      "scriptId":"u57"},
    "f626173d0a3e43a591cd4fa6b07e9fdc":{
      "scriptId":"u58"},
    "3c222b064ff0400ca3094878be96ceef":{
      "scriptId":"u59"},
    "df120cc926ad4ddf891404baff865375":{
      "scriptId":"u60"},
    "218d3b3600964a27b8e515acd3cf327c":{
      "scriptId":"u61"},
    "1e0a99b085fb4758a0800817af4f564e":{
      "scriptId":"u62"},
    "a172e17379484dc38164da80254a519f":{
      "scriptId":"u63"},
    "06a29402116b48de8264bac6631ee9e5":{
      "scriptId":"u64"},
    "66e7016d2a5e4efbb0acd017037dcd06":{
      "scriptId":"u65"},
    "b53d7a84278046779f9b94a4dd95dc78":{
      "scriptId":"u66"},
    "0f6bdad0cf6a4591b3f2125d3c7ba0d9":{
      "scriptId":"u67"},
    "85d5c13e68c84f2db5259b8daa0cc54e":{
      "scriptId":"u68"},
    "92d962bcc3e240728594f73e89c13129":{
      "scriptId":"u69"},
    "75384e5c5aa24e2bbda7d791067a6415":{
      "scriptId":"u70"},
    "d8d00f31352847de81e9195742bc19a2":{
      "scriptId":"u71"},
    "ba88ed167bd64c38a7789e916d0eb53e":{
      "scriptId":"u72"},
    "eff1e005031d47ce8c59d0dfb607c92b":{
      "scriptId":"u73"},
    "041fa7a8160443d3a1608e18a7a91e18":{
      "scriptId":"u74"},
    "a187c38c64c441e4aa38cf032fb7baad":{
      "scriptId":"u75"},
    "0481ae9782ec41889de063769f898a1c":{
      "scriptId":"u76"},
    "36aa22bfdc55414d9feb756afb7aa16c":{
      "scriptId":"u77"},
    "dbaf0bee84584b8da6a22b12558c0e94":{
      "scriptId":"u78"},
    "5cdf4efa33234fe6a58b870aa1ba6f4e":{
      "scriptId":"u79"},
    "bbd6fae126ba4a58af5d45d5154b633d":{
      "scriptId":"u80"},
    "b2b179fbe1544dadad335a861d0909d6":{
      "scriptId":"u81"},
    "a7b2d7bdf8624d47b64c606b925e7c0b":{
      "scriptId":"u82"},
    "b16adc15eb2643fcafe43d78f7d95b04":{
      "scriptId":"u83"},
    "5bbb8b629f2c4166aad55c6fb4760791":{
      "scriptId":"u84"},
    "e850e3751db54a30be6e43650c50aa9e":{
      "scriptId":"u85"},
    "7b633e2d169940f19cb4ea065349f1be":{
      "scriptId":"u86"},
    "7b888a413846440382afcbabb2ae37e5":{
      "scriptId":"u87"},
    "20579b6553014929b5ff37001869d980":{
      "scriptId":"u88"}}});