$axure.loadCurrentPage({
  "url":"login.html",
  "generationDate":new Date(1423764002213.77),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"3ec5d42c0b954bb59ef48afbf27f69e8",
    "type":"Axure:Page",
    "name":"Login",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"1a2a69672892499893a3bcca7393ec13",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "size":{
              "width":980,
              "height":850},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"481200e2d86a40e795a1013e1dfc5af5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "size":{
                  "width":980,
                  "height":850},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/cadastro/u0.png"}},
{
          "id":"4d6110bcf35b4c2eb182daac268431e7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":272,
              "y":220},
            "size":{
              "width":440,
              "height":300},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"4",
            "outerShadow":{
              "on":true,
              "offsetX":0,
              "offsetY":4,
              "blurRadius":3,
              "color":{
                "r":134,
                "g":134,
                "b":134,
                "a":0.219607843137255}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eee1e2e209ba4f7c93c92eebd1c09ceb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":272,
                  "y":220},
                "size":{
                  "width":440,
                  "height":300},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"4",
                "outerShadow":{
                  "on":true,
                  "offsetX":0,
                  "offsetY":4,
                  "blurRadius":3,
                  "color":{
                    "r":134,
                    "g":134,
                    "b":134,
                    "a":0.219607843137255}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/login/u2.png"}},
{
          "id":"fd999c63941446e39a8d9b18ec13e5e4",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":302,
              "y":285},
            "size":{
              "width":380,
              "height":45}},
          "adaptiveStyles":{
}},
{
          "id":"e0f0a0636cb242dc8615fa797c751186",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":302,
              "y":345},
            "size":{
              "width":380,
              "height":45}},
          "adaptiveStyles":{
}},
{
          "id":"afab04c3dba84d77985cceadda853263",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negrito', 'Arial'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF0099FF},
            "location":{
              "x":302,
              "y":440},
            "size":{
              "width":380,
              "height":41},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"37f4d9d025814769812ec43829472472",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negrito', 'Arial'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0099FF},
                "location":{
                  "x":302,
                  "y":440},
                "size":{
                  "width":380,
                  "height":41},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"2"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Link in Current Window",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/cadastro/u12.png"}},
{
          "id":"8a7efca3335049ce86a5ef48ba9cf0cb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":302,
              "y":400},
            "size":{
              "width":350,
              "height":14},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4b3b064c859c464ab8636c22471a5eab",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":302,
                  "y":400},
                "size":{
                  "width":350,
                  "height":14},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9b1c48cef88d490daaf7204482d915b8",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":810},
            "size":{
              "width":1277,
              "height":33}},
          "adaptiveStyles":{
},
          "masterId":"4226023da38e45578b3ec7ef42593243"},
{
          "id":"fdb52f73c8e14a5e83d5509fe077c266",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "horizontalAlignment":"center",
            "location":{
              "x":300,
              "y":127},
            "size":{
              "width":363,
              "height":38}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cf275158ddb24cbe824943e25c23d568",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "horizontalAlignment":"center",
                "location":{
                  "x":300,
                  "y":127},
                "size":{
                  "width":363,
                  "height":38}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"29568e2e758b4af4af93757f71824861",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":302,
              "y":247},
            "size":{
              "width":94,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3ae73df21fd94a55af2d187ad584b1a6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":302,
                  "y":247},
                "size":{
                  "width":94,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"12279c313a174bd1a33b4a68823f8b59",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":358,
              "y":60},
            "size":{
              "width":252,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8d367812db0e4001b5092df6f6db92a0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":358,
                  "y":60},
                "size":{
                  "width":252,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/cadastro/u19.png"}}]}},
  "masters":{
    "4226023da38e45578b3ec7ef42593243":{
      "packageId":"4226023da38e45578b3ec7ef42593243",
      "type":"Axure:Master",
      "name":"footer",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"98f6e95fccd74ca4a04a4a23229806bc",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"12px",
              "verticalAlignment":"middle",
              "fill":{
                "fillType":"solid",
                "color":0xFFF2F2F2},
              "location":{
                "x":240,
                "y":0},
              "size":{
                "width":780,
                "height":40}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"4c99a36cd31f4770a5042ff302db729c",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"12px",
                  "verticalAlignment":"middle",
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2},
                  "location":{
                    "x":240,
                    "y":0},
                  "size":{
                    "width":780,
                    "height":40}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/cadastro/u3.png"}}]}}},
  "objectPaths":{
    "1a2a69672892499893a3bcca7393ec13":{
      "scriptId":"u0"},
    "481200e2d86a40e795a1013e1dfc5af5":{
      "scriptId":"u1"},
    "4d6110bcf35b4c2eb182daac268431e7":{
      "scriptId":"u2"},
    "eee1e2e209ba4f7c93c92eebd1c09ceb":{
      "scriptId":"u3"},
    "fd999c63941446e39a8d9b18ec13e5e4":{
      "scriptId":"u4"},
    "e0f0a0636cb242dc8615fa797c751186":{
      "scriptId":"u5"},
    "afab04c3dba84d77985cceadda853263":{
      "scriptId":"u6"},
    "37f4d9d025814769812ec43829472472":{
      "scriptId":"u7"},
    "8a7efca3335049ce86a5ef48ba9cf0cb":{
      "scriptId":"u8"},
    "4b3b064c859c464ab8636c22471a5eab":{
      "scriptId":"u9"},
    "9b1c48cef88d490daaf7204482d915b8":{
      "scriptId":"u10",
      "98f6e95fccd74ca4a04a4a23229806bc":{
        "scriptId":"u11"},
      "4c99a36cd31f4770a5042ff302db729c":{
        "scriptId":"u12"}},
    "fdb52f73c8e14a5e83d5509fe077c266":{
      "scriptId":"u13"},
    "cf275158ddb24cbe824943e25c23d568":{
      "scriptId":"u14"},
    "29568e2e758b4af4af93757f71824861":{
      "scriptId":"u15"},
    "3ae73df21fd94a55af2d187ad584b1a6":{
      "scriptId":"u16"},
    "12279c313a174bd1a33b4a68823f8b59":{
      "scriptId":"u17"},
    "8d367812db0e4001b5092df6f6db92a0":{
      "scriptId":"u18"}}});