$axure.loadCurrentPage({
  "url":"feedback.html",
  "generationDate":new Date(1423764002672.88),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"b4c4b970c5fa43a2a6f4f3512277af0c",
    "type":"Axure:Page",
    "name":"Feedback",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"934ce1f594db474289f7b2671c9446c9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "size":{
              "width":980,
              "height":850},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"972b7bdf138e4d54a97cf13b0120bdfd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "size":{
                  "width":980,
                  "height":850},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/cadastro/u0.png"}},
{
          "id":"3e52463e598248fbb2c1e10b22c3955e",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":810},
            "size":{
              "width":1277,
              "height":33}},
          "adaptiveStyles":{
},
          "masterId":"4226023da38e45578b3ec7ef42593243"},
{
          "id":"44d521a28ede48258da466b78b7b2f13",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negrito', 'Arial'",
            "fontWeight":"700",
            "fill":{
              "fillType":"solid",
              "color":0xE0FFFFCC},
            "location":{
              "x":77,
              "y":-10},
            "size":{
              "width":790,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1e3b0be2b75c4d42b258e0ae1739314f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negrito', 'Arial'",
                "fontWeight":"700",
                "fill":{
                  "fillType":"solid",
                  "color":0xE0FFFFCC},
                "location":{
                  "x":77,
                  "y":-10},
                "size":{
                  "width":790,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/tratamento_de_erro__cadastro_existente/u19.png"}},
{
          "id":"ed923e558e7f4657b946dd097c18a946",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":272,
              "y":220},
            "size":{
              "width":440,
              "height":300},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"4",
            "outerShadow":{
              "on":true,
              "offsetX":0,
              "offsetY":4,
              "blurRadius":3,
              "color":{
                "r":134,
                "g":134,
                "b":134,
                "a":0.219607843137255}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f4a019c4dcd84499b059177ca02b3892",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":272,
                  "y":220},
                "size":{
                  "width":440,
                  "height":300},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"4",
                "outerShadow":{
                  "on":true,
                  "offsetX":0,
                  "offsetY":4,
                  "blurRadius":3,
                  "color":{
                    "r":134,
                    "g":134,
                    "b":134,
                    "a":0.219607843137255}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/login/u2.png"}},
{
          "id":"9a570a9628474cfeabe6a8f076cd5387",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":302,
              "y":285},
            "size":{
              "width":380,
              "height":45}},
          "adaptiveStyles":{
}},
{
          "id":"3051c657c80349d9a79fe23634a4b19e",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":302,
              "y":345},
            "size":{
              "width":380,
              "height":45}},
          "adaptiveStyles":{
}},
{
          "id":"85188b0270b649fcad50c8274b909329",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negrito', 'Arial'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF0099FF},
            "location":{
              "x":302,
              "y":440},
            "size":{
              "width":380,
              "height":41},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f1a21bf8116f4b2c87980970a6c6a67c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negrito', 'Arial'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0099FF},
                "location":{
                  "x":302,
                  "y":440},
                "size":{
                  "width":380,
                  "height":41},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"2"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Link in Current Window",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/cadastro/u12.png"}},
{
          "id":"10cb8f05228d41fd98fa2b4135cc6c0f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":302,
              "y":400},
            "size":{
              "width":350,
              "height":14},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2272fe7280b540809e4c79458d28d209",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":302,
                  "y":400},
                "size":{
                  "width":350,
                  "height":14},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"16459062d6c0412d9db5576f64be3ed1",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":302,
              "y":247},
            "size":{
              "width":94,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f856a1441e9045a58b403233c348a0e6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":302,
                  "y":247},
                "size":{
                  "width":94,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"28f8fbb5f66946baac58a0145721b105",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "horizontalAlignment":"center",
            "location":{
              "x":300,
              "y":127},
            "size":{
              "width":363,
              "height":38}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2c410c06114c427bb7daedb4ed5067ba",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "horizontalAlignment":"center",
                "location":{
                  "x":300,
                  "y":127},
                "size":{
                  "width":363,
                  "height":38}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6b668965963c41298c85e9439b5a7f7f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":358,
              "y":60},
            "size":{
              "width":252,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d38c277ea7d94a8296bae8adb766b39e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":358,
                  "y":60},
                "size":{
                  "width":252,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/cadastro/u19.png"}}]}},
  "masters":{
    "4226023da38e45578b3ec7ef42593243":{
      "packageId":"4226023da38e45578b3ec7ef42593243",
      "type":"Axure:Master",
      "name":"footer",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"98f6e95fccd74ca4a04a4a23229806bc",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"12px",
              "verticalAlignment":"middle",
              "fill":{
                "fillType":"solid",
                "color":0xFFF2F2F2},
              "location":{
                "x":240,
                "y":0},
              "size":{
                "width":780,
                "height":40}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"4c99a36cd31f4770a5042ff302db729c",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"12px",
                  "verticalAlignment":"middle",
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2},
                  "location":{
                    "x":240,
                    "y":0},
                  "size":{
                    "width":780,
                    "height":40}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/cadastro/u3.png"}}]}}},
  "objectPaths":{
    "934ce1f594db474289f7b2671c9446c9":{
      "scriptId":"u0"},
    "972b7bdf138e4d54a97cf13b0120bdfd":{
      "scriptId":"u1"},
    "3e52463e598248fbb2c1e10b22c3955e":{
      "scriptId":"u2",
      "98f6e95fccd74ca4a04a4a23229806bc":{
        "scriptId":"u3"},
      "4c99a36cd31f4770a5042ff302db729c":{
        "scriptId":"u4"}},
    "44d521a28ede48258da466b78b7b2f13":{
      "scriptId":"u5"},
    "1e3b0be2b75c4d42b258e0ae1739314f":{
      "scriptId":"u6"},
    "ed923e558e7f4657b946dd097c18a946":{
      "scriptId":"u7"},
    "f4a019c4dcd84499b059177ca02b3892":{
      "scriptId":"u8"},
    "9a570a9628474cfeabe6a8f076cd5387":{
      "scriptId":"u9"},
    "3051c657c80349d9a79fe23634a4b19e":{
      "scriptId":"u10"},
    "85188b0270b649fcad50c8274b909329":{
      "scriptId":"u11"},
    "f1a21bf8116f4b2c87980970a6c6a67c":{
      "scriptId":"u12"},
    "10cb8f05228d41fd98fa2b4135cc6c0f":{
      "scriptId":"u13"},
    "2272fe7280b540809e4c79458d28d209":{
      "scriptId":"u14"},
    "16459062d6c0412d9db5576f64be3ed1":{
      "scriptId":"u15"},
    "f856a1441e9045a58b403233c348a0e6":{
      "scriptId":"u16"},
    "28f8fbb5f66946baac58a0145721b105":{
      "scriptId":"u17"},
    "2c410c06114c427bb7daedb4ed5067ba":{
      "scriptId":"u18"},
    "6b668965963c41298c85e9439b5a7f7f":{
      "scriptId":"u19"},
    "d38c277ea7d94a8296bae8adb766b39e":{
      "scriptId":"u20"}}});