$axure.loadCurrentPage({
  "url":"detalhe_campanha.html",
  "generationDate":new Date(1421410014995.16),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"15c8af337b7e4b018c83db01ec88d09a",
    "type":"Axure:Page",
    "name":"Detalhe_campanha",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"6fa83c7d691d42b0a5f191fc856b3fa2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "size":{
              "width":980,
              "height":890},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cf034a8f1c4d4be4b11d57199d5243bb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "size":{
                  "width":980,
                  "height":890},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/detalhe_relatorio/u0.png"}},
{
          "id":"324a7a7607614ef9b58cca993ccc4d44",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":850},
            "size":{
              "width":780,
              "height":40}},
          "adaptiveStyles":{
},
          "masterId":"4226023da38e45578b3ec7ef42593243"},
{
          "id":"0a27b825e7f647ba83833091b55d29e2",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"fbc37d401c784c2abad213112443341e"},
{
          "id":"a0cb5b4062a6404a96529286481624a5",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":34,
              "y":138},
            "size":{
              "width":446,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"77798baf3ba1482187aa8a9cbf9313c7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":34,
                  "y":138},
                "size":{
                  "width":446,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ec87a0f6424b4713af21dafb588a3986",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"12px",
            "fontWeight":"400",
            "underline":true,
            "location":{
              "x":34,
              "y":112},
            "size":{
              "width":216,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"50e44a113fcb4635a6814d731583b9a1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"12px",
                "fontWeight":"400",
                "underline":true,
                "location":{
                  "x":34,
                  "y":112},
                "size":{
                  "width":216,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Campanhas in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"campanhas.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"711e5fa157bb40329b0b134250ce1d0a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":34,
              "y":433},
            "size":{
              "width":255,
              "height":32},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"957657e39ce944f9af48c30ec8bec257",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":34,
                  "y":433},
                "size":{
                  "width":255,
                  "height":32},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/detalhe_relatorio/u45.png"}},
{
          "id":"376b7e0898b94bdabc2b25653b542309",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":35,
              "y":409},
            "size":{
              "width":220,
              "height":17},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e320bebf96c244538cfe6fbe9ccbd38d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":35,
                  "y":409},
                "size":{
                  "width":220,
                  "height":17},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"009b4b1c9ca14d5783d3630e8e364d83",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":35,
              "y":310},
            "size":{
              "width":220,
              "height":17},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"04fab6e82f894b2f92c4d143b665dd0e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":35,
                  "y":310},
                "size":{
                  "width":220,
                  "height":17},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ff04f3589eea4697a7de28e622de8fcf",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negrito', 'Arial'",
            "fontSize":"11px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":300,
              "y":334},
            "size":{
              "width":130,
              "height":31},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d844ddafc94b435eb5ae9cff95cee65d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negrito', 'Arial'",
                "fontSize":"11px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":300,
                  "y":334},
                "size":{
                  "width":130,
                  "height":31},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"2"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/detalhe_relatorio/u51.png"}},
{
          "id":"e5e9c768248243aba1a015b96cef7001",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":35,
              "y":333},
            "size":{
              "width":255,
              "height":32},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"baf779d19194449f9a21e7c4bc8faa79",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":35,
                  "y":333},
                "size":{
                  "width":255,
                  "height":32},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/detalhe_relatorio/u45.png"}},
{
          "id":"5aa168642edb41e6a7932d2a84476fda",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":440,
              "y":342},
            "size":{
              "width":200,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0ae9b079664a4f7b862c5af9fe0c6fec",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":440,
                  "y":342},
                "size":{
                  "width":200,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3402fba56da34c4293b83fafd4ea7fcd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Itálico', 'Arial'",
            "fontSize":"12px",
            "fontStyle":"italic",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":34,
              "y":470},
            "size":{
              "width":195,
              "height":15},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7cc6464cee264399ab882991a7256e3d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Itálico', 'Arial'",
                "fontSize":"12px",
                "fontStyle":"italic",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":34,
                  "y":470},
                "size":{
                  "width":195,
                  "height":15},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f43a3c57b81748fcbe558ec003d8dcd6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negrito', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF0099FF},
            "location":{
              "x":30,
              "y":587},
            "size":{
              "width":96,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9f91f945ab764b87b1627b9f853000d7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negrito', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0099FF},
                "location":{
                  "x":30,
                  "y":587},
                "size":{
                  "width":96,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"2"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/detalhe_relatorio/u59.png"}},
{
          "id":"5d8da2567d9f42b1a717ccb9788ac68c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":33,
              "y":520},
            "size":{
              "width":57,
              "height":17},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"84b419c247994e2bb089bcda8c2f7086",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":33,
                  "y":520},
                "size":{
                  "width":57,
                  "height":17},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a6977c9246f94a2bb349b470eb96f7db",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":522},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"caac91e0ecc44727af0b8c556ff04cc4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":522},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"b758a6b7a2b54f4a9f9e97ef61e05d5b",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":187,
              "y":522},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f1a0d27b367d4bad83bf8905fe79987e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":187,
                  "y":522},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"bf41d5ee372b4e27be651f09591e0422",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":34,
              "y":557},
            "size":{
              "width":876,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/detalhe_calendario/u51_line.png"}},
{
          "id":"3d15b67f390c47faae9f83096b7bba0c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":35,
              "y":212},
            "size":{
              "width":125,
              "height":17},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"38664ea3da1a43e296bc7a2fb2a17692",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":35,
                  "y":212},
                "size":{
                  "width":125,
                  "height":17},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6f7816cf259b4e228a1e56ffc2130b34",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negrito', 'Arial'",
            "fontSize":"11px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":300,
              "y":239},
            "size":{
              "width":130,
              "height":31},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"96af25aad88e47e6be3a1a691fa2d744",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negrito', 'Arial'",
                "fontSize":"11px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":300,
                  "y":239},
                "size":{
                  "width":130,
                  "height":31},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"2"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/detalhe_relatorio/u51.png"}},
{
          "id":"df168e3bbb904edab5623e9bad24e1f3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":35,
              "y":238},
            "size":{
              "width":255,
              "height":32},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5b126a279d6b4efb93220f2cd3b667ef",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":35,
                  "y":238},
                "size":{
                  "width":255,
                  "height":32},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/detalhe_relatorio/u45.png"}},
{
          "id":"575ae392bfc44df3a98ad324ffde2de0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":440,
              "y":246},
            "size":{
              "width":200,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"841163d3419947bbab6714a77c04c0b7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":440,
                  "y":246},
                "size":{
                  "width":200,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7c61db06d2bb496a80eda1f4e2397e30",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Itálico', 'Arial'",
            "fontSize":"12px",
            "fontStyle":"italic",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":35,
              "y":275},
            "size":{
              "width":195,
              "height":15},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d979b9e3b6184fe7a0ad80cb2940eba6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Itálico', 'Arial'",
                "fontSize":"12px",
                "fontStyle":"italic",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":35,
                  "y":275},
                "size":{
                  "width":195,
                  "height":15},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f2399530b93b4d23864fc67669f38ff5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Itálico', 'Arial'",
            "fontSize":"12px",
            "fontStyle":"italic",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":35,
              "y":371},
            "size":{
              "width":195,
              "height":15},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e3ae34c0959c40ec8f052224f2764e77",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Itálico', 'Arial'",
                "fontSize":"12px",
                "fontStyle":"italic",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":35,
                  "y":371},
                "size":{
                  "width":195,
                  "height":15},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d30cc0a3136147d7923d1764fa385502",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"12px",
            "fontWeight":"400",
            "underline":true,
            "location":{
              "x":34,
              "y":770},
            "size":{
              "width":236,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c2804a3fd7244544a7af4cb570fdd733",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"12px",
                "fontWeight":"400",
                "underline":true,
                "location":{
                  "x":34,
                  "y":770},
                "size":{
                  "width":236,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Campanhas in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"campanhas.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"66c852865ca74550a79b46c338976247",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":34,
              "y":740},
            "size":{
              "width":876,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/detalhe_calendario/u51_line.png"}}]}},
  "masters":{
    "4226023da38e45578b3ec7ef42593243":{
      "packageId":"4226023da38e45578b3ec7ef42593243",
      "type":"Axure:Master",
      "name":"footer",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"98f6e95fccd74ca4a04a4a23229806bc",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"12px",
              "verticalAlignment":"middle",
              "fill":{
                "fillType":"solid",
                "color":0xFFF2F2F2},
              "location":{
                "x":240,
                "y":0},
              "size":{
                "width":780,
                "height":40}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"4c99a36cd31f4770a5042ff302db729c",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"12px",
                  "verticalAlignment":"middle",
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2},
                  "location":{
                    "x":240,
                    "y":0},
                  "size":{
                    "width":780,
                    "height":40}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/dashboard/u3.png"}}]}},
    "fbc37d401c784c2abad213112443341e":{
      "packageId":"fbc37d401c784c2abad213112443341e",
      "type":"Axure:Master",
      "name":"header_gerente",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"a98ffd8705e040929b7ec88c6bbc264e",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "size":{
                "width":980,
                "height":80},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8ab6195fdb274feb89b20710a3fc5997",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":980,
                    "height":80},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/dashboard/u8.png"}},
{
            "id":"fa8b587736bf4c6ea418fcbeaa262c99",
            "label":"",
            "type":"verticalLine",
            "styleType":"verticalLine",
            "visible":true,
            "style":{
              "location":{
                "x":284,
                "y":0},
              "size":{
                "width":10,
                "height":81},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFE4E4E4}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/dashboard/u10_line.png"}},
{
            "id":"38639eb7baa94a2c8bedf245688e39bd",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":276,
                "y":26},
              "size":{
                "width":28,
                "height":28},
              "borderWidth":"2",
              "borderFill":{
                "fillType":"solid",
                "color":0xFFBCBCBC},
              "cornerRadiusTopLeft":"100"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b1f5768804d347539bfd076bab6dbe28",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":276,
                    "y":26},
                  "size":{
                    "width":28,
                    "height":28},
                  "borderWidth":"2",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFBCBCBC},
                  "cornerRadiusTopLeft":"100"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/dashboard/u11.png"}},
{
            "id":"fe49e2a706744e048a3667060b9a3e69",
            "label":"dropdown-user",
            "type":"dynamicPanel",
            "styleType":"dynamicPanel",
            "visible":true,
            "style":{
              "location":{
                "x":780,
                "y":22},
              "size":{
                "width":10,
                "height":10}},
            "adaptiveStyles":{
},
            "scrollbars":"none",
            "fitToContent":true,
            "propagate":false,
            "diagrams":[{
                "id":"9988237930104c0f96653f270533b92b",
                "label":"State1",
                "type":"Axure:PanelDiagram",
                "objects":[{
                    "id":"6204713e832042c18bfcced89f8bce20",
                    "label":"",
                    "parentDynamicPanel":"fe49e2a706744e048a3667060b9a3e69",
                    "panelIndex":0,
                    "type":"buttonShape",
                    "styleType":"paragraph",
                    "visible":true,
                    "style":{
                      "fontName":"'Helvetica Neue'",
                      "fontSize":"18px",
                      "horizontalAlignment":"right",
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF666666,
                        "opacity":1},
                      "location":{
                        "x":54,
                        "y":18},
                      "size":{
                        "width":92,
                        "height":22}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"62986fe513794f9c8abec46cde2877a7",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"fe49e2a706744e048a3667060b9a3e69",
                        "panelIndex":0,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontName":"'Helvetica Neue'",
                          "fontSize":"18px",
                          "horizontalAlignment":"right",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFF666666,
                            "opacity":1},
                          "location":{
                            "x":54,
                            "y":18},
                          "size":{
                            "width":92,
                            "height":22}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"c076f0909fb542b49a704785b1078434",
                    "label":"",
                    "parentDynamicPanel":"fe49e2a706744e048a3667060b9a3e69",
                    "panelIndex":0,
                    "type":"buttonShape",
                    "styleType":"paragraph",
                    "visible":true,
                    "style":{
                      "fontName":"'Helvetica Neue'",
                      "fontSize":"12px",
                      "horizontalAlignment":"right",
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF666666,
                        "opacity":1},
                      "location":{
                        "x":79,
                        "y":0},
                      "size":{
                        "width":66,
                        "height":14}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"c925cae17de947179805ef69d39926c2",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"fe49e2a706744e048a3667060b9a3e69",
                        "panelIndex":0,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontName":"'Helvetica Neue'",
                          "fontSize":"12px",
                          "horizontalAlignment":"right",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFF666666,
                            "opacity":1},
                          "location":{
                            "x":79,
                            "y":0},
                          "size":{
                            "width":66,
                            "height":14}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"11cf14182664433ebd8e6f1a0ee85ffe",
                    "label":"",
                    "parentDynamicPanel":"fe49e2a706744e048a3667060b9a3e69",
                    "panelIndex":0,
                    "type":"imageBox",
                    "styleType":"imageBox",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":162,
                        "y":4},
                      "size":{
                        "width":28,
                        "height":28}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"9a3f85fce4df4d77b97c4565d725eec5",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"fe49e2a706744e048a3667060b9a3e69",
                        "panelIndex":0,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":162,
                            "y":4},
                          "size":{
                            "width":28,
                            "height":28}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/dashboard/u18.png"}},
{
                    "id":"f6b7572cbf4c448c9f6afbaa10bfad13",
                    "label":"",
                    "parentDynamicPanel":"fe49e2a706744e048a3667060b9a3e69",
                    "panelIndex":0,
                    "type":"imageMapRegion",
                    "styleType":"imageMapRegion",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":155,
                        "y":0},
                      "size":{
                        "width":40,
                        "height":40}},
                    "adaptiveStyles":{
},
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"setPanelState",
                                "description":"Set dropdown-user to State2",
                                "panelsToStates":[{
                                    "panelPath":["fe49e2a706744e048a3667060b9a3e69"],
                                    "stateInfo":{
                                      "setStateType":"diagram",
                                      "stateNumber":2,
                                      "stateValue":{
                                        "exprType":"stringLiteral",
                                        "value":"1",
                                        "stos":[]},
                                      "loop":false,
                                      "showWhenSet":false,
                                      "options":{
                                        "compress":false}}}]}]}]}},
                    "tabbable":true}],
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFFFFF},
                  "image":null,
                  "imageHorizontalAlignment":"near",
                  "imageVerticalAlignment":"near",
                  "imageRepeat":"auto"},
                "adaptiveStyles":{
}},
{
                "id":"5ab577ad4f0d4fea8d6efa85d310a7cd",
                "label":"State2",
                "type":"Axure:PanelDiagram",
                "objects":[{
                    "id":"9ed6828666f447f7a7e0ceb44c3afe85",
                    "label":"",
                    "parentDynamicPanel":"fe49e2a706744e048a3667060b9a3e69",
                    "panelIndex":1,
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFE4E4E4},
                      "location":{
                        "x":0,
                        "y":47},
                      "size":{
                        "width":200,
                        "height":83},
                      "borderFill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "cornerRadiusTopLeft":"5"},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"bd713743a4fd4100b43ccca1b70ca994",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"fe49e2a706744e048a3667060b9a3e69",
                        "panelIndex":1,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFE4E4E4},
                          "location":{
                            "x":0,
                            "y":47},
                          "size":{
                            "width":200,
                            "height":83},
                          "borderFill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "cornerRadiusTopLeft":"5"},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/dashboard/u21.png"}},
{
                    "id":"c45b355677264302bfe15da0b7663744",
                    "label":"",
                    "parentDynamicPanel":"fe49e2a706744e048a3667060b9a3e69",
                    "panelIndex":1,
                    "type":"buttonShape",
                    "styleType":"paragraph",
                    "visible":true,
                    "style":{
                      "fontSize":"14px",
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF000000,
                        "opacity":1},
                      "location":{
                        "x":20,
                        "y":58},
                      "size":{
                        "width":170,
                        "height":16},
                      "rotation":"0",
                      "textRotation":"0"},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"3dee6155c57042de849e03626aa42332",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"fe49e2a706744e048a3667060b9a3e69",
                        "panelIndex":1,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontSize":"14px",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFF000000,
                            "opacity":1},
                          "location":{
                            "x":20,
                            "y":58},
                          "size":{
                            "width":170,
                            "height":16},
                          "rotation":"0",
                          "textRotation":"0"},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"Open Link in Current Window",
                                "target":{
                                  "targetType":"page",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"5b7ee831d3d94eb7bcd42535e0e07829",
                    "label":"",
                    "parentDynamicPanel":"fe49e2a706744e048a3667060b9a3e69",
                    "panelIndex":1,
                    "type":"horizontalLine",
                    "styleType":"horizontalLine",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":0,
                        "y":82},
                      "size":{
                        "width":200,
                        "height":10},
                      "borderFill":{
                        "fillType":"solid",
                        "color":0xFFCCCCCC}},
                    "adaptiveStyles":{
},
                    "images":{
                      "start~":"resources/images/transparent.gif",
                      "end~":"resources/images/transparent.gif",
                      "line~":"images/dashboard/u25_line.png"}},
{
                    "id":"78e83a886be14343987e121a22698ce9",
                    "label":"",
                    "parentDynamicPanel":"fe49e2a706744e048a3667060b9a3e69",
                    "panelIndex":1,
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFE4E4E4},
                      "location":{
                        "x":166,
                        "y":36},
                      "size":{
                        "width":20,
                        "height":15},
                      "borderFill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "cornerRadiusTopLeft":"5"},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"048b499446c24a21965e02b1a1c2cda1",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"fe49e2a706744e048a3667060b9a3e69",
                        "panelIndex":1,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFE4E4E4},
                          "location":{
                            "x":166,
                            "y":36},
                          "size":{
                            "width":20,
                            "height":15},
                          "borderFill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "cornerRadiusTopLeft":"5"},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/dashboard/u26.png"}},
{
                    "id":"e07433f9f99a4fcca3478cabd32cb61e",
                    "label":"",
                    "parentDynamicPanel":"fe49e2a706744e048a3667060b9a3e69",
                    "panelIndex":1,
                    "type":"buttonShape",
                    "styleType":"paragraph",
                    "visible":true,
                    "style":{
                      "fontName":"'Helvetica Neue'",
                      "fontSize":"18px",
                      "horizontalAlignment":"right",
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF666666,
                        "opacity":1},
                      "location":{
                        "x":54,
                        "y":18},
                      "size":{
                        "width":92,
                        "height":22}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"87c0a50ec8474ff2a48c7489776d6e3c",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"fe49e2a706744e048a3667060b9a3e69",
                        "panelIndex":1,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontName":"'Helvetica Neue'",
                          "fontSize":"18px",
                          "horizontalAlignment":"right",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFF666666,
                            "opacity":1},
                          "location":{
                            "x":54,
                            "y":18},
                          "size":{
                            "width":92,
                            "height":22}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"1e467f8e63d14e87b4967a32746222e9",
                    "label":"",
                    "parentDynamicPanel":"fe49e2a706744e048a3667060b9a3e69",
                    "panelIndex":1,
                    "type":"buttonShape",
                    "styleType":"paragraph",
                    "visible":true,
                    "style":{
                      "fontName":"'Helvetica Neue'",
                      "fontSize":"12px",
                      "horizontalAlignment":"right",
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF666666,
                        "opacity":1},
                      "location":{
                        "x":79,
                        "y":0},
                      "size":{
                        "width":66,
                        "height":14}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"b19b8a20efe044748b51ac5b68a88f23",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"fe49e2a706744e048a3667060b9a3e69",
                        "panelIndex":1,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontName":"'Helvetica Neue'",
                          "fontSize":"12px",
                          "horizontalAlignment":"right",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFF666666,
                            "opacity":1},
                          "location":{
                            "x":79,
                            "y":0},
                          "size":{
                            "width":66,
                            "height":14}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"b8608e9f638b4660a8a6dee7aa9c3e36",
                    "label":"",
                    "parentDynamicPanel":"fe49e2a706744e048a3667060b9a3e69",
                    "panelIndex":1,
                    "type":"imageBox",
                    "styleType":"imageBox",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":162,
                        "y":4},
                      "size":{
                        "width":28,
                        "height":28}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"a559e57a14854d24a4609485d50f1ed3",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"fe49e2a706744e048a3667060b9a3e69",
                        "panelIndex":1,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":162,
                            "y":4},
                          "size":{
                            "width":28,
                            "height":28}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/dashboard/u18.png"}},
{
                    "id":"fda57ffd0f054a0d897d3b093d669bdd",
                    "label":"",
                    "parentDynamicPanel":"fe49e2a706744e048a3667060b9a3e69",
                    "panelIndex":1,
                    "type":"buttonShape",
                    "styleType":"paragraph",
                    "visible":true,
                    "style":{
                      "fontSize":"14px",
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF000000,
                        "opacity":1},
                      "location":{
                        "x":20,
                        "y":99},
                      "size":{
                        "width":170,
                        "height":16},
                      "rotation":"0",
                      "textRotation":"0"},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"5cc804455eb0464b85ff7cc456067800",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"fe49e2a706744e048a3667060b9a3e69",
                        "panelIndex":1,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontSize":"14px",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFF000000,
                            "opacity":1},
                          "location":{
                            "x":20,
                            "y":99},
                          "size":{
                            "width":170,
                            "height":16},
                          "rotation":"0",
                          "textRotation":"0"},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"Open Link in Current Window",
                                "target":{
                                  "targetType":"page",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"a6aab5213b4b4c3e85ac4afe1f257e91",
                    "label":"",
                    "parentDynamicPanel":"fe49e2a706744e048a3667060b9a3e69",
                    "panelIndex":1,
                    "type":"imageMapRegion",
                    "styleType":"imageMapRegion",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":155,
                        "y":0},
                      "size":{
                        "width":40,
                        "height":40}},
                    "adaptiveStyles":{
},
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"setPanelState",
                                "description":"Set dropdown-user to State1",
                                "panelsToStates":[{
                                    "panelPath":["fe49e2a706744e048a3667060b9a3e69"],
                                    "stateInfo":{
                                      "setStateType":"diagram",
                                      "stateNumber":1,
                                      "stateValue":{
                                        "exprType":"stringLiteral",
                                        "value":"1",
                                        "stos":[]},
                                      "loop":false,
                                      "showWhenSet":false,
                                      "options":{
                                        "compress":false}}}]}]}]}},
                    "tabbable":true}],
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFFFFF},
                  "image":null,
                  "imageHorizontalAlignment":"near",
                  "imageVerticalAlignment":"near",
                  "imageRepeat":"auto"},
                "adaptiveStyles":{
}}]},
{
            "id":"da364140f50c47a5a49a390f2c5fa9ae",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "stateStyles":{
                "mouseOver":{
                  "opacity":"0.6"}},
              "location":{
                "x":276,
                "y":26},
              "size":{
                "width":28,
                "height":28}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"93ee0f68a2b948238ef2e6ff71880680",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "stateStyles":{
                    "mouseOver":{
                      "opacity":"0.6"}},
                  "location":{
                    "x":276,
                    "y":26},
                  "size":{
                    "width":28,
                    "height":28}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/dashboard/u37.png",
              "mouseOver~":"images/dashboard/u37.png"}},
{
            "id":"5280f6ab2ff541e3a08d602a96f14af5",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":8,
                "y":22},
              "size":{
                "width":252,
                "height":37}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"62a6cea60ded4fa9a507f5f197608b58",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":8,
                    "y":22},
                  "size":{
                    "width":252,
                    "height":37}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/dashboard/u39.png"}},
{
            "id":"fe5658b4dd484718b4046ef0c1c59a08",
            "label":"",
            "type":"imageMapRegion",
            "styleType":"imageMapRegion",
            "visible":true,
            "style":{
              "size":{
                "width":294,
                "height":81}},
            "adaptiveStyles":{
},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Link in Current Window",
                        "target":{
                          "targetType":"page",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true},
{
            "id":"c68a3e19da77499fa30eb2ee99e26c9a",
            "label":"",
            "type":"imageMapRegion",
            "styleType":"imageMapRegion",
            "visible":true,
            "style":{
              "location":{
                "x":270,
                "y":21},
              "size":{
                "width":39,
                "height":39}},
            "adaptiveStyles":{
},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Link in Current Window",
                        "target":{
                          "targetType":"page",
                          "includeVariables":true},
                        "linkType":"current"},
{
                        "action":"linkWindow",
                        "description":"Open Link in Current Window",
                        "target":{
                          "targetType":"page",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true}]}}},
  "objectPaths":{
    "6fa83c7d691d42b0a5f191fc856b3fa2":{
      "scriptId":"u0"},
    "cf034a8f1c4d4be4b11d57199d5243bb":{
      "scriptId":"u1"},
    "324a7a7607614ef9b58cca993ccc4d44":{
      "scriptId":"u2",
      "98f6e95fccd74ca4a04a4a23229806bc":{
        "scriptId":"u3"},
      "4c99a36cd31f4770a5042ff302db729c":{
        "scriptId":"u4"}},
    "0a27b825e7f647ba83833091b55d29e2":{
      "scriptId":"u5",
      "a98ffd8705e040929b7ec88c6bbc264e":{
        "scriptId":"u6"},
      "8ab6195fdb274feb89b20710a3fc5997":{
        "scriptId":"u7"},
      "fa8b587736bf4c6ea418fcbeaa262c99":{
        "scriptId":"u8"},
      "38639eb7baa94a2c8bedf245688e39bd":{
        "scriptId":"u9"},
      "b1f5768804d347539bfd076bab6dbe28":{
        "scriptId":"u10"},
      "fe49e2a706744e048a3667060b9a3e69":{
        "scriptId":"u11"},
      "6204713e832042c18bfcced89f8bce20":{
        "scriptId":"u12"},
      "62986fe513794f9c8abec46cde2877a7":{
        "scriptId":"u13"},
      "c076f0909fb542b49a704785b1078434":{
        "scriptId":"u14"},
      "c925cae17de947179805ef69d39926c2":{
        "scriptId":"u15"},
      "11cf14182664433ebd8e6f1a0ee85ffe":{
        "scriptId":"u16"},
      "9a3f85fce4df4d77b97c4565d725eec5":{
        "scriptId":"u17"},
      "f6b7572cbf4c448c9f6afbaa10bfad13":{
        "scriptId":"u18"},
      "9ed6828666f447f7a7e0ceb44c3afe85":{
        "scriptId":"u19"},
      "bd713743a4fd4100b43ccca1b70ca994":{
        "scriptId":"u20"},
      "c45b355677264302bfe15da0b7663744":{
        "scriptId":"u21"},
      "3dee6155c57042de849e03626aa42332":{
        "scriptId":"u22"},
      "5b7ee831d3d94eb7bcd42535e0e07829":{
        "scriptId":"u23"},
      "78e83a886be14343987e121a22698ce9":{
        "scriptId":"u24"},
      "048b499446c24a21965e02b1a1c2cda1":{
        "scriptId":"u25"},
      "e07433f9f99a4fcca3478cabd32cb61e":{
        "scriptId":"u26"},
      "87c0a50ec8474ff2a48c7489776d6e3c":{
        "scriptId":"u27"},
      "1e467f8e63d14e87b4967a32746222e9":{
        "scriptId":"u28"},
      "b19b8a20efe044748b51ac5b68a88f23":{
        "scriptId":"u29"},
      "b8608e9f638b4660a8a6dee7aa9c3e36":{
        "scriptId":"u30"},
      "a559e57a14854d24a4609485d50f1ed3":{
        "scriptId":"u31"},
      "fda57ffd0f054a0d897d3b093d669bdd":{
        "scriptId":"u32"},
      "5cc804455eb0464b85ff7cc456067800":{
        "scriptId":"u33"},
      "a6aab5213b4b4c3e85ac4afe1f257e91":{
        "scriptId":"u34"},
      "da364140f50c47a5a49a390f2c5fa9ae":{
        "scriptId":"u35"},
      "93ee0f68a2b948238ef2e6ff71880680":{
        "scriptId":"u36"},
      "5280f6ab2ff541e3a08d602a96f14af5":{
        "scriptId":"u37"},
      "62a6cea60ded4fa9a507f5f197608b58":{
        "scriptId":"u38"},
      "fe5658b4dd484718b4046ef0c1c59a08":{
        "scriptId":"u39"},
      "c68a3e19da77499fa30eb2ee99e26c9a":{
        "scriptId":"u40"}},
    "a0cb5b4062a6404a96529286481624a5":{
      "scriptId":"u41"},
    "77798baf3ba1482187aa8a9cbf9313c7":{
      "scriptId":"u42"},
    "ec87a0f6424b4713af21dafb588a3986":{
      "scriptId":"u43"},
    "50e44a113fcb4635a6814d731583b9a1":{
      "scriptId":"u44"},
    "711e5fa157bb40329b0b134250ce1d0a":{
      "scriptId":"u45"},
    "957657e39ce944f9af48c30ec8bec257":{
      "scriptId":"u46"},
    "376b7e0898b94bdabc2b25653b542309":{
      "scriptId":"u47"},
    "e320bebf96c244538cfe6fbe9ccbd38d":{
      "scriptId":"u48"},
    "009b4b1c9ca14d5783d3630e8e364d83":{
      "scriptId":"u49"},
    "04fab6e82f894b2f92c4d143b665dd0e":{
      "scriptId":"u50"},
    "ff04f3589eea4697a7de28e622de8fcf":{
      "scriptId":"u51"},
    "d844ddafc94b435eb5ae9cff95cee65d":{
      "scriptId":"u52"},
    "e5e9c768248243aba1a015b96cef7001":{
      "scriptId":"u53"},
    "baf779d19194449f9a21e7c4bc8faa79":{
      "scriptId":"u54"},
    "5aa168642edb41e6a7932d2a84476fda":{
      "scriptId":"u55"},
    "0ae9b079664a4f7b862c5af9fe0c6fec":{
      "scriptId":"u56"},
    "3402fba56da34c4293b83fafd4ea7fcd":{
      "scriptId":"u57"},
    "7cc6464cee264399ab882991a7256e3d":{
      "scriptId":"u58"},
    "f43a3c57b81748fcbe558ec003d8dcd6":{
      "scriptId":"u59"},
    "9f91f945ab764b87b1627b9f853000d7":{
      "scriptId":"u60"},
    "5d8da2567d9f42b1a717ccb9788ac68c":{
      "scriptId":"u61"},
    "84b419c247994e2bb089bcda8c2f7086":{
      "scriptId":"u62"},
    "a6977c9246f94a2bb349b470eb96f7db":{
      "scriptId":"u63"},
    "caac91e0ecc44727af0b8c556ff04cc4":{
      "scriptId":"u64"},
    "b758a6b7a2b54f4a9f9e97ef61e05d5b":{
      "scriptId":"u65"},
    "f1a0d27b367d4bad83bf8905fe79987e":{
      "scriptId":"u66"},
    "bf41d5ee372b4e27be651f09591e0422":{
      "scriptId":"u67"},
    "3d15b67f390c47faae9f83096b7bba0c":{
      "scriptId":"u68"},
    "38664ea3da1a43e296bc7a2fb2a17692":{
      "scriptId":"u69"},
    "6f7816cf259b4e228a1e56ffc2130b34":{
      "scriptId":"u70"},
    "96af25aad88e47e6be3a1a691fa2d744":{
      "scriptId":"u71"},
    "df168e3bbb904edab5623e9bad24e1f3":{
      "scriptId":"u72"},
    "5b126a279d6b4efb93220f2cd3b667ef":{
      "scriptId":"u73"},
    "575ae392bfc44df3a98ad324ffde2de0":{
      "scriptId":"u74"},
    "841163d3419947bbab6714a77c04c0b7":{
      "scriptId":"u75"},
    "7c61db06d2bb496a80eda1f4e2397e30":{
      "scriptId":"u76"},
    "d979b9e3b6184fe7a0ad80cb2940eba6":{
      "scriptId":"u77"},
    "f2399530b93b4d23864fc67669f38ff5":{
      "scriptId":"u78"},
    "e3ae34c0959c40ec8f052224f2764e77":{
      "scriptId":"u79"},
    "d30cc0a3136147d7923d1764fa385502":{
      "scriptId":"u80"},
    "c2804a3fd7244544a7af4cb570fdd733":{
      "scriptId":"u81"},
    "66c852865ca74550a79b46c338976247":{
      "scriptId":"u82"}}});