$axure.loadCurrentPage({
  "url":"tratamento_de_erro__acesso_nao_permitido.html",
  "generationDate":new Date(1423764002103.74),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"61bf853da72742cfb0013f936e1e8042",
    "type":"Axure:Page",
    "name":"Tratamento de erro: acesso não permitido",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"37a72237377a47d8b4de6e0ff3d6f01d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "size":{
              "width":980,
              "height":850},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"29b2d39555ab4fc0b4a661c5e2cf5724",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "size":{
                  "width":980,
                  "height":850},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/cadastro/u0.png"}},
{
          "id":"1ab65f090d224d7396635c34afd8b16c",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":810},
            "size":{
              "width":1277,
              "height":33}},
          "adaptiveStyles":{
},
          "masterId":"4226023da38e45578b3ec7ef42593243"},
{
          "id":"96f19c57b48d480fbb00b8b72d63dc90",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "horizontalAlignment":"center",
            "location":{
              "x":300,
              "y":127},
            "size":{
              "width":363,
              "height":38}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"28f6127dbea94cc2b25dec928d8d17b0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "horizontalAlignment":"center",
                "location":{
                  "x":300,
                  "y":127},
                "size":{
                  "width":363,
                  "height":38}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6c91470452f44566b94e5a1f34578b33",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":272,
              "y":220},
            "size":{
              "width":440,
              "height":410},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"4",
            "outerShadow":{
              "on":true,
              "offsetX":0,
              "offsetY":4,
              "blurRadius":3,
              "color":{
                "r":134,
                "g":134,
                "b":134,
                "a":0.219607843137255}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0ab8a1d80426472099d03dfb25a76988",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":272,
                  "y":220},
                "size":{
                  "width":440,
                  "height":410},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"4",
                "outerShadow":{
                  "on":true,
                  "offsetX":0,
                  "offsetY":4,
                  "blurRadius":3,
                  "color":{
                    "r":134,
                    "g":134,
                    "b":134,
                    "a":0.219607843137255}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/cadastro/u7.png"}},
{
          "id":"b1fabc1087e4401190b496be1293bc7d",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":302,
              "y":285},
            "size":{
              "width":380,
              "height":45}},
          "adaptiveStyles":{
}},
{
          "id":"90e0b64f8b9f44baa1211ec389104895",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":302,
              "y":345},
            "size":{
              "width":380,
              "height":45}},
          "adaptiveStyles":{
}},
{
          "id":"503e62191fb949b79561e825445713cb",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":302,
              "y":404},
            "size":{
              "width":380,
              "height":45}},
          "adaptiveStyles":{
}},
{
          "id":"7de3911e07e14106b20cca7848190cc8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negrito', 'Arial'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF0099FF},
            "location":{
              "x":302,
              "y":560},
            "size":{
              "width":380,
              "height":41},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e7bedebe831f429e9df5e08869b6b8a9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negrito', 'Arial'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0099FF},
                "location":{
                  "x":302,
                  "y":560},
                "size":{
                  "width":380,
                  "height":41},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"2"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Link in Current Window",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/cadastro/u12.png"}},
{
          "id":"5e93867f113846db8c52fdfdf9afc9da",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":302,
              "y":459},
            "size":{
              "width":350,
              "height":14},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a655fdcd246647d5ad0a07b30102de26",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":302,
                  "y":459},
                "size":{
                  "width":350,
                  "height":14},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6666057c458049f6b8c3861a5ccf5029",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":302,
              "y":490},
            "size":{
              "width":380,
              "height":45}},
          "adaptiveStyles":{
}},
{
          "id":"8bcf7d71a0854a39b0ab68a36707d96e",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":302,
              "y":247},
            "size":{
              "width":253,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"504c2139963940bda2cd4c338ef0d383",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":302,
                  "y":247},
                "size":{
                  "width":253,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"68dc55f949e24d86a13f9a3d013a25a3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negrito', 'Arial'",
            "fontWeight":"700",
            "fill":{
              "fillType":"solid",
              "color":0xE0FFFFCC},
            "location":{
              "x":77,
              "y":-10},
            "size":{
              "width":790,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c41a04a280c74409b3ab407b52841eec",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negrito', 'Arial'",
                "fontWeight":"700",
                "fill":{
                  "fillType":"solid",
                  "color":0xE0FFFFCC},
                "location":{
                  "x":77,
                  "y":-10},
                "size":{
                  "width":790,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/tratamento_de_erro__cadastro_existente/u19.png"}},
{
          "id":"b35ee2a46b214c869f3580bfe4b84796",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":690,
              "y":0},
            "size":{
              "width":30,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"963b54d240984819a863dafbdc9747e9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":690,
                  "y":0},
                "size":{
                  "width":30,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/tratamento_de_erro__cadastro_existente/u21.png"}},
{
          "id":"d997e5fdeb904046a697f7bb3f6e79b4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":358,
              "y":60},
            "size":{
              "width":252,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e9554373b7a248a0aa15499ab91ea9d1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":358,
                  "y":60},
                "size":{
                  "width":252,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/cadastro/u19.png"}}]}},
  "masters":{
    "4226023da38e45578b3ec7ef42593243":{
      "packageId":"4226023da38e45578b3ec7ef42593243",
      "type":"Axure:Master",
      "name":"footer",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"98f6e95fccd74ca4a04a4a23229806bc",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"12px",
              "verticalAlignment":"middle",
              "fill":{
                "fillType":"solid",
                "color":0xFFF2F2F2},
              "location":{
                "x":240,
                "y":0},
              "size":{
                "width":780,
                "height":40}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"4c99a36cd31f4770a5042ff302db729c",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"12px",
                  "verticalAlignment":"middle",
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2},
                  "location":{
                    "x":240,
                    "y":0},
                  "size":{
                    "width":780,
                    "height":40}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/cadastro/u3.png"}}]}}},
  "objectPaths":{
    "37a72237377a47d8b4de6e0ff3d6f01d":{
      "scriptId":"u0"},
    "29b2d39555ab4fc0b4a661c5e2cf5724":{
      "scriptId":"u1"},
    "1ab65f090d224d7396635c34afd8b16c":{
      "scriptId":"u2",
      "98f6e95fccd74ca4a04a4a23229806bc":{
        "scriptId":"u3"},
      "4c99a36cd31f4770a5042ff302db729c":{
        "scriptId":"u4"}},
    "96f19c57b48d480fbb00b8b72d63dc90":{
      "scriptId":"u5"},
    "28f6127dbea94cc2b25dec928d8d17b0":{
      "scriptId":"u6"},
    "6c91470452f44566b94e5a1f34578b33":{
      "scriptId":"u7"},
    "0ab8a1d80426472099d03dfb25a76988":{
      "scriptId":"u8"},
    "b1fabc1087e4401190b496be1293bc7d":{
      "scriptId":"u9"},
    "90e0b64f8b9f44baa1211ec389104895":{
      "scriptId":"u10"},
    "503e62191fb949b79561e825445713cb":{
      "scriptId":"u11"},
    "7de3911e07e14106b20cca7848190cc8":{
      "scriptId":"u12"},
    "e7bedebe831f429e9df5e08869b6b8a9":{
      "scriptId":"u13"},
    "5e93867f113846db8c52fdfdf9afc9da":{
      "scriptId":"u14"},
    "a655fdcd246647d5ad0a07b30102de26":{
      "scriptId":"u15"},
    "6666057c458049f6b8c3861a5ccf5029":{
      "scriptId":"u16"},
    "8bcf7d71a0854a39b0ab68a36707d96e":{
      "scriptId":"u17"},
    "504c2139963940bda2cd4c338ef0d383":{
      "scriptId":"u18"},
    "68dc55f949e24d86a13f9a3d013a25a3":{
      "scriptId":"u19"},
    "c41a04a280c74409b3ab407b52841eec":{
      "scriptId":"u20"},
    "b35ee2a46b214c869f3580bfe4b84796":{
      "scriptId":"u21"},
    "963b54d240984819a863dafbdc9747e9":{
      "scriptId":"u22"},
    "d997e5fdeb904046a697f7bb3f6e79b4":{
      "scriptId":"u23"},
    "e9554373b7a248a0aa15499ab91ea9d1":{
      "scriptId":"u24"}}});