$axure.loadCurrentPage({
  "url":"imagem_ampliada.html",
  "generationDate":new Date(1423764019983.27),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"3294e37c02904ac49160cf8098d6966e",
    "type":"Axure:Page",
    "name":"Imagem ampliada",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"70e81e3fcdd842a8b381fd1972069b78",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "size":{
              "width":980,
              "height":910},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"749dc0e222a04cd6a2509cb400222802",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "size":{
                  "width":980,
                  "height":910},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/detalhe_fotos/u0.png"}},
{
          "id":"3150aeb3fd72457694ee4f7b79fe057a",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":870},
            "size":{
              "width":780,
              "height":40}},
          "adaptiveStyles":{
},
          "masterId":"4226023da38e45578b3ec7ef42593243"},
{
          "id":"567ccecc4f194bb08f31f2e8803c1899",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"fbc37d401c784c2abad213112443341e"},
{
          "id":"e87ba86019d849a1aedf38677adca064",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFD7D7D7},
            "location":{
              "x":34,
              "y":190},
            "size":{
              "width":916,
              "height":65},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"75db1e5f2dcf406990d5e4f03c603f0d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7},
                "location":{
                  "x":34,
                  "y":190},
                "size":{
                  "width":916,
                  "height":65},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/detalhe_fotos/u36.png"}},
{
          "id":"d7adcfea4bd94731abb11ffa4c71e6ec",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":34,
              "y":138},
            "size":{
              "width":446,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a4f68523d27d422483f910ce1b3ee742",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":34,
                  "y":138},
                "size":{
                  "width":446,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0ad536178bcf49f3a2898e77a47f417d",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"12px",
            "fontWeight":"400",
            "underline":true,
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099FF,
              "opacity":1},
            "location":{
              "x":34,
              "y":112},
            "size":{
              "width":196,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b64f3f37fee14343a96b0a388b89d801",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"12px",
                "fontWeight":"400",
                "underline":true,
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":34,
                  "y":112},
                "size":{
                  "width":196,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Fotos de eventos in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"fotos_de_eventos.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e1c97dd975f24867bf3bcce84ff73bc8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "horizontalAlignment":"left",
            "lineSpacing":"25px",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":60,
              "y":195},
            "size":{
              "width":460,
              "height":55},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e904048a3a9d488b9c395492745b8b40",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "horizontalAlignment":"left",
                "lineSpacing":"25px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":60,
                  "y":195},
                "size":{
                  "width":460,
                  "height":55},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2e08fa3d6d084f0caa907deaa03a378d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":35,
              "y":423},
            "size":{
              "width":914,
              "height":46},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e96486526b634726959bdb2ec046ee76",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":35,
                  "y":423},
                "size":{
                  "width":914,
                  "height":46},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/detalhe_do_feedback_da_agencia/u46.png"}},
{
          "id":"1572d4255c9740f0a9c41b971408eacb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":35,
              "y":519},
            "size":{
              "width":914,
              "height":46},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"afe19b95d8d74c909f4a708cfa6ff944",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":35,
                  "y":519},
                "size":{
                  "width":914,
                  "height":46},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/detalhe_do_feedback_da_agencia/u46.png"}},
{
          "id":"4edcb65a69df47c49630e6b971f4ccba",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":35,
              "y":310},
            "size":{
              "width":914,
              "height":400}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5cec5f842fdd45d590300bb38b1aac21",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "size":{
                  "width":914,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0d00a65fefe545c1aef670ff1d2141f5",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0099FF,
                      "opacity":1},
                    "size":{
                      "width":914,
                      "height":40},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/detalhe_fotos/u49.png"}},
{
              "id":"27450b4f35b4477c8d55a53edc928b97",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":0,
                  "y":40},
                "size":{
                  "width":914,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"bf882d6662c04d54905b2141c717711b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0099FF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "location":{
                      "x":0,
                      "y":40},
                    "size":{
                      "width":914,
                      "height":40},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/detalhe_fotos/u51.png"}},
{
              "id":"02cbeda95de94c418d2c48d34bd363cf",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":0,
                  "y":80},
                "size":{
                  "width":914,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9467a4400f9b463b8db0e78d1988a87a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0099FF,
                      "opacity":1},
                    "location":{
                      "x":0,
                      "y":80},
                    "size":{
                      "width":914,
                      "height":40},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/detalhe_fotos/u49.png"}},
{
              "id":"181fa91dd4314766b2182e7f81b5d67d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":0,
                  "y":120},
                "size":{
                  "width":914,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"bc8cf8066ecd49408c408bfb1c140331",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0099FF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "location":{
                      "x":0,
                      "y":120},
                    "size":{
                      "width":914,
                      "height":40},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/detalhe_fotos/u51.png"}},
{
              "id":"695184117b1946828ab7372c6e505f27",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":0,
                  "y":160},
                "size":{
                  "width":914,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"3d60ec406c5c4ca0998f3b8a77f75d69",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0099FF,
                      "opacity":1},
                    "location":{
                      "x":0,
                      "y":160},
                    "size":{
                      "width":914,
                      "height":40},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/detalhe_fotos/u49.png"}},
{
              "id":"a01d125de5bc4270b7aedb9c2922223a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":0,
                  "y":200},
                "size":{
                  "width":914,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"7afbea2a50a148c1983eee29462f59cf",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0099FF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "location":{
                      "x":0,
                      "y":200},
                    "size":{
                      "width":914,
                      "height":40},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/detalhe_fotos/u51.png"}},
{
              "id":"cad81a9a0d274ccdb938b29eb5f064cb",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":0,
                  "y":240},
                "size":{
                  "width":914,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"2f52dc2fb0b2400aaec887f148f1b0b2",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0099FF,
                      "opacity":1},
                    "location":{
                      "x":0,
                      "y":240},
                    "size":{
                      "width":914,
                      "height":40},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/detalhe_fotos/u49.png"}},
{
              "id":"319735cc4dda43d6b4d174b1a533058d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":0,
                  "y":280},
                "size":{
                  "width":914,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"50d211c8471f40db8407393872ea7af5",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0099FF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "location":{
                      "x":0,
                      "y":280},
                    "size":{
                      "width":914,
                      "height":40},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/detalhe_fotos/u51.png"}},
{
              "id":"fabe2dff90184e219e1e633fe1088919",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":0,
                  "y":320},
                "size":{
                  "width":914,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"22d36d52a20a417ca77e56e02299ea19",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0099FF,
                      "opacity":1},
                    "location":{
                      "x":0,
                      "y":320},
                    "size":{
                      "width":914,
                      "height":40},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/detalhe_fotos/u49.png"}},
{
              "id":"88b7b77248964098beb366b5875adbb3",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":0,
                  "y":360},
                "size":{
                  "width":914,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"2172282ba73f402faf139d0dbbacd971",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0099FF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "location":{
                      "x":0,
                      "y":360},
                    "size":{
                      "width":914,
                      "height":40},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/detalhe_fotos/u67.png"}}]},
{
          "id":"49cb45580b5148a3b7c58be663521486",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":34,
              "y":310},
            "size":{
              "width":146,
              "height":400}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Link in Current Window",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"628ea10680dd4281bdaf473ca0e94a2b",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Itálico', 'Arial'",
            "fontSize":"13px",
            "fontWeight":"400",
            "fontStyle":"italic",
            "location":{
              "x":37,
              "y":276},
            "size":{
              "width":208,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9ff6094cf8ea406486853be51283c038",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Itálico', 'Arial'",
                "fontSize":"13px",
                "fontWeight":"400",
                "fontStyle":"italic",
                "location":{
                  "x":37,
                  "y":276},
                "size":{
                  "width":208,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"11f01b5e6ef04e95aa2f05822d908891",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":35,
              "y":740},
            "size":{
              "width":190,
              "height":31}},
          "adaptiveStyles":{
},
          "masterId":"5b189047120d4e709c202136ab932927"},
{
          "id":"05a222a2eae845a9b073deb644e22636",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"12px",
            "fontWeight":"400",
            "underline":true,
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099FF,
              "opacity":1},
            "location":{
              "x":34,
              "y":824},
            "size":{
              "width":236,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e6307cb804b249baae052d0040e8d752",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"12px",
                "fontWeight":"400",
                "underline":true,
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":34,
                  "y":824},
                "size":{
                  "width":236,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Fotos de eventos in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"fotos_de_eventos.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ba99e5e7fc624df28fe17554fb9cc024",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":34,
              "y":794},
            "size":{
              "width":876,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/alterar_senha/u42_line.png"}},
{
          "id":"423f655583ea4aff827cde15268891e1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negrito', 'Arial'",
            "fontSize":"11px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF0099FF},
            "location":{
              "x":765,
              "y":270},
            "size":{
              "width":180,
              "height":31},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"df170d7638e04ff98733bd5625905a75",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negrito', 'Arial'",
                "fontSize":"11px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0099FF},
                "location":{
                  "x":765,
                  "y":270},
                "size":{
                  "width":180,
                  "height":31},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"2"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/detalhe_fotos/u78.png"}},
{
          "id":"619717dbc4fa442c99b6db920a2278da",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negrito', 'Arial'",
            "fontSize":"11px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF0099FF},
            "location":{
              "x":765,
              "y":729},
            "size":{
              "width":180,
              "height":31},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4c126d88ba6546a19fa09e13bc9616f8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negrito', 'Arial'",
                "fontSize":"11px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0099FF},
                "location":{
                  "x":765,
                  "y":729},
                "size":{
                  "width":180,
                  "height":31},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"2"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/detalhe_fotos/u78.png"}},
{
          "id":"886571b667024e9d9bb67e84d7ff37d2",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":900,
              "y":314},
            "size":{
              "width":32,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ec7afb9ee4db4a3e81314834afc019c7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":900,
                  "y":314},
                "size":{
                  "width":32,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/detalhe_fotos/u82.png"}},
{
          "id":"88e0e50bb3ef44d9ac41818e8eb57f63",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":900,
              "y":355},
            "size":{
              "width":32,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"955dbe179b7744cba692a3c7adf0f5fd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":900,
                  "y":355},
                "size":{
                  "width":32,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/detalhe_fotos/u82.png"}},
{
          "id":"8488c8ab2cb94740842cae1949f870fe",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":900,
              "y":396},
            "size":{
              "width":32,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3bda59cf79dd41a490c19c04d864ce2a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":900,
                  "y":396},
                "size":{
                  "width":32,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/detalhe_fotos/u82.png"}},
{
          "id":"9c94d58a489d4d93b5675ee3db29f69c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":900,
              "y":436},
            "size":{
              "width":32,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"44fb3c4f79234cf48f8a68702ebcd4b2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":900,
                  "y":436},
                "size":{
                  "width":32,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/detalhe_fotos/u82.png"}},
{
          "id":"435c90b3d83b4d05abb5c961595494c2",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":900,
              "y":474},
            "size":{
              "width":32,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1315917b4c1146f1994dd7ac33b77bd3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":900,
                  "y":474},
                "size":{
                  "width":32,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/detalhe_fotos/u82.png"}},
{
          "id":"ac4924a2173c49dbba83a5afe5b550a5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":900,
              "y":515},
            "size":{
              "width":32,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7340ce48449041ca96e54f168f90d391",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":900,
                  "y":515},
                "size":{
                  "width":32,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/detalhe_fotos/u82.png"}},
{
          "id":"8b2106d0fc62475fa7d9f694605300b2",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":900,
              "y":555},
            "size":{
              "width":32,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3da3daab2ed646e1b7a5912fca8e329f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":900,
                  "y":555},
                "size":{
                  "width":32,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/detalhe_fotos/u82.png"}},
{
          "id":"a19367e426d74a62aaa6009b46cc6f88",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":900,
              "y":595},
            "size":{
              "width":32,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f79c810d0c8f4ff0bfe89557d1206966",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":900,
                  "y":595},
                "size":{
                  "width":32,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/detalhe_fotos/u82.png"}},
{
          "id":"898f9a89372c4b7aaaf3e6685d099e1c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":900,
              "y":635},
            "size":{
              "width":32,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c1dd15f3bbc949bda2d66efe7d7f8188",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":900,
                  "y":635},
                "size":{
                  "width":32,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/detalhe_fotos/u82.png"}},
{
          "id":"3e6319d339904c43a2db4bfa3c3afb27",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":900,
              "y":675},
            "size":{
              "width":32,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"61f4f1e2251d4d47a4bcc85d5fb1680e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":900,
                  "y":675},
                "size":{
                  "width":32,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/detalhe_fotos/u82.png"}},
{
          "id":"453fdc9003f94ff9ace89ad75f51c185",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"10px",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF00},
            "location":{
              "x":952,
              "y":321},
            "size":{
              "width":18,
              "height":18},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0015b28368c14c3a8ab1d60a51ccf429",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"10px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF00},
                "location":{
                  "x":952,
                  "y":321},
                "size":{
                  "width":18,
                  "height":18},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/recuperar_senha/u11.png"}},
{
          "id":"511c94525cd24c40b029032af77edb03",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0x7C000000},
            "location":{
              "x":-8,
              "y":-10},
            "size":{
              "width":998,
              "height":920}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c5c8a6a2068943d385e277fac98940cb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0x7C000000},
                "location":{
                  "x":-8,
                  "y":-10},
                "size":{
                  "width":998,
                  "height":920}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/imagem_ampliada/u104.png"}},
{
          "id":"a6a9256d42b243b3854476abdb86803e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":148,
              "y":212},
            "size":{
              "width":710,
              "height":506},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f581eb917b86453da30f41e5e0a16b7a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":148,
                  "y":212},
                "size":{
                  "width":710,
                  "height":506},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/imagem_ampliada/u106.png"}},
{
          "id":"abece1ed93374f8486204bc3d5a92e49",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2,
              "opacity":1},
            "location":{
              "x":828,
              "y":170},
            "size":{
              "width":19,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d98297a9459643e8950bc461f046b4b5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2,
                  "opacity":1},
                "location":{
                  "x":828,
                  "y":170},
                "size":{
                  "width":19,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Back in Current Window",
                      "target":{
                        "targetType":"backUrl",
                        "includeVariables":false},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0fb148ba3a984bf489a1eb3897ae642b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":239,
              "y":274},
            "size":{
              "width":528,
              "height":324},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"15e14ca2e85640e99afc4ec13e748435",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":239,
                  "y":274},
                "size":{
                  "width":528,
                  "height":324},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/imagem_ampliada/u110.png"}},
{
          "id":"d40d1c52200b4d5998631a094d8fcfbc",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":438,
              "y":628},
            "size":{
              "width":32,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d1c4af1b7deb437da169adaab782d17d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":438,
                  "y":628},
                "size":{
                  "width":32,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/imagem_ampliada/u112.png"}},
{
          "id":"3f4e8e864fb448279d9c5009fa92fd0a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":522,
              "y":628},
            "size":{
              "width":32,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"edf050f6ea644b27a9e36d9e95954b2c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":522,
                  "y":628},
                "size":{
                  "width":32,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/imagem_ampliada/u114.png"}}]}},
  "masters":{
    "4226023da38e45578b3ec7ef42593243":{
      "packageId":"4226023da38e45578b3ec7ef42593243",
      "type":"Axure:Master",
      "name":"footer",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"98f6e95fccd74ca4a04a4a23229806bc",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"12px",
              "verticalAlignment":"middle",
              "fill":{
                "fillType":"solid",
                "color":0xFFF2F2F2},
              "location":{
                "x":240,
                "y":0},
              "size":{
                "width":780,
                "height":40}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"4c99a36cd31f4770a5042ff302db729c",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"12px",
                  "verticalAlignment":"middle",
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2},
                  "location":{
                    "x":240,
                    "y":0},
                  "size":{
                    "width":780,
                    "height":40}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/cadastro/u3.png"}}]}},
    "fbc37d401c784c2abad213112443341e":{
      "packageId":"fbc37d401c784c2abad213112443341e",
      "type":"Axure:Master",
      "name":"header_gerente",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"a98ffd8705e040929b7ec88c6bbc264e",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "size":{
                "width":980,
                "height":80},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8ab6195fdb274feb89b20710a3fc5997",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":980,
                    "height":80},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/alterar_senha/u6.png"}},
{
            "id":"fa8b587736bf4c6ea418fcbeaa262c99",
            "label":"",
            "type":"verticalLine",
            "styleType":"verticalLine",
            "visible":true,
            "style":{
              "location":{
                "x":284,
                "y":0},
              "size":{
                "width":10,
                "height":81},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFE4E4E4}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/alterar_senha/u8_line.png"}},
{
            "id":"fe49e2a706744e048a3667060b9a3e69",
            "label":"dropdown-user",
            "type":"dynamicPanel",
            "styleType":"dynamicPanel",
            "visible":true,
            "style":{
              "location":{
                "x":780,
                "y":22},
              "size":{
                "width":200,
                "height":138}},
            "adaptiveStyles":{
},
            "scrollbars":"none",
            "fitToContent":false,
            "propagate":false,
            "diagrams":[{
                "id":"9988237930104c0f96653f270533b92b",
                "label":"State1",
                "type":"Axure:PanelDiagram",
                "objects":[{
                    "id":"6204713e832042c18bfcced89f8bce20",
                    "label":"",
                    "parentDynamicPanel":"fe49e2a706744e048a3667060b9a3e69",
                    "panelIndex":0,
                    "type":"buttonShape",
                    "styleType":"paragraph",
                    "visible":true,
                    "style":{
                      "fontName":"'Helvetica Neue'",
                      "fontSize":"18px",
                      "horizontalAlignment":"right",
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF666666,
                        "opacity":1},
                      "location":{
                        "x":54,
                        "y":18},
                      "size":{
                        "width":92,
                        "height":22}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"62986fe513794f9c8abec46cde2877a7",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"fe49e2a706744e048a3667060b9a3e69",
                        "panelIndex":0,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontName":"'Helvetica Neue'",
                          "fontSize":"18px",
                          "horizontalAlignment":"right",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFF666666,
                            "opacity":1},
                          "location":{
                            "x":54,
                            "y":18},
                          "size":{
                            "width":92,
                            "height":22}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"c076f0909fb542b49a704785b1078434",
                    "label":"",
                    "parentDynamicPanel":"fe49e2a706744e048a3667060b9a3e69",
                    "panelIndex":0,
                    "type":"buttonShape",
                    "styleType":"paragraph",
                    "visible":true,
                    "style":{
                      "fontName":"'Helvetica Neue'",
                      "fontSize":"12px",
                      "horizontalAlignment":"right",
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF666666,
                        "opacity":1},
                      "location":{
                        "x":79,
                        "y":0},
                      "size":{
                        "width":66,
                        "height":14}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"c925cae17de947179805ef69d39926c2",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"fe49e2a706744e048a3667060b9a3e69",
                        "panelIndex":0,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontName":"'Helvetica Neue'",
                          "fontSize":"12px",
                          "horizontalAlignment":"right",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFF666666,
                            "opacity":1},
                          "location":{
                            "x":79,
                            "y":0},
                          "size":{
                            "width":66,
                            "height":14}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"11cf14182664433ebd8e6f1a0ee85ffe",
                    "label":"",
                    "parentDynamicPanel":"fe49e2a706744e048a3667060b9a3e69",
                    "panelIndex":0,
                    "type":"imageBox",
                    "styleType":"imageBox",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":162,
                        "y":4},
                      "size":{
                        "width":28,
                        "height":28}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"9a3f85fce4df4d77b97c4565d725eec5",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"fe49e2a706744e048a3667060b9a3e69",
                        "panelIndex":0,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":162,
                            "y":4},
                          "size":{
                            "width":28,
                            "height":28}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/alterar_senha/u14.png"}},
{
                    "id":"f6b7572cbf4c448c9f6afbaa10bfad13",
                    "label":"",
                    "parentDynamicPanel":"fe49e2a706744e048a3667060b9a3e69",
                    "panelIndex":0,
                    "type":"imageMapRegion",
                    "styleType":"imageMapRegion",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":155,
                        "y":0},
                      "size":{
                        "width":40,
                        "height":40}},
                    "adaptiveStyles":{
},
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"setPanelState",
                                "description":"Set dropdown-user to State2",
                                "panelsToStates":[{
                                    "panelPath":["fe49e2a706744e048a3667060b9a3e69"],
                                    "stateInfo":{
                                      "setStateType":"diagram",
                                      "stateNumber":2,
                                      "stateValue":{
                                        "exprType":"stringLiteral",
                                        "value":"1",
                                        "stos":[]},
                                      "loop":false,
                                      "showWhenSet":false,
                                      "options":{
                                        "compress":false}}}]}]}]}},
                    "tabbable":true}],
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFFFFF},
                  "image":null,
                  "imageHorizontalAlignment":"near",
                  "imageVerticalAlignment":"near",
                  "imageRepeat":"auto"},
                "adaptiveStyles":{
}},
{
                "id":"5ab577ad4f0d4fea8d6efa85d310a7cd",
                "label":"State2",
                "type":"Axure:PanelDiagram",
                "objects":[{
                    "id":"9ed6828666f447f7a7e0ceb44c3afe85",
                    "label":"",
                    "parentDynamicPanel":"fe49e2a706744e048a3667060b9a3e69",
                    "panelIndex":1,
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFE4E4E4},
                      "location":{
                        "x":0,
                        "y":47},
                      "size":{
                        "width":200,
                        "height":83},
                      "borderFill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "cornerRadiusTopLeft":"5"},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"bd713743a4fd4100b43ccca1b70ca994",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"fe49e2a706744e048a3667060b9a3e69",
                        "panelIndex":1,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFE4E4E4},
                          "location":{
                            "x":0,
                            "y":47},
                          "size":{
                            "width":200,
                            "height":83},
                          "borderFill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "cornerRadiusTopLeft":"5"},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/alterar_senha/u17.png"}},
{
                    "id":"c45b355677264302bfe15da0b7663744",
                    "label":"",
                    "parentDynamicPanel":"fe49e2a706744e048a3667060b9a3e69",
                    "panelIndex":1,
                    "type":"buttonShape",
                    "styleType":"paragraph",
                    "visible":true,
                    "style":{
                      "fontSize":"14px",
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF0066FF,
                        "opacity":1},
                      "location":{
                        "x":20,
                        "y":58},
                      "size":{
                        "width":170,
                        "height":16},
                      "rotation":"0",
                      "textRotation":"0"},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"3dee6155c57042de849e03626aa42332",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"fe49e2a706744e048a3667060b9a3e69",
                        "panelIndex":1,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontSize":"14px",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFF0066FF,
                            "opacity":1},
                          "location":{
                            "x":20,
                            "y":58},
                          "size":{
                            "width":170,
                            "height":16},
                          "rotation":"0",
                          "textRotation":"0"},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"Open Alterar senha in Current Window",
                                "target":{
                                  "targetType":"page",
                                  "url":"alterar_senha.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"5b7ee831d3d94eb7bcd42535e0e07829",
                    "label":"",
                    "parentDynamicPanel":"fe49e2a706744e048a3667060b9a3e69",
                    "panelIndex":1,
                    "type":"horizontalLine",
                    "styleType":"horizontalLine",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":0,
                        "y":82},
                      "size":{
                        "width":200,
                        "height":10},
                      "borderFill":{
                        "fillType":"solid",
                        "color":0xFFCCCCCC}},
                    "adaptiveStyles":{
},
                    "images":{
                      "start~":"resources/images/transparent.gif",
                      "end~":"resources/images/transparent.gif",
                      "line~":"images/alterar_senha/u21_line.png"}},
{
                    "id":"78e83a886be14343987e121a22698ce9",
                    "label":"",
                    "parentDynamicPanel":"fe49e2a706744e048a3667060b9a3e69",
                    "panelIndex":1,
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFE4E4E4},
                      "location":{
                        "x":166,
                        "y":36},
                      "size":{
                        "width":20,
                        "height":15},
                      "borderFill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "cornerRadiusTopLeft":"5"},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"048b499446c24a21965e02b1a1c2cda1",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"fe49e2a706744e048a3667060b9a3e69",
                        "panelIndex":1,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFE4E4E4},
                          "location":{
                            "x":166,
                            "y":36},
                          "size":{
                            "width":20,
                            "height":15},
                          "borderFill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "cornerRadiusTopLeft":"5"},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/alterar_senha/u22.png"}},
{
                    "id":"e07433f9f99a4fcca3478cabd32cb61e",
                    "label":"",
                    "parentDynamicPanel":"fe49e2a706744e048a3667060b9a3e69",
                    "panelIndex":1,
                    "type":"buttonShape",
                    "styleType":"paragraph",
                    "visible":true,
                    "style":{
                      "fontName":"'Helvetica Neue'",
                      "fontSize":"18px",
                      "horizontalAlignment":"right",
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF666666,
                        "opacity":1},
                      "location":{
                        "x":54,
                        "y":18},
                      "size":{
                        "width":92,
                        "height":22}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"87c0a50ec8474ff2a48c7489776d6e3c",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"fe49e2a706744e048a3667060b9a3e69",
                        "panelIndex":1,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontName":"'Helvetica Neue'",
                          "fontSize":"18px",
                          "horizontalAlignment":"right",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFF666666,
                            "opacity":1},
                          "location":{
                            "x":54,
                            "y":18},
                          "size":{
                            "width":92,
                            "height":22}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"1e467f8e63d14e87b4967a32746222e9",
                    "label":"",
                    "parentDynamicPanel":"fe49e2a706744e048a3667060b9a3e69",
                    "panelIndex":1,
                    "type":"buttonShape",
                    "styleType":"paragraph",
                    "visible":true,
                    "style":{
                      "fontName":"'Helvetica Neue'",
                      "fontSize":"12px",
                      "horizontalAlignment":"right",
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF666666,
                        "opacity":1},
                      "location":{
                        "x":79,
                        "y":0},
                      "size":{
                        "width":66,
                        "height":14}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"b19b8a20efe044748b51ac5b68a88f23",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"fe49e2a706744e048a3667060b9a3e69",
                        "panelIndex":1,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontName":"'Helvetica Neue'",
                          "fontSize":"12px",
                          "horizontalAlignment":"right",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFF666666,
                            "opacity":1},
                          "location":{
                            "x":79,
                            "y":0},
                          "size":{
                            "width":66,
                            "height":14}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"b8608e9f638b4660a8a6dee7aa9c3e36",
                    "label":"",
                    "parentDynamicPanel":"fe49e2a706744e048a3667060b9a3e69",
                    "panelIndex":1,
                    "type":"imageBox",
                    "styleType":"imageBox",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":162,
                        "y":4},
                      "size":{
                        "width":28,
                        "height":28}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"a559e57a14854d24a4609485d50f1ed3",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"fe49e2a706744e048a3667060b9a3e69",
                        "panelIndex":1,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":162,
                            "y":4},
                          "size":{
                            "width":28,
                            "height":28}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/alterar_senha/u14.png"}},
{
                    "id":"fda57ffd0f054a0d897d3b093d669bdd",
                    "label":"",
                    "parentDynamicPanel":"fe49e2a706744e048a3667060b9a3e69",
                    "panelIndex":1,
                    "type":"buttonShape",
                    "styleType":"paragraph",
                    "visible":true,
                    "style":{
                      "fontSize":"14px",
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF0066FF,
                        "opacity":1},
                      "location":{
                        "x":20,
                        "y":99},
                      "size":{
                        "width":170,
                        "height":16},
                      "rotation":"0",
                      "textRotation":"0"},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"5cc804455eb0464b85ff7cc456067800",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"fe49e2a706744e048a3667060b9a3e69",
                        "panelIndex":1,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontSize":"14px",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFF0066FF,
                            "opacity":1},
                          "location":{
                            "x":20,
                            "y":99},
                          "size":{
                            "width":170,
                            "height":16},
                          "rotation":"0",
                          "textRotation":"0"},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"Open Cadastro in Current Window",
                                "target":{
                                  "targetType":"page",
                                  "url":"cadastro.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"a6aab5213b4b4c3e85ac4afe1f257e91",
                    "label":"",
                    "parentDynamicPanel":"fe49e2a706744e048a3667060b9a3e69",
                    "panelIndex":1,
                    "type":"imageMapRegion",
                    "styleType":"imageMapRegion",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":155,
                        "y":0},
                      "size":{
                        "width":40,
                        "height":40}},
                    "adaptiveStyles":{
},
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"setPanelState",
                                "description":"Set dropdown-user to State1",
                                "panelsToStates":[{
                                    "panelPath":["fe49e2a706744e048a3667060b9a3e69"],
                                    "stateInfo":{
                                      "setStateType":"diagram",
                                      "stateNumber":1,
                                      "stateValue":{
                                        "exprType":"stringLiteral",
                                        "value":"1",
                                        "stos":[]},
                                      "loop":false,
                                      "showWhenSet":false,
                                      "options":{
                                        "compress":false}}}]}]}]}},
                    "tabbable":true}],
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFFFFF},
                  "image":null,
                  "imageHorizontalAlignment":"near",
                  "imageVerticalAlignment":"near",
                  "imageRepeat":"auto"},
                "adaptiveStyles":{
}}]},
{
            "id":"5280f6ab2ff541e3a08d602a96f14af5",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":8,
                "y":22},
              "size":{
                "width":252,
                "height":37}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"62a6cea60ded4fa9a507f5f197608b58",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":8,
                    "y":22},
                  "size":{
                    "width":252,
                    "height":37}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/cadastro/u19.png"}},
{
            "id":"fe5658b4dd484718b4046ef0c1c59a08",
            "label":"",
            "type":"imageMapRegion",
            "styleType":"imageMapRegion",
            "visible":true,
            "style":{
              "size":{
                "width":294,
                "height":81}},
            "adaptiveStyles":{
},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Dashboard in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"dashboard.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true}]}},
    "5b189047120d4e709c202136ab932927":{
      "packageId":"5b189047120d4e709c202136ab932927",
      "type":"Axure:Master",
      "name":"Paginacao",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"31283c18ea584dae809cd3269f1ffddf",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "size":{
                "width":190,
                "height":31}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"da8b6f03e029420a934b12ba13469d33",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":190,
                    "height":31}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/senha_feedback1/u128.png"}}]}}},
  "objectPaths":{
    "70e81e3fcdd842a8b381fd1972069b78":{
      "scriptId":"u0"},
    "749dc0e222a04cd6a2509cb400222802":{
      "scriptId":"u1"},
    "3150aeb3fd72457694ee4f7b79fe057a":{
      "scriptId":"u2",
      "98f6e95fccd74ca4a04a4a23229806bc":{
        "scriptId":"u3"},
      "4c99a36cd31f4770a5042ff302db729c":{
        "scriptId":"u4"}},
    "567ccecc4f194bb08f31f2e8803c1899":{
      "scriptId":"u5",
      "a98ffd8705e040929b7ec88c6bbc264e":{
        "scriptId":"u6"},
      "8ab6195fdb274feb89b20710a3fc5997":{
        "scriptId":"u7"},
      "fa8b587736bf4c6ea418fcbeaa262c99":{
        "scriptId":"u8"},
      "fe49e2a706744e048a3667060b9a3e69":{
        "scriptId":"u9"},
      "6204713e832042c18bfcced89f8bce20":{
        "scriptId":"u10"},
      "62986fe513794f9c8abec46cde2877a7":{
        "scriptId":"u11"},
      "c076f0909fb542b49a704785b1078434":{
        "scriptId":"u12"},
      "c925cae17de947179805ef69d39926c2":{
        "scriptId":"u13"},
      "11cf14182664433ebd8e6f1a0ee85ffe":{
        "scriptId":"u14"},
      "9a3f85fce4df4d77b97c4565d725eec5":{
        "scriptId":"u15"},
      "f6b7572cbf4c448c9f6afbaa10bfad13":{
        "scriptId":"u16"},
      "9ed6828666f447f7a7e0ceb44c3afe85":{
        "scriptId":"u17"},
      "bd713743a4fd4100b43ccca1b70ca994":{
        "scriptId":"u18"},
      "c45b355677264302bfe15da0b7663744":{
        "scriptId":"u19"},
      "3dee6155c57042de849e03626aa42332":{
        "scriptId":"u20"},
      "5b7ee831d3d94eb7bcd42535e0e07829":{
        "scriptId":"u21"},
      "78e83a886be14343987e121a22698ce9":{
        "scriptId":"u22"},
      "048b499446c24a21965e02b1a1c2cda1":{
        "scriptId":"u23"},
      "e07433f9f99a4fcca3478cabd32cb61e":{
        "scriptId":"u24"},
      "87c0a50ec8474ff2a48c7489776d6e3c":{
        "scriptId":"u25"},
      "1e467f8e63d14e87b4967a32746222e9":{
        "scriptId":"u26"},
      "b19b8a20efe044748b51ac5b68a88f23":{
        "scriptId":"u27"},
      "b8608e9f638b4660a8a6dee7aa9c3e36":{
        "scriptId":"u28"},
      "a559e57a14854d24a4609485d50f1ed3":{
        "scriptId":"u29"},
      "fda57ffd0f054a0d897d3b093d669bdd":{
        "scriptId":"u30"},
      "5cc804455eb0464b85ff7cc456067800":{
        "scriptId":"u31"},
      "a6aab5213b4b4c3e85ac4afe1f257e91":{
        "scriptId":"u32"},
      "5280f6ab2ff541e3a08d602a96f14af5":{
        "scriptId":"u33"},
      "62a6cea60ded4fa9a507f5f197608b58":{
        "scriptId":"u34"},
      "fe5658b4dd484718b4046ef0c1c59a08":{
        "scriptId":"u35"}},
    "e87ba86019d849a1aedf38677adca064":{
      "scriptId":"u36"},
    "75db1e5f2dcf406990d5e4f03c603f0d":{
      "scriptId":"u37"},
    "d7adcfea4bd94731abb11ffa4c71e6ec":{
      "scriptId":"u38"},
    "a4f68523d27d422483f910ce1b3ee742":{
      "scriptId":"u39"},
    "0ad536178bcf49f3a2898e77a47f417d":{
      "scriptId":"u40"},
    "b64f3f37fee14343a96b0a388b89d801":{
      "scriptId":"u41"},
    "e1c97dd975f24867bf3bcce84ff73bc8":{
      "scriptId":"u42"},
    "e904048a3a9d488b9c395492745b8b40":{
      "scriptId":"u43"},
    "2e08fa3d6d084f0caa907deaa03a378d":{
      "scriptId":"u44"},
    "e96486526b634726959bdb2ec046ee76":{
      "scriptId":"u45"},
    "1572d4255c9740f0a9c41b971408eacb":{
      "scriptId":"u46"},
    "afe19b95d8d74c909f4a708cfa6ff944":{
      "scriptId":"u47"},
    "4edcb65a69df47c49630e6b971f4ccba":{
      "scriptId":"u48"},
    "5cec5f842fdd45d590300bb38b1aac21":{
      "scriptId":"u49"},
    "0d00a65fefe545c1aef670ff1d2141f5":{
      "scriptId":"u50"},
    "27450b4f35b4477c8d55a53edc928b97":{
      "scriptId":"u51"},
    "bf882d6662c04d54905b2141c717711b":{
      "scriptId":"u52"},
    "02cbeda95de94c418d2c48d34bd363cf":{
      "scriptId":"u53"},
    "9467a4400f9b463b8db0e78d1988a87a":{
      "scriptId":"u54"},
    "181fa91dd4314766b2182e7f81b5d67d":{
      "scriptId":"u55"},
    "bc8cf8066ecd49408c408bfb1c140331":{
      "scriptId":"u56"},
    "695184117b1946828ab7372c6e505f27":{
      "scriptId":"u57"},
    "3d60ec406c5c4ca0998f3b8a77f75d69":{
      "scriptId":"u58"},
    "a01d125de5bc4270b7aedb9c2922223a":{
      "scriptId":"u59"},
    "7afbea2a50a148c1983eee29462f59cf":{
      "scriptId":"u60"},
    "cad81a9a0d274ccdb938b29eb5f064cb":{
      "scriptId":"u61"},
    "2f52dc2fb0b2400aaec887f148f1b0b2":{
      "scriptId":"u62"},
    "319735cc4dda43d6b4d174b1a533058d":{
      "scriptId":"u63"},
    "50d211c8471f40db8407393872ea7af5":{
      "scriptId":"u64"},
    "fabe2dff90184e219e1e633fe1088919":{
      "scriptId":"u65"},
    "22d36d52a20a417ca77e56e02299ea19":{
      "scriptId":"u66"},
    "88b7b77248964098beb366b5875adbb3":{
      "scriptId":"u67"},
    "2172282ba73f402faf139d0dbbacd971":{
      "scriptId":"u68"},
    "49cb45580b5148a3b7c58be663521486":{
      "scriptId":"u69"},
    "628ea10680dd4281bdaf473ca0e94a2b":{
      "scriptId":"u70"},
    "9ff6094cf8ea406486853be51283c038":{
      "scriptId":"u71"},
    "11f01b5e6ef04e95aa2f05822d908891":{
      "scriptId":"u72",
      "31283c18ea584dae809cd3269f1ffddf":{
        "scriptId":"u73"},
      "da8b6f03e029420a934b12ba13469d33":{
        "scriptId":"u74"}},
    "05a222a2eae845a9b073deb644e22636":{
      "scriptId":"u75"},
    "e6307cb804b249baae052d0040e8d752":{
      "scriptId":"u76"},
    "ba99e5e7fc624df28fe17554fb9cc024":{
      "scriptId":"u77"},
    "423f655583ea4aff827cde15268891e1":{
      "scriptId":"u78"},
    "df170d7638e04ff98733bd5625905a75":{
      "scriptId":"u79"},
    "619717dbc4fa442c99b6db920a2278da":{
      "scriptId":"u80"},
    "4c126d88ba6546a19fa09e13bc9616f8":{
      "scriptId":"u81"},
    "886571b667024e9d9bb67e84d7ff37d2":{
      "scriptId":"u82"},
    "ec7afb9ee4db4a3e81314834afc019c7":{
      "scriptId":"u83"},
    "88e0e50bb3ef44d9ac41818e8eb57f63":{
      "scriptId":"u84"},
    "955dbe179b7744cba692a3c7adf0f5fd":{
      "scriptId":"u85"},
    "8488c8ab2cb94740842cae1949f870fe":{
      "scriptId":"u86"},
    "3bda59cf79dd41a490c19c04d864ce2a":{
      "scriptId":"u87"},
    "9c94d58a489d4d93b5675ee3db29f69c":{
      "scriptId":"u88"},
    "44fb3c4f79234cf48f8a68702ebcd4b2":{
      "scriptId":"u89"},
    "435c90b3d83b4d05abb5c961595494c2":{
      "scriptId":"u90"},
    "1315917b4c1146f1994dd7ac33b77bd3":{
      "scriptId":"u91"},
    "ac4924a2173c49dbba83a5afe5b550a5":{
      "scriptId":"u92"},
    "7340ce48449041ca96e54f168f90d391":{
      "scriptId":"u93"},
    "8b2106d0fc62475fa7d9f694605300b2":{
      "scriptId":"u94"},
    "3da3daab2ed646e1b7a5912fca8e329f":{
      "scriptId":"u95"},
    "a19367e426d74a62aaa6009b46cc6f88":{
      "scriptId":"u96"},
    "f79c810d0c8f4ff0bfe89557d1206966":{
      "scriptId":"u97"},
    "898f9a89372c4b7aaaf3e6685d099e1c":{
      "scriptId":"u98"},
    "c1dd15f3bbc949bda2d66efe7d7f8188":{
      "scriptId":"u99"},
    "3e6319d339904c43a2db4bfa3c3afb27":{
      "scriptId":"u100"},
    "61f4f1e2251d4d47a4bcc85d5fb1680e":{
      "scriptId":"u101"},
    "453fdc9003f94ff9ace89ad75f51c185":{
      "scriptId":"u102"},
    "0015b28368c14c3a8ab1d60a51ccf429":{
      "scriptId":"u103"},
    "511c94525cd24c40b029032af77edb03":{
      "scriptId":"u104"},
    "c5c8a6a2068943d385e277fac98940cb":{
      "scriptId":"u105"},
    "a6a9256d42b243b3854476abdb86803e":{
      "scriptId":"u106"},
    "f581eb917b86453da30f41e5e0a16b7a":{
      "scriptId":"u107"},
    "abece1ed93374f8486204bc3d5a92e49":{
      "scriptId":"u108"},
    "d98297a9459643e8950bc461f046b4b5":{
      "scriptId":"u109"},
    "0fb148ba3a984bf489a1eb3897ae642b":{
      "scriptId":"u110"},
    "15e14ca2e85640e99afc4ec13e748435":{
      "scriptId":"u111"},
    "d40d1c52200b4d5998631a094d8fcfbc":{
      "scriptId":"u112"},
    "d1c4af1b7deb437da169adaab782d17d":{
      "scriptId":"u113"},
    "3f4e8e864fb448279d9c5009fa92fd0a":{
      "scriptId":"u114"},
    "edf050f6ea644b27a9e36d9e95954b2c":{
      "scriptId":"u115"}}});