$axure.loadCurrentPage({
  "url":"cadastro.html",
  "generationDate":new Date(1423764001755.66),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"a9d715aade594c53bf247af300ab521a",
    "type":"Axure:Page",
    "name":"Cadastro",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"9949c8c98a0345a8a576dc06ed3b8f7c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "size":{
              "width":980,
              "height":850},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"93f0dd1839fb462db48be21b7c9a995a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "size":{
                  "width":980,
                  "height":850},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/cadastro/u0.png"}},
{
          "id":"686f50f2108646579486669a33caa77c",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":810},
            "size":{
              "width":1277,
              "height":33}},
          "adaptiveStyles":{
},
          "masterId":"4226023da38e45578b3ec7ef42593243"},
{
          "id":"5a30299e0a66494ea0b0d63681bd2d4b",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "horizontalAlignment":"center",
            "location":{
              "x":300,
              "y":127},
            "size":{
              "width":363,
              "height":38}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b9e99c6f9e3944df93ae299ff296ee90",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "horizontalAlignment":"center",
                "location":{
                  "x":300,
                  "y":127},
                "size":{
                  "width":363,
                  "height":38}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"52a5f6f2e4ed45dfa38b998df38bf8d1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":272,
              "y":220},
            "size":{
              "width":440,
              "height":410},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"4",
            "outerShadow":{
              "on":true,
              "offsetX":0,
              "offsetY":4,
              "blurRadius":3,
              "color":{
                "r":134,
                "g":134,
                "b":134,
                "a":0.219607843137255}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6bf5c6a4f9674fd7b000a23d06cb25cc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":272,
                  "y":220},
                "size":{
                  "width":440,
                  "height":410},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"4",
                "outerShadow":{
                  "on":true,
                  "offsetX":0,
                  "offsetY":4,
                  "blurRadius":3,
                  "color":{
                    "r":134,
                    "g":134,
                    "b":134,
                    "a":0.219607843137255}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/cadastro/u7.png"}},
{
          "id":"73a4f3f94ec24d0483ac6e0a9ba77bd4",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":302,
              "y":285},
            "size":{
              "width":380,
              "height":45}},
          "adaptiveStyles":{
}},
{
          "id":"2439883eda9e4ed7919d77ff62c611d8",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":302,
              "y":345},
            "size":{
              "width":380,
              "height":45}},
          "adaptiveStyles":{
}},
{
          "id":"40387aec411e4e27853815b1bb0cd06b",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":302,
              "y":404},
            "size":{
              "width":380,
              "height":45}},
          "adaptiveStyles":{
}},
{
          "id":"6fa531ffae5f44779e34c40ac29c31f8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negrito', 'Arial'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF0099FF},
            "location":{
              "x":302,
              "y":560},
            "size":{
              "width":380,
              "height":41},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2bca8ced920646d98501930087b2f84d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negrito', 'Arial'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0099FF},
                "location":{
                  "x":302,
                  "y":560},
                "size":{
                  "width":380,
                  "height":41},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"2"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Link in Current Window",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/cadastro/u12.png"}},
{
          "id":"5f9118113ff94bdaa68166f50bb2823e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":302,
              "y":459},
            "size":{
              "width":350,
              "height":14},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2081501c8cb34fde959116c7f11e8fe4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":302,
                  "y":459},
                "size":{
                  "width":350,
                  "height":14},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"42bd87cc6f6f488cad7a345c64db8644",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":302,
              "y":490},
            "size":{
              "width":380,
              "height":45}},
          "adaptiveStyles":{
}},
{
          "id":"3e5ec4a363884427884992542d602fa4",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":302,
              "y":247},
            "size":{
              "width":253,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9413b49e497547788b7f634efeacea80",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":302,
                  "y":247},
                "size":{
                  "width":253,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b9b7821a3f1547a788f75485dadc7ede",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":358,
              "y":60},
            "size":{
              "width":252,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ece6b525977a4d66a3ac10aa30c1770a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":358,
                  "y":60},
                "size":{
                  "width":252,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/cadastro/u19.png"}}]}},
  "masters":{
    "4226023da38e45578b3ec7ef42593243":{
      "packageId":"4226023da38e45578b3ec7ef42593243",
      "type":"Axure:Master",
      "name":"footer",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"98f6e95fccd74ca4a04a4a23229806bc",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"12px",
              "verticalAlignment":"middle",
              "fill":{
                "fillType":"solid",
                "color":0xFFF2F2F2},
              "location":{
                "x":240,
                "y":0},
              "size":{
                "width":780,
                "height":40}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"4c99a36cd31f4770a5042ff302db729c",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"12px",
                  "verticalAlignment":"middle",
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2},
                  "location":{
                    "x":240,
                    "y":0},
                  "size":{
                    "width":780,
                    "height":40}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/cadastro/u3.png"}}]}}},
  "objectPaths":{
    "9949c8c98a0345a8a576dc06ed3b8f7c":{
      "scriptId":"u0"},
    "93f0dd1839fb462db48be21b7c9a995a":{
      "scriptId":"u1"},
    "686f50f2108646579486669a33caa77c":{
      "scriptId":"u2",
      "98f6e95fccd74ca4a04a4a23229806bc":{
        "scriptId":"u3"},
      "4c99a36cd31f4770a5042ff302db729c":{
        "scriptId":"u4"}},
    "5a30299e0a66494ea0b0d63681bd2d4b":{
      "scriptId":"u5"},
    "b9e99c6f9e3944df93ae299ff296ee90":{
      "scriptId":"u6"},
    "52a5f6f2e4ed45dfa38b998df38bf8d1":{
      "scriptId":"u7"},
    "6bf5c6a4f9674fd7b000a23d06cb25cc":{
      "scriptId":"u8"},
    "73a4f3f94ec24d0483ac6e0a9ba77bd4":{
      "scriptId":"u9"},
    "2439883eda9e4ed7919d77ff62c611d8":{
      "scriptId":"u10"},
    "40387aec411e4e27853815b1bb0cd06b":{
      "scriptId":"u11"},
    "6fa531ffae5f44779e34c40ac29c31f8":{
      "scriptId":"u12"},
    "2bca8ced920646d98501930087b2f84d":{
      "scriptId":"u13"},
    "5f9118113ff94bdaa68166f50bb2823e":{
      "scriptId":"u14"},
    "2081501c8cb34fde959116c7f11e8fe4":{
      "scriptId":"u15"},
    "42bd87cc6f6f488cad7a345c64db8644":{
      "scriptId":"u16"},
    "3e5ec4a363884427884992542d602fa4":{
      "scriptId":"u17"},
    "9413b49e497547788b7f634efeacea80":{
      "scriptId":"u18"},
    "b9b7821a3f1547a788f75485dadc7ede":{
      "scriptId":"u19"},
    "ece6b525977a4d66a3ac10aa30c1770a":{
      "scriptId":"u20"}}});