$axure.loadCurrentPage({
  "url":"detalhe_do_lembrete.html",
  "generationDate":new Date(1421442776147.55),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"f99efc7b568c41b29ccb8b9bd8d5f939",
    "type":"Axure:Page",
    "name":"Detalhe do lembrete",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"c55b641589fa43c8b088ca4aab5d4a57",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "size":{
              "width":980,
              "height":877},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"22d495609e0745e5a0ae69d35940d195",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "size":{
                  "width":980,
                  "height":877},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/senha_feedback1/u0.png"}},
{
          "id":"492198f3888042e88a5b73e8dd5f0adb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":0,
              "y":81},
            "size":{
              "width":200,
              "height":797},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"65650dffe3f245a88d115e48a13e49e4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":0,
                  "y":81},
                "size":{
                  "width":200,
                  "height":797},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/senha_feedback1/u2.png"}},
{
          "id":"cb6e95cdba7d46dcb6b26ef506f17169",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":200,
              "y":837},
            "size":{
              "width":1277,
              "height":33}},
          "adaptiveStyles":{
},
          "masterId":"4226023da38e45578b3ec7ef42593243"},
{
          "id":"f4379b2d037d4dbe884f6787fc0a0436",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"fbc37d401c784c2abad213112443341e"},
{
          "id":"6525dbf0122444d1b4e9292a0e61f076",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":81}},
          "adaptiveStyles":{
},
          "masterId":"be6bc10f038e4524a33637c7abaa0ee1"},
{
          "id":"e1415e5f30734ced897e99a9cb8ebb5e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0x30000000},
            "location":{
              "x":0,
              "y":199},
            "size":{
              "width":200,
              "height":59},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"73c03bb2a54c448f9b9abf8e60aa6b5c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0x30000000},
                "location":{
                  "x":0,
                  "y":199},
                "size":{
                  "width":200,
                  "height":59},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/senha_feedback1/u84.png"}},
{
          "id":"a83c0cfd1e654fd1aa94969a620e0d2c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFCC},
            "location":{
              "x":295,
              "y":280},
            "size":{
              "width":590,
              "height":260},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6beee088becf4d16be572a73bbc16cc4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFCC},
                "location":{
                  "x":295,
                  "y":280},
                "size":{
                  "width":590,
                  "height":260},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/dashboard/u43.png"}}]}},
  "masters":{
    "4226023da38e45578b3ec7ef42593243":{
      "packageId":"4226023da38e45578b3ec7ef42593243",
      "type":"Axure:Master",
      "name":"footer",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"98f6e95fccd74ca4a04a4a23229806bc",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"12px",
              "verticalAlignment":"middle",
              "fill":{
                "fillType":"solid",
                "color":0xFFF2F2F2},
              "location":{
                "x":240,
                "y":0},
              "size":{
                "width":780,
                "height":40}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"4c99a36cd31f4770a5042ff302db729c",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"12px",
                  "verticalAlignment":"middle",
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2},
                  "location":{
                    "x":240,
                    "y":0},
                  "size":{
                    "width":780,
                    "height":40}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/dashboard/u3.png"}}]}},
    "fbc37d401c784c2abad213112443341e":{
      "packageId":"fbc37d401c784c2abad213112443341e",
      "type":"Axure:Master",
      "name":"header_gerente",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"a98ffd8705e040929b7ec88c6bbc264e",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "size":{
                "width":980,
                "height":80},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8ab6195fdb274feb89b20710a3fc5997",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":980,
                    "height":80},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/dashboard/u8.png"}},
{
            "id":"fa8b587736bf4c6ea418fcbeaa262c99",
            "label":"",
            "type":"verticalLine",
            "styleType":"verticalLine",
            "visible":true,
            "style":{
              "location":{
                "x":284,
                "y":0},
              "size":{
                "width":10,
                "height":81},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFE4E4E4}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/dashboard/u10_line.png"}},
{
            "id":"38639eb7baa94a2c8bedf245688e39bd",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":276,
                "y":26},
              "size":{
                "width":28,
                "height":28},
              "borderWidth":"2",
              "borderFill":{
                "fillType":"solid",
                "color":0xFFBCBCBC},
              "cornerRadiusTopLeft":"100"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b1f5768804d347539bfd076bab6dbe28",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":276,
                    "y":26},
                  "size":{
                    "width":28,
                    "height":28},
                  "borderWidth":"2",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFBCBCBC},
                  "cornerRadiusTopLeft":"100"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/dashboard/u11.png"}},
{
            "id":"fe49e2a706744e048a3667060b9a3e69",
            "label":"dropdown-user",
            "type":"dynamicPanel",
            "styleType":"dynamicPanel",
            "visible":true,
            "style":{
              "location":{
                "x":780,
                "y":22},
              "size":{
                "width":200,
                "height":138}},
            "adaptiveStyles":{
},
            "scrollbars":"none",
            "fitToContent":false,
            "propagate":false,
            "diagrams":[{
                "id":"9988237930104c0f96653f270533b92b",
                "label":"State1",
                "type":"Axure:PanelDiagram",
                "objects":[{
                    "id":"6204713e832042c18bfcced89f8bce20",
                    "label":"",
                    "parentDynamicPanel":"fe49e2a706744e048a3667060b9a3e69",
                    "panelIndex":0,
                    "type":"buttonShape",
                    "styleType":"paragraph",
                    "visible":true,
                    "style":{
                      "fontName":"'Helvetica Neue'",
                      "fontSize":"18px",
                      "horizontalAlignment":"right",
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF666666,
                        "opacity":1},
                      "location":{
                        "x":54,
                        "y":18},
                      "size":{
                        "width":92,
                        "height":22}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"62986fe513794f9c8abec46cde2877a7",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"fe49e2a706744e048a3667060b9a3e69",
                        "panelIndex":0,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontName":"'Helvetica Neue'",
                          "fontSize":"18px",
                          "horizontalAlignment":"right",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFF666666,
                            "opacity":1},
                          "location":{
                            "x":54,
                            "y":18},
                          "size":{
                            "width":92,
                            "height":22}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"c076f0909fb542b49a704785b1078434",
                    "label":"",
                    "parentDynamicPanel":"fe49e2a706744e048a3667060b9a3e69",
                    "panelIndex":0,
                    "type":"buttonShape",
                    "styleType":"paragraph",
                    "visible":true,
                    "style":{
                      "fontName":"'Helvetica Neue'",
                      "fontSize":"12px",
                      "horizontalAlignment":"right",
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF666666,
                        "opacity":1},
                      "location":{
                        "x":79,
                        "y":0},
                      "size":{
                        "width":66,
                        "height":14}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"c925cae17de947179805ef69d39926c2",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"fe49e2a706744e048a3667060b9a3e69",
                        "panelIndex":0,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontName":"'Helvetica Neue'",
                          "fontSize":"12px",
                          "horizontalAlignment":"right",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFF666666,
                            "opacity":1},
                          "location":{
                            "x":79,
                            "y":0},
                          "size":{
                            "width":66,
                            "height":14}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"11cf14182664433ebd8e6f1a0ee85ffe",
                    "label":"",
                    "parentDynamicPanel":"fe49e2a706744e048a3667060b9a3e69",
                    "panelIndex":0,
                    "type":"imageBox",
                    "styleType":"imageBox",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":162,
                        "y":4},
                      "size":{
                        "width":28,
                        "height":28}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"9a3f85fce4df4d77b97c4565d725eec5",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"fe49e2a706744e048a3667060b9a3e69",
                        "panelIndex":0,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":162,
                            "y":4},
                          "size":{
                            "width":28,
                            "height":28}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/dashboard/u18.png"}},
{
                    "id":"f6b7572cbf4c448c9f6afbaa10bfad13",
                    "label":"",
                    "parentDynamicPanel":"fe49e2a706744e048a3667060b9a3e69",
                    "panelIndex":0,
                    "type":"imageMapRegion",
                    "styleType":"imageMapRegion",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":155,
                        "y":0},
                      "size":{
                        "width":40,
                        "height":40}},
                    "adaptiveStyles":{
},
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"setPanelState",
                                "description":"Set dropdown-user to State2",
                                "panelsToStates":[{
                                    "panelPath":["fe49e2a706744e048a3667060b9a3e69"],
                                    "stateInfo":{
                                      "setStateType":"diagram",
                                      "stateNumber":2,
                                      "stateValue":{
                                        "exprType":"stringLiteral",
                                        "value":"1",
                                        "stos":[]},
                                      "loop":false,
                                      "showWhenSet":false,
                                      "options":{
                                        "compress":false}}}]}]}]}},
                    "tabbable":true}],
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFFFFF},
                  "image":null,
                  "imageHorizontalAlignment":"near",
                  "imageVerticalAlignment":"near",
                  "imageRepeat":"auto"},
                "adaptiveStyles":{
}},
{
                "id":"5ab577ad4f0d4fea8d6efa85d310a7cd",
                "label":"State2",
                "type":"Axure:PanelDiagram",
                "objects":[{
                    "id":"9ed6828666f447f7a7e0ceb44c3afe85",
                    "label":"",
                    "parentDynamicPanel":"fe49e2a706744e048a3667060b9a3e69",
                    "panelIndex":1,
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFE4E4E4},
                      "location":{
                        "x":0,
                        "y":47},
                      "size":{
                        "width":200,
                        "height":83},
                      "borderFill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "cornerRadiusTopLeft":"5"},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"bd713743a4fd4100b43ccca1b70ca994",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"fe49e2a706744e048a3667060b9a3e69",
                        "panelIndex":1,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFE4E4E4},
                          "location":{
                            "x":0,
                            "y":47},
                          "size":{
                            "width":200,
                            "height":83},
                          "borderFill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "cornerRadiusTopLeft":"5"},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/dashboard/u21.png"}},
{
                    "id":"c45b355677264302bfe15da0b7663744",
                    "label":"",
                    "parentDynamicPanel":"fe49e2a706744e048a3667060b9a3e69",
                    "panelIndex":1,
                    "type":"buttonShape",
                    "styleType":"paragraph",
                    "visible":true,
                    "style":{
                      "fontSize":"14px",
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF0066FF,
                        "opacity":1},
                      "location":{
                        "x":20,
                        "y":58},
                      "size":{
                        "width":170,
                        "height":16},
                      "rotation":"0",
                      "textRotation":"0"},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"3dee6155c57042de849e03626aa42332",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"fe49e2a706744e048a3667060b9a3e69",
                        "panelIndex":1,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontSize":"14px",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFF0066FF,
                            "opacity":1},
                          "location":{
                            "x":20,
                            "y":58},
                          "size":{
                            "width":170,
                            "height":16},
                          "rotation":"0",
                          "textRotation":"0"},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"Open Alterar senha in Current Window",
                                "target":{
                                  "targetType":"page",
                                  "url":"alterar_senha.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"5b7ee831d3d94eb7bcd42535e0e07829",
                    "label":"",
                    "parentDynamicPanel":"fe49e2a706744e048a3667060b9a3e69",
                    "panelIndex":1,
                    "type":"horizontalLine",
                    "styleType":"horizontalLine",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":0,
                        "y":82},
                      "size":{
                        "width":200,
                        "height":10},
                      "borderFill":{
                        "fillType":"solid",
                        "color":0xFFCCCCCC}},
                    "adaptiveStyles":{
},
                    "images":{
                      "start~":"resources/images/transparent.gif",
                      "end~":"resources/images/transparent.gif",
                      "line~":"images/dashboard/u25_line.png"}},
{
                    "id":"78e83a886be14343987e121a22698ce9",
                    "label":"",
                    "parentDynamicPanel":"fe49e2a706744e048a3667060b9a3e69",
                    "panelIndex":1,
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFE4E4E4},
                      "location":{
                        "x":166,
                        "y":36},
                      "size":{
                        "width":20,
                        "height":15},
                      "borderFill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "cornerRadiusTopLeft":"5"},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"048b499446c24a21965e02b1a1c2cda1",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"fe49e2a706744e048a3667060b9a3e69",
                        "panelIndex":1,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFE4E4E4},
                          "location":{
                            "x":166,
                            "y":36},
                          "size":{
                            "width":20,
                            "height":15},
                          "borderFill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "cornerRadiusTopLeft":"5"},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/dashboard/u26.png"}},
{
                    "id":"e07433f9f99a4fcca3478cabd32cb61e",
                    "label":"",
                    "parentDynamicPanel":"fe49e2a706744e048a3667060b9a3e69",
                    "panelIndex":1,
                    "type":"buttonShape",
                    "styleType":"paragraph",
                    "visible":true,
                    "style":{
                      "fontName":"'Helvetica Neue'",
                      "fontSize":"18px",
                      "horizontalAlignment":"right",
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF666666,
                        "opacity":1},
                      "location":{
                        "x":54,
                        "y":18},
                      "size":{
                        "width":92,
                        "height":22}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"87c0a50ec8474ff2a48c7489776d6e3c",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"fe49e2a706744e048a3667060b9a3e69",
                        "panelIndex":1,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontName":"'Helvetica Neue'",
                          "fontSize":"18px",
                          "horizontalAlignment":"right",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFF666666,
                            "opacity":1},
                          "location":{
                            "x":54,
                            "y":18},
                          "size":{
                            "width":92,
                            "height":22}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"1e467f8e63d14e87b4967a32746222e9",
                    "label":"",
                    "parentDynamicPanel":"fe49e2a706744e048a3667060b9a3e69",
                    "panelIndex":1,
                    "type":"buttonShape",
                    "styleType":"paragraph",
                    "visible":true,
                    "style":{
                      "fontName":"'Helvetica Neue'",
                      "fontSize":"12px",
                      "horizontalAlignment":"right",
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF666666,
                        "opacity":1},
                      "location":{
                        "x":79,
                        "y":0},
                      "size":{
                        "width":66,
                        "height":14}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"b19b8a20efe044748b51ac5b68a88f23",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"fe49e2a706744e048a3667060b9a3e69",
                        "panelIndex":1,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontName":"'Helvetica Neue'",
                          "fontSize":"12px",
                          "horizontalAlignment":"right",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFF666666,
                            "opacity":1},
                          "location":{
                            "x":79,
                            "y":0},
                          "size":{
                            "width":66,
                            "height":14}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"b8608e9f638b4660a8a6dee7aa9c3e36",
                    "label":"",
                    "parentDynamicPanel":"fe49e2a706744e048a3667060b9a3e69",
                    "panelIndex":1,
                    "type":"imageBox",
                    "styleType":"imageBox",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":162,
                        "y":4},
                      "size":{
                        "width":28,
                        "height":28}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"a559e57a14854d24a4609485d50f1ed3",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"fe49e2a706744e048a3667060b9a3e69",
                        "panelIndex":1,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":162,
                            "y":4},
                          "size":{
                            "width":28,
                            "height":28}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/dashboard/u18.png"}},
{
                    "id":"fda57ffd0f054a0d897d3b093d669bdd",
                    "label":"",
                    "parentDynamicPanel":"fe49e2a706744e048a3667060b9a3e69",
                    "panelIndex":1,
                    "type":"buttonShape",
                    "styleType":"paragraph",
                    "visible":true,
                    "style":{
                      "fontSize":"14px",
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF0066FF,
                        "opacity":1},
                      "location":{
                        "x":20,
                        "y":99},
                      "size":{
                        "width":170,
                        "height":16},
                      "rotation":"0",
                      "textRotation":"0"},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"5cc804455eb0464b85ff7cc456067800",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"fe49e2a706744e048a3667060b9a3e69",
                        "panelIndex":1,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontSize":"14px",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFF0066FF,
                            "opacity":1},
                          "location":{
                            "x":20,
                            "y":99},
                          "size":{
                            "width":170,
                            "height":16},
                          "rotation":"0",
                          "textRotation":"0"},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"Open Cadastro in Current Window",
                                "target":{
                                  "targetType":"page",
                                  "url":"cadastro.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"a6aab5213b4b4c3e85ac4afe1f257e91",
                    "label":"",
                    "parentDynamicPanel":"fe49e2a706744e048a3667060b9a3e69",
                    "panelIndex":1,
                    "type":"imageMapRegion",
                    "styleType":"imageMapRegion",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":155,
                        "y":0},
                      "size":{
                        "width":40,
                        "height":40}},
                    "adaptiveStyles":{
},
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"setPanelState",
                                "description":"Set dropdown-user to State1",
                                "panelsToStates":[{
                                    "panelPath":["fe49e2a706744e048a3667060b9a3e69"],
                                    "stateInfo":{
                                      "setStateType":"diagram",
                                      "stateNumber":1,
                                      "stateValue":{
                                        "exprType":"stringLiteral",
                                        "value":"1",
                                        "stos":[]},
                                      "loop":false,
                                      "showWhenSet":false,
                                      "options":{
                                        "compress":false}}}]}]}]}},
                    "tabbable":true}],
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFFFFF},
                  "image":null,
                  "imageHorizontalAlignment":"near",
                  "imageVerticalAlignment":"near",
                  "imageRepeat":"auto"},
                "adaptiveStyles":{
}}]},
{
            "id":"da364140f50c47a5a49a390f2c5fa9ae",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "stateStyles":{
                "mouseOver":{
                  "opacity":"0.6"}},
              "location":{
                "x":276,
                "y":26},
              "size":{
                "width":28,
                "height":28}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"93ee0f68a2b948238ef2e6ff71880680",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "stateStyles":{
                    "mouseOver":{
                      "opacity":"0.6"}},
                  "location":{
                    "x":276,
                    "y":26},
                  "size":{
                    "width":28,
                    "height":28}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/dashboard/u37.png",
              "mouseOver~":"images/dashboard/u37.png"}},
{
            "id":"5280f6ab2ff541e3a08d602a96f14af5",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":8,
                "y":22},
              "size":{
                "width":252,
                "height":37}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"62a6cea60ded4fa9a507f5f197608b58",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":8,
                    "y":22},
                  "size":{
                    "width":252,
                    "height":37}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/dashboard/u39.png"}},
{
            "id":"fe5658b4dd484718b4046ef0c1c59a08",
            "label":"",
            "type":"imageMapRegion",
            "styleType":"imageMapRegion",
            "visible":true,
            "style":{
              "size":{
                "width":294,
                "height":81}},
            "adaptiveStyles":{
},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Dashboard in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"dashboard.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true},
{
            "id":"c68a3e19da77499fa30eb2ee99e26c9a",
            "label":"",
            "type":"imageMapRegion",
            "styleType":"imageMapRegion",
            "visible":true,
            "style":{
              "location":{
                "x":270,
                "y":21},
              "size":{
                "width":39,
                "height":39}},
            "adaptiveStyles":{
},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Calendario in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"calendario.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true}]}},
    "be6bc10f038e4524a33637c7abaa0ee1":{
      "packageId":"be6bc10f038e4524a33637c7abaa0ee1",
      "type":"Axure:Master",
      "name":"main-menu",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"4079ac959ca440aea804937b3ce55078",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'Arial Negrito', 'Arial'",
              "fontSize":"12px",
              "fontWeight":"700",
              "horizontalAlignment":"left",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF666666,
                "opacity":1},
              "fill":{
                "fillType":"solid",
                "color":0xFFE4E4E4},
              "paddingTop":"0",
              "paddingBottom":"0",
              "size":{
                "width":200,
                "height":60},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"58fd79ea1bdd410394d0bb63bcd39cb8",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Negrito', 'Arial'",
                  "fontSize":"12px",
                  "fontWeight":"700",
                  "horizontalAlignment":"left",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF666666,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFE4E4E4},
                  "paddingTop":"0",
                  "paddingBottom":"0",
                  "size":{
                    "width":200,
                    "height":60},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Calendario in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"calendario.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/senha_feedback1/u44.png"}},
{
            "id":"06992f228c9d4b33a464660f8f327034",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":170,
                "y":20},
              "size":{
                "width":10,
                "height":17}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"e31194bf27274a02b174f9ea849513d4",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":170,
                    "y":20},
                  "size":{
                    "width":10,
                    "height":17}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/senha_feedback1/u46.png"}},
{
            "id":"9b01bbc4271d4891979c3f56cce02115",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'Arial Negrito', 'Arial'",
              "fontSize":"12px",
              "fontWeight":"700",
              "horizontalAlignment":"left",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF666666,
                "opacity":1},
              "fill":{
                "fillType":"solid",
                "color":0xFFE4E4E4},
              "paddingTop":"0",
              "paddingBottom":"0",
              "location":{
                "x":0,
                "y":60},
              "size":{
                "width":200,
                "height":60},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"5ef1762dd6d545f792321f65a9782898",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Negrito', 'Arial'",
                  "fontSize":"12px",
                  "fontWeight":"700",
                  "horizontalAlignment":"left",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF666666,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFE4E4E4},
                  "paddingTop":"0",
                  "paddingBottom":"0",
                  "location":{
                    "x":0,
                    "y":60},
                  "size":{
                    "width":200,
                    "height":60},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Feedback da agencia in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"feedback_da_agencia.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/senha_feedback1/u44.png"}},
{
            "id":"723488de07994f14b41c36bbf95186a0",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":170,
                "y":80},
              "size":{
                "width":10,
                "height":17}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"ad006440ffb243fbaad55711ba31694f",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":170,
                    "y":80},
                  "size":{
                    "width":10,
                    "height":17}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/senha_feedback1/u46.png"}},
{
            "id":"6390f5fca59b4de185ff7a9f38d41b63",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'Arial Negrito', 'Arial'",
              "fontSize":"12px",
              "fontWeight":"700",
              "horizontalAlignment":"left",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF666666,
                "opacity":1},
              "fill":{
                "fillType":"solid",
                "color":0xFFE4E4E4},
              "paddingTop":"0",
              "paddingBottom":"0",
              "location":{
                "x":0,
                "y":120},
              "size":{
                "width":200,
                "height":60},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"a62d2ed4918d4fa3b1f2407a0aac96a7",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Negrito', 'Arial'",
                  "fontSize":"12px",
                  "fontWeight":"700",
                  "horizontalAlignment":"left",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF666666,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFE4E4E4},
                  "paddingTop":"0",
                  "paddingBottom":"0",
                  "location":{
                    "x":0,
                    "y":120},
                  "size":{
                    "width":200,
                    "height":60},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Lembrete in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"lembrete.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/senha_feedback1/u44.png"}},
{
            "id":"5850271b9e1645fda7b3fb90a636a1a3",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":170,
                "y":140},
              "size":{
                "width":10,
                "height":17}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"fe1a06be89414992a30222af957f9bc4",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":170,
                    "y":140},
                  "size":{
                    "width":10,
                    "height":17}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/senha_feedback1/u46.png"}},
{
            "id":"c777f6d723c4489ea0b0bc7bbf0dc8b4",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'Arial Negrito', 'Arial'",
              "fontSize":"12px",
              "fontWeight":"700",
              "horizontalAlignment":"left",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF666666,
                "opacity":1},
              "fill":{
                "fillType":"solid",
                "color":0xFFE4E4E4},
              "paddingTop":"0",
              "paddingBottom":"0",
              "location":{
                "x":0,
                "y":179},
              "size":{
                "width":200,
                "height":60},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"013b5f21d4f643afbf4f67f56c3521c9",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Negrito', 'Arial'",
                  "fontSize":"12px",
                  "fontWeight":"700",
                  "horizontalAlignment":"left",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF666666,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFE4E4E4},
                  "paddingTop":"0",
                  "paddingBottom":"0",
                  "location":{
                    "x":0,
                    "y":179},
                  "size":{
                    "width":200,
                    "height":60},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Forum in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"forum.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/senha_feedback1/u44.png"}},
{
            "id":"057d2bd8f6e240c9880956331f5206ef",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":170,
                "y":200},
              "size":{
                "width":10,
                "height":17}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"147c3c96b73943e9961b3d0e551383f0",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":170,
                    "y":200},
                  "size":{
                    "width":10,
                    "height":17}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/senha_feedback1/u46.png"}},
{
            "id":"130e77e3ec35413d84c4f11ed9f07403",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'Arial Negrito', 'Arial'",
              "fontSize":"12px",
              "fontWeight":"700",
              "horizontalAlignment":"left",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF666666,
                "opacity":1},
              "fill":{
                "fillType":"solid",
                "color":0xFFE4E4E4},
              "paddingTop":"0",
              "paddingBottom":"0",
              "location":{
                "x":0,
                "y":238},
              "size":{
                "width":200,
                "height":60},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"697dab4436e042bfa8177da83b8a3238",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Negrito', 'Arial'",
                  "fontSize":"12px",
                  "fontWeight":"700",
                  "horizontalAlignment":"left",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF666666,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFE4E4E4},
                  "paddingTop":"0",
                  "paddingBottom":"0",
                  "location":{
                    "x":0,
                    "y":238},
                  "size":{
                    "width":200,
                    "height":60},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Relatorios in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"relatorios.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/senha_feedback1/u44.png"}},
{
            "id":"adb74da283974b20b7e8cd9862790b59",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":170,
                "y":258},
              "size":{
                "width":10,
                "height":17}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"86bd7e7530e34d64a64c511f35511278",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":170,
                    "y":258},
                  "size":{
                    "width":10,
                    "height":17}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/senha_feedback1/u46.png"}},
{
            "id":"a840d7d1315b49b59d1224406cdccedf",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'Arial Negrito', 'Arial'",
              "fontSize":"12px",
              "fontWeight":"700",
              "horizontalAlignment":"left",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF666666,
                "opacity":1},
              "fill":{
                "fillType":"solid",
                "color":0xFFE4E4E4},
              "paddingTop":"0",
              "paddingBottom":"0",
              "location":{
                "x":0,
                "y":297},
              "size":{
                "width":200,
                "height":60},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"94d029530bdc47eaa53ed19d251ed348",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Negrito', 'Arial'",
                  "fontSize":"12px",
                  "fontWeight":"700",
                  "horizontalAlignment":"left",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF666666,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFE4E4E4},
                  "paddingTop":"0",
                  "paddingBottom":"0",
                  "location":{
                    "x":0,
                    "y":297},
                  "size":{
                    "width":200,
                    "height":60},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Campanhas in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"campanhas.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/senha_feedback1/u44.png"}},
{
            "id":"32f346e4a7804d598cef967f1fb615d9",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":170,
                "y":317},
              "size":{
                "width":10,
                "height":17}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"99c6edfdee5f4b29acb6d9a7941fc53f",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":170,
                    "y":317},
                  "size":{
                    "width":10,
                    "height":17}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/senha_feedback1/u46.png"}},
{
            "id":"ba6867a3a67f42bca448dfe446f539e7",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'Arial Negrito', 'Arial'",
              "fontSize":"12px",
              "fontWeight":"700",
              "horizontalAlignment":"left",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF666666,
                "opacity":1},
              "fill":{
                "fillType":"solid",
                "color":0xFFE4E4E4},
              "paddingTop":"0",
              "paddingBottom":"0",
              "location":{
                "x":0,
                "y":356},
              "size":{
                "width":200,
                "height":60},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"861ac089919f4d6a9c52370a44a6d23b",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Negrito', 'Arial'",
                  "fontSize":"12px",
                  "fontWeight":"700",
                  "horizontalAlignment":"left",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF666666,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFE4E4E4},
                  "paddingTop":"0",
                  "paddingBottom":"0",
                  "location":{
                    "x":0,
                    "y":356},
                  "size":{
                    "width":200,
                    "height":60},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Fotos de eventos in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"fotos_de_eventos.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/senha_feedback1/u44.png"}},
{
            "id":"e1e91eda6f5644dc9a57029652a98b6b",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":170,
                "y":376},
              "size":{
                "width":10,
                "height":17}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c743abc9652a4e5dbb10228c50d0c8eb",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":170,
                    "y":376},
                  "size":{
                    "width":10,
                    "height":17}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/senha_feedback1/u46.png"}},
{
            "id":"8b25c0546a5648feb16bfb886c6b622c",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'Arial Negrito', 'Arial'",
              "fontSize":"12px",
              "fontWeight":"700",
              "horizontalAlignment":"left",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF666666,
                "opacity":1},
              "paddingTop":"0",
              "paddingBottom":"0",
              "location":{
                "x":0,
                "y":474},
              "size":{
                "width":200,
                "height":60},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"6968802497484c4797828104b098b742",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Negrito', 'Arial'",
                  "fontSize":"12px",
                  "fontWeight":"700",
                  "horizontalAlignment":"left",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF666666,
                    "opacity":1},
                  "paddingTop":"0",
                  "paddingBottom":"0",
                  "location":{
                    "x":0,
                    "y":474},
                  "size":{
                    "width":200,
                    "height":60},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Usuarios in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"usuarios.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/senha_feedback1/u72.png"}},
{
            "id":"dc78bf928d6a4c07a59e88ef60e12c05",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":170,
                "y":494},
              "size":{
                "width":10,
                "height":17}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"0a43f13a59df48aeaa7d748e2dd25cfb",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":170,
                    "y":494},
                  "size":{
                    "width":10,
                    "height":17}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/senha_feedback1/u46.png"}},
{
            "id":"3585a60620a044819c3b453f78ed5261",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'Arial Negrito', 'Arial'",
              "fontSize":"12px",
              "fontWeight":"700",
              "horizontalAlignment":"left",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF666666,
                "opacity":1},
              "paddingTop":"0",
              "paddingBottom":"0",
              "location":{
                "x":0,
                "y":533},
              "size":{
                "width":200,
                "height":60},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"78fa6202cb234cbf8dea2fa8d0698d2c",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Negrito', 'Arial'",
                  "fontSize":"12px",
                  "fontWeight":"700",
                  "horizontalAlignment":"left",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF666666,
                    "opacity":1},
                  "paddingTop":"0",
                  "paddingBottom":"0",
                  "location":{
                    "x":0,
                    "y":533},
                  "size":{
                    "width":200,
                    "height":60},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Agencias in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"agencias.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/senha_feedback1/u72.png"}},
{
            "id":"10c323e4a9444faf9139876ca9ff556d",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":170,
                "y":553},
              "size":{
                "width":10,
                "height":17}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"f6cf0a4e900b464aa3c014510791ce8e",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":170,
                    "y":553},
                  "size":{
                    "width":10,
                    "height":17}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/senha_feedback1/u46.png"}},
{
            "id":"f5ec13b6bd5d4128af1b9386b75a70c8",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'Arial Negrito', 'Arial'",
              "fontSize":"12px",
              "fontWeight":"700",
              "horizontalAlignment":"left",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF666666,
                "opacity":1},
              "fill":{
                "fillType":"solid",
                "color":0xFFE4E4E4},
              "paddingTop":"0",
              "paddingBottom":"0",
              "location":{
                "x":0,
                "y":415},
              "size":{
                "width":200,
                "height":60},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"f7f373e7e55d40de91bf67f24700cf44",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Negrito', 'Arial'",
                  "fontSize":"12px",
                  "fontWeight":"700",
                  "horizontalAlignment":"left",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF666666,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFE4E4E4},
                  "paddingTop":"0",
                  "paddingBottom":"0",
                  "location":{
                    "x":0,
                    "y":415},
                  "size":{
                    "width":200,
                    "height":60},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Banner da Home in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"banner_da_home.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/senha_feedback1/u44.png"}},
{
            "id":"8c7a27f7cacc44de856fcb6643facd52",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":170,
                "y":437},
              "size":{
                "width":10,
                "height":17}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"cd092d125fbe4520a1d9ed3c96521b3b",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":170,
                    "y":437},
                  "size":{
                    "width":10,
                    "height":17}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/senha_feedback1/u46.png"}}]}}},
  "objectPaths":{
    "c55b641589fa43c8b088ca4aab5d4a57":{
      "scriptId":"u0"},
    "22d495609e0745e5a0ae69d35940d195":{
      "scriptId":"u1"},
    "492198f3888042e88a5b73e8dd5f0adb":{
      "scriptId":"u2"},
    "65650dffe3f245a88d115e48a13e49e4":{
      "scriptId":"u3"},
    "cb6e95cdba7d46dcb6b26ef506f17169":{
      "scriptId":"u4",
      "98f6e95fccd74ca4a04a4a23229806bc":{
        "scriptId":"u5"},
      "4c99a36cd31f4770a5042ff302db729c":{
        "scriptId":"u6"}},
    "f4379b2d037d4dbe884f6787fc0a0436":{
      "scriptId":"u7",
      "a98ffd8705e040929b7ec88c6bbc264e":{
        "scriptId":"u8"},
      "8ab6195fdb274feb89b20710a3fc5997":{
        "scriptId":"u9"},
      "fa8b587736bf4c6ea418fcbeaa262c99":{
        "scriptId":"u10"},
      "38639eb7baa94a2c8bedf245688e39bd":{
        "scriptId":"u11"},
      "b1f5768804d347539bfd076bab6dbe28":{
        "scriptId":"u12"},
      "fe49e2a706744e048a3667060b9a3e69":{
        "scriptId":"u13"},
      "6204713e832042c18bfcced89f8bce20":{
        "scriptId":"u14"},
      "62986fe513794f9c8abec46cde2877a7":{
        "scriptId":"u15"},
      "c076f0909fb542b49a704785b1078434":{
        "scriptId":"u16"},
      "c925cae17de947179805ef69d39926c2":{
        "scriptId":"u17"},
      "11cf14182664433ebd8e6f1a0ee85ffe":{
        "scriptId":"u18"},
      "9a3f85fce4df4d77b97c4565d725eec5":{
        "scriptId":"u19"},
      "f6b7572cbf4c448c9f6afbaa10bfad13":{
        "scriptId":"u20"},
      "9ed6828666f447f7a7e0ceb44c3afe85":{
        "scriptId":"u21"},
      "bd713743a4fd4100b43ccca1b70ca994":{
        "scriptId":"u22"},
      "c45b355677264302bfe15da0b7663744":{
        "scriptId":"u23"},
      "3dee6155c57042de849e03626aa42332":{
        "scriptId":"u24"},
      "5b7ee831d3d94eb7bcd42535e0e07829":{
        "scriptId":"u25"},
      "78e83a886be14343987e121a22698ce9":{
        "scriptId":"u26"},
      "048b499446c24a21965e02b1a1c2cda1":{
        "scriptId":"u27"},
      "e07433f9f99a4fcca3478cabd32cb61e":{
        "scriptId":"u28"},
      "87c0a50ec8474ff2a48c7489776d6e3c":{
        "scriptId":"u29"},
      "1e467f8e63d14e87b4967a32746222e9":{
        "scriptId":"u30"},
      "b19b8a20efe044748b51ac5b68a88f23":{
        "scriptId":"u31"},
      "b8608e9f638b4660a8a6dee7aa9c3e36":{
        "scriptId":"u32"},
      "a559e57a14854d24a4609485d50f1ed3":{
        "scriptId":"u33"},
      "fda57ffd0f054a0d897d3b093d669bdd":{
        "scriptId":"u34"},
      "5cc804455eb0464b85ff7cc456067800":{
        "scriptId":"u35"},
      "a6aab5213b4b4c3e85ac4afe1f257e91":{
        "scriptId":"u36"},
      "da364140f50c47a5a49a390f2c5fa9ae":{
        "scriptId":"u37"},
      "93ee0f68a2b948238ef2e6ff71880680":{
        "scriptId":"u38"},
      "5280f6ab2ff541e3a08d602a96f14af5":{
        "scriptId":"u39"},
      "62a6cea60ded4fa9a507f5f197608b58":{
        "scriptId":"u40"},
      "fe5658b4dd484718b4046ef0c1c59a08":{
        "scriptId":"u41"},
      "c68a3e19da77499fa30eb2ee99e26c9a":{
        "scriptId":"u42"}},
    "6525dbf0122444d1b4e9292a0e61f076":{
      "scriptId":"u43",
      "4079ac959ca440aea804937b3ce55078":{
        "scriptId":"u44"},
      "58fd79ea1bdd410394d0bb63bcd39cb8":{
        "scriptId":"u45"},
      "06992f228c9d4b33a464660f8f327034":{
        "scriptId":"u46"},
      "e31194bf27274a02b174f9ea849513d4":{
        "scriptId":"u47"},
      "9b01bbc4271d4891979c3f56cce02115":{
        "scriptId":"u48"},
      "5ef1762dd6d545f792321f65a9782898":{
        "scriptId":"u49"},
      "723488de07994f14b41c36bbf95186a0":{
        "scriptId":"u50"},
      "ad006440ffb243fbaad55711ba31694f":{
        "scriptId":"u51"},
      "6390f5fca59b4de185ff7a9f38d41b63":{
        "scriptId":"u52"},
      "a62d2ed4918d4fa3b1f2407a0aac96a7":{
        "scriptId":"u53"},
      "5850271b9e1645fda7b3fb90a636a1a3":{
        "scriptId":"u54"},
      "fe1a06be89414992a30222af957f9bc4":{
        "scriptId":"u55"},
      "c777f6d723c4489ea0b0bc7bbf0dc8b4":{
        "scriptId":"u56"},
      "013b5f21d4f643afbf4f67f56c3521c9":{
        "scriptId":"u57"},
      "057d2bd8f6e240c9880956331f5206ef":{
        "scriptId":"u58"},
      "147c3c96b73943e9961b3d0e551383f0":{
        "scriptId":"u59"},
      "130e77e3ec35413d84c4f11ed9f07403":{
        "scriptId":"u60"},
      "697dab4436e042bfa8177da83b8a3238":{
        "scriptId":"u61"},
      "adb74da283974b20b7e8cd9862790b59":{
        "scriptId":"u62"},
      "86bd7e7530e34d64a64c511f35511278":{
        "scriptId":"u63"},
      "a840d7d1315b49b59d1224406cdccedf":{
        "scriptId":"u64"},
      "94d029530bdc47eaa53ed19d251ed348":{
        "scriptId":"u65"},
      "32f346e4a7804d598cef967f1fb615d9":{
        "scriptId":"u66"},
      "99c6edfdee5f4b29acb6d9a7941fc53f":{
        "scriptId":"u67"},
      "ba6867a3a67f42bca448dfe446f539e7":{
        "scriptId":"u68"},
      "861ac089919f4d6a9c52370a44a6d23b":{
        "scriptId":"u69"},
      "e1e91eda6f5644dc9a57029652a98b6b":{
        "scriptId":"u70"},
      "c743abc9652a4e5dbb10228c50d0c8eb":{
        "scriptId":"u71"},
      "8b25c0546a5648feb16bfb886c6b622c":{
        "scriptId":"u72"},
      "6968802497484c4797828104b098b742":{
        "scriptId":"u73"},
      "dc78bf928d6a4c07a59e88ef60e12c05":{
        "scriptId":"u74"},
      "0a43f13a59df48aeaa7d748e2dd25cfb":{
        "scriptId":"u75"},
      "3585a60620a044819c3b453f78ed5261":{
        "scriptId":"u76"},
      "78fa6202cb234cbf8dea2fa8d0698d2c":{
        "scriptId":"u77"},
      "10c323e4a9444faf9139876ca9ff556d":{
        "scriptId":"u78"},
      "f6cf0a4e900b464aa3c014510791ce8e":{
        "scriptId":"u79"},
      "f5ec13b6bd5d4128af1b9386b75a70c8":{
        "scriptId":"u80"},
      "f7f373e7e55d40de91bf67f24700cf44":{
        "scriptId":"u81"},
      "8c7a27f7cacc44de856fcb6643facd52":{
        "scriptId":"u82"},
      "cd092d125fbe4520a1d9ed3c96521b3b":{
        "scriptId":"u83"}},
    "e1415e5f30734ced897e99a9cb8ebb5e":{
      "scriptId":"u84"},
    "73c03bb2a54c448f9b9abf8e60aa6b5c":{
      "scriptId":"u85"},
    "a83c0cfd1e654fd1aa94969a620e0d2c":{
      "scriptId":"u86"},
    "6beee088becf4d16be572a73bbc16cc4":{
      "scriptId":"u87"}}});